### ISSUE TITLE
Develop Sigma rules for Atomic Red Team test (Linux)

### ISSUE THREAD

**Issue by yugoslavskiy** [SigmaHQ/sigma#1011]
- Subject: [Atomic Red Team project](https://github.com/redcanaryco/atomic-red-team/)
- Author: @redcanaryco
- Type: threat simulation tests
- Requirements: Create one Pull Request per Sigma rule
- Pro tip: Consider developing Sigma rules for both Linux and [macOS](https://github.com/Neo23x0/sigma/issues/1012) tests concurrently. There are lots for intersections, and you can kill two birds in one stone 

Please comment the issue with a task number that you are going to work out so the others will not intersect with you.

| Task #  | ATT&CK Technique name/link                                                                    | ART test link                                                                                     | Comment                                             |
|:-------:|-----------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------:|-----------------------------------------------------|
| 1       | [T1014](https://attack.mitre.org/techniques/T1014): Rootkit                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1014/T1014.md)         | this task could take a huge amount of time to solve |
| 2       | [T1016](https://attack.mitre.org/techniques/T1016): System Network Configuration Discovery    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1016/T1016.md)         |                                                     |
| 3       | [T1018](https://attack.mitre.org/techniques/T1018): Remote System Discovery                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1018/T1018.md)         |                                                     |
| 4       | [T1027](https://attack.mitre.org/techniques/T1027): Obfuscated Files or Information           | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1027/T1027.md)         |                                                     |
| 5       | [T1027.001](https://attack.mitre.org/techniques/T1027/001): Binary Padding                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1027.001/T1027.001.md) |                                                     |
| 6       | [T1030](https://attack.mitre.org/techniques/T1030): Data Transfer Size Limits                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1030/T1030.md)         |                                                     |
| 7       | [T1046](https://attack.mitre.org/techniques/T1046): Network Service Scanning                  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1046/T1046.md)         |                                                     |
| 8       | [T1049](https://attack.mitre.org/techniques/T1049): System Network Connections Discovery      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1049/T1049.md)         |                                                     |
| 9       | [T1053.001](https://attack.mitre.org/techniques/T1053/001): At (Linux)                        | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1053.001/T1053.001.md) |                                                     |
| 10      | [T1053.003](https://attack.mitre.org/techniques/T1053/003): Cron                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1053.003/T1053.003.md) |                                                     |
| 11      | [T1057](https://attack.mitre.org/techniques/T1057): Process Discovery                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1057/T1057.md)         |                                                     |
| 12      | [T1069.001](https://attack.mitre.org/techniques/T1069/001): Local Groups                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1069.001/T1069.001.md) |                                                     |
| 13      | [T1070.002](https://attack.mitre.org/techniques/T1070/002): Clear Linux or Mac System Logs    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.002/T1070.002.md) |                                                     |
| 14      | [T1070.004](https://attack.mitre.org/techniques/T1070/004): File Deletion                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.004/T1070.004.md) |                                                     |
| 15      | [T1070.006](https://attack.mitre.org/techniques/T1070/006): Timestomp                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.006/T1070.006.md) |                                                     |
| 16      | [T1071.001](https://attack.mitre.org/techniques/T1071/001): Web Protocols                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1071.001/T1071.001.md) |                                                     |
| 17      | [T1082](https://attack.mitre.org/techniques/T1082): System Information Discovery              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1082/T1082.md)         |                                                     |
| 18      | [T1083](https://attack.mitre.org/techniques/T1083): File and Directory Discovery              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1083/T1083.md)         |                                                     |
| 19      | [T1087.001](https://attack.mitre.org/techniques/T1087/001): Local Account                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1087.001/T1087.001.md) |                                                     |
| 20      | [T1090.001](https://attack.mitre.org/techniques/T1090/001): Internal Proxy                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1090.001/T1090.001.md) |                                                     |
| 21      | [T1113](https://attack.mitre.org/techniques/T1113): Screen Capture                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1113/T1113.md)         |                                                     |
| 22      | [T1135](https://attack.mitre.org/techniques/T1135): Network Share Discovery                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1135/T1135.md)         |                                                     |
| 23      | [T1176](https://attack.mitre.org/techniques/T1176): Browser Extensions                        | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1176/T1176.md)         |                                                     |
| 24      | [T1201](https://attack.mitre.org/techniques/T1201): Password Policy Discovery                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1201/T1201.md)         |                                                     |
| 25      | [T1217](https://attack.mitre.org/techniques/T1217): Browser Bookmark Discovery                | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1217/T1217.md)         |                                                     |
| 26      | [T1518.001](https://attack.mitre.org/techniques/T1518/001): Security Software Discovery       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518.001/T1518.001.md) |                                                     |
| 27      | [T1529](https://attack.mitre.org/techniques/T1529): System Shutdown/Reboot                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1529/T1529.md)         |                                                     |
| 28      | [T1546.005](https://attack.mitre.org/techniques/T1546/005): Trap                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.005/T1546.005.md) |                                                     |
| 29      | [T1547.006](https://attack.mitre.org/techniques/T1547/006): Kernel Modules and Extensions     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1547.006/T1547.006.md) | this task could take a huge amount of time to solve |
| 30      | [T1548.001](https://attack.mitre.org/techniques/T1548/001): Setuid and Setgid                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1548.001/T1548.001.md) |                                                     |
| 31      | [T1548.003](https://attack.mitre.org/techniques/T1548/003): Sudo and Sudo Caching             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1548.003/T1548.003.md) |                                                     |
| 32      | [T1552.001](https://attack.mitre.org/techniques/T1552/001): Credentials In Files              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.001/T1552.001.md) |                                                     |
| 33      | [T1552.003](https://attack.mitre.org/techniques/T1552/003): Bash History                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.003/T1552.003.md) |                                                     |
| 34      | [T1552.004](https://attack.mitre.org/techniques/T1552/004): Private Keys                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.004/T1552.004.md) |                                                     |
| 35      | [T1553.004](https://attack.mitre.org/techniques/T1553/004): Install Root Certificate          | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1553.004/T1553.004.md) |                                                     |
| 36      | [T1562.001](https://attack.mitre.org/techniques/T1562/001): Disable or Modify Tools           | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md) | this task could take a huge amount of time to solve |
| 37      | [T1562.003](https://attack.mitre.org/techniques/T1562/003): HISTCONTROL                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.003/T1562.003.md) |                                                     |
| 38      | [T1562.004](https://attack.mitre.org/techniques/T1562/004): Disable or Modify System Firewall | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.004/T1562.004.md) |                                                     |
| 39      | [T1564.001](https://attack.mitre.org/techniques/T1564/001): Hidden Files and Directories      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1564.001/T1564.001.md) |                                                     |

**Comment by omergunal** [comment]
35

**Comment by alejandroortuno** [comment]
Taking task 10: T1053.003: Cron

**Comment by alejandroortuno** [comment]
Taking:

19	T1087.001: Local Account
12	T1069.001: Local Groups

**Comment by weslambert** [comment]
I can take 7,22

**Comment by alejandroortuno** [comment]
Taking

38 	T1562.004: Disable or Modify System Firewall
3 	T1018: Remote System Discovery

**Comment by fitsigor** [comment]
Taking:
5. T1027.001: Binary Padding
6. T1030: Data Transfer Size Limits
7. T1046: Network Service Scanning
15. T1070.006: Timestomp
27  T1529: System Shutdown/Reboot
32. T1552.001: Credentials In Files

**Comment by weslambert** [comment]
@fitsigor Im already working on 7 😄

**Comment by fitsigor** [comment]
> 
> 
> @fitsigor Im already working on 7 😄

ok, didn't notice

**Comment by alx1m1k** [comment]
Taking
33  T1552.003: Bash History

**Comment by alejandroortuno** [comment]
@fitsigor I took T1046 Network Service Scanning on MacOs but I see you have it on Linux. As rules should be the same, let me know if you want to also take the Macos one.

**Comment by yugoslavskiy** [comment]
I'll work out:

- 3: T1027: Obfuscated Files or Information
- 14: T1049: System Network Connections Discovery
- 28: T1083: File and Directory Discovery
- 41: T1518.001: Security Software Discovery

**Comment by alejandroortuno** [comment]
@fitsigor done T1046 Network Service Scanning for Linux as it seems the same as for MacOS:

https://github.com/Neo23x0/sigma/pull/1257
