### ISSUE TITLE
Develop Sigma rules for Atomic Red Team test (macOS)

### ISSUE THREAD

**Issue by yugoslavskiy** [SigmaHQ/sigma#1012]
- Subject: [Atomic Red Team project](https://github.com/redcanaryco/atomic-red-team/)
- Author: @redcanaryco
- Type: threat simulation tests
- Requirements: Create one Pull Request per Sigma rule
- Pro tip: Consider developing Sigma rules for both macOS and [Linux](https://github.com/Neo23x0/sigma/issues/1011) tests concurrently. There are lots for intersections, and you can kill two birds in one stone 

Please comment the issue with a task number that you are going to work out so the others will not intersect with you.

| Task # | ATT&CK Technique name/link                                                                                          | ART test link                                                                                     |
|:------:|---------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------:|
| 1    | [T1016](https://attack.mitre.org/techniques/T1016): System Network Configuration Discovery                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1016/T1016.md)         |
| 2    | [T1018](https://attack.mitre.org/techniques/T1018): Remote System Discovery                                           | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1018/T1018.md)         |
| 3    | [T1027](https://attack.mitre.org/techniques/T1027): Obfuscated Files or Information                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1027/T1027.md)         |
| 4    | [T1027.001](https://attack.mitre.org/techniques/T1027/001): Binary Padding                                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1027.001/T1027.001.md) |
| 5    | [T1030](https://attack.mitre.org/techniques/T1030): Data Transfer Size Limits                                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1030/T1030.md)         |
| 6    | [T1033](https://attack.mitre.org/techniques/T1033): System Owner/User Discovery                                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1033/T1033.md)         |
| 7    | [T1036.006](https://attack.mitre.org/techniques/T1036/006): Space after Filename                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1036.006/T1036.006.md) |
| 8    | [T1037.002](https://attack.mitre.org/techniques/T1037/002): Logon Script (Mac)                                        | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1037.002/T1037.002.md) |
| 9    | [T1037.004](https://attack.mitre.org/techniques/T1037/004): Rc.common                                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1037.004/T1037.004.md) |
| 10   | [T1037.005](https://attack.mitre.org/techniques/T1037/005): Startup Items                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1037.005/T1037.005.md) |
| 11   | [T1040](https://attack.mitre.org/techniques/T1040): Network Sniffing                                                  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1040/T1040.md)         |
| 12   | [T1046](https://attack.mitre.org/techniques/T1046): Network Service Scanning                                          | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1046/T1046.md)         |
| 13   | [T1048.003](https://attack.mitre.org/techniques/T1048/003): Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1048.003/T1048.003.md) |
| 14   | [T1049](https://attack.mitre.org/techniques/T1049): System Network Connections Discovery                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1049/T1049.md)         |
| 15   | [T1053.003](https://attack.mitre.org/techniques/T1053/003): Cron                                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1053.003/T1053.003.md) |
| 16   | [T1053.004](https://attack.mitre.org/techniques/T1053/004): Launchd                                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1053.004/T1053.004.md) |
| 17   | [T1056.002](https://attack.mitre.org/techniques/T1056/002): GUI Input Capture                                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1056.002/T1056.002.md) |
| 18   | [T1057](https://attack.mitre.org/techniques/T1057): Process Discovery                                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1057/T1057.md)         |
| 19   | [T1059.002](https://attack.mitre.org/techniques/T1059/002): AppleScript                                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.002/T1059.002.md) |
| 20   | [T1059.004](https://attack.mitre.org/techniques/T1059/004): Unix Shell                                                | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.004/T1059.004.md) |
| 21   | [T1069.001](https://attack.mitre.org/techniques/T1069/001): Local Groups                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1069.001/T1069.001.md) |
| 22   | [T1070.002](https://attack.mitre.org/techniques/T1070/002): Clear Linux or Mac System Logs                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.002/T1070.002.md) |
| 23   | [T1070.003](https://attack.mitre.org/techniques/T1070/003): Clear Command History                                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.003/T1070.003.md) |
| 24   | [T1070.004](https://attack.mitre.org/techniques/T1070/004): File Deletion                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.004/T1070.004.md) |
| 25   | [T1070.006](https://attack.mitre.org/techniques/T1070/006): Timestomp                                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.006/T1070.006.md) |
| 26   | [T1071.001](https://attack.mitre.org/techniques/T1071/001): Web Protocols                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1071.001/T1071.001.md) |
| 27   | [T1082](https://attack.mitre.org/techniques/T1082): System Information Discovery                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1082/T1082.md)         |
| 28   | [T1083](https://attack.mitre.org/techniques/T1083): File and Directory Discovery                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1083/T1083.md)         |
| 29   | [T1087.001](https://attack.mitre.org/techniques/T1087/001): Local Account                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1087.001/T1087.001.md) |
| 30   | [T1090.001](https://attack.mitre.org/techniques/T1090/001): Internal Proxy                                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1090.001/T1090.001.md) |
| 31   | [T1105](https://attack.mitre.org/techniques/T1105): Ingress Tool Transfer                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1105/T1105.md)         |
| 32   | [T1113](https://attack.mitre.org/techniques/T1113): Screen Capture                                                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1113/T1113.md)         |
| 33   | [T1135](https://attack.mitre.org/techniques/T1135): Network Share Discovery                                           | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1135/T1135.md)         |
| 34   | [T1136.001](https://attack.mitre.org/techniques/T1136/001): Local Account                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1136.001/T1136.001.md) |
| 35   | [T1176](https://attack.mitre.org/techniques/T1176): Browser Extensions                                                | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1176/T1176.md)         |
| 36   | [T1201](https://attack.mitre.org/techniques/T1201): Password Policy Discovery                                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1201/T1201.md)         |
| 37   | [T1217](https://attack.mitre.org/techniques/T1217): Browser Bookmark Discovery                                        | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1217/T1217.md)         |
| 38   | [T1222.002](https://attack.mitre.org/techniques/T1222/002): Linux and Mac File and Directory Permissions Modification | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1222.002/T1222.002.md) |
| 39   | [T1485](https://attack.mitre.org/techniques/T1485): Data Destruction                                                  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1485/T1485.md)         |
| 40   | [T1518](https://attack.mitre.org/techniques/T1518): Software Discovery                                                | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518/T1518.md)         |
| 41   | [T1518.001](https://attack.mitre.org/techniques/T1518/001): Security Software Discovery                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518.001/T1518.001.md) |
| 42   | [T1529](https://attack.mitre.org/techniques/T1529): System Shutdown/Reboot                                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1529/T1529.md)         |
| 43   | [T1543.001](https://attack.mitre.org/techniques/T1543/001): Launch Agent                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1543.001/T1543.001.md) |
| 44   | [T1543.004](https://attack.mitre.org/techniques/T1543/004): Launch Daemon                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1543.004/T1543.004.md) |
| 45   | [T1546.004](https://attack.mitre.org/techniques/T1546/004): .bash_profile and .bashrc                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.004/T1546.004.md) |
| 46   | [T1546.005](https://attack.mitre.org/techniques/T1546/005): Trap                                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.005/T1546.005.md) |
| 47   | [T1546.014](https://attack.mitre.org/techniques/T1546.014): Emond                                                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.014/T1546.014.md) |
| 48   | [T1547.007](https://attack.mitre.org/techniques/T1547/007): Re-opened Applications                                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1547.007/T1547.007.md) |
| 49   | [T1547.011](https://attack.mitre.org/techniques/T1547.011): Plist Modification                                        | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1547.011/T1547.011.md) |
| 50   | [T1548.001](https://attack.mitre.org/techniques/T1548/001): Setuid and Setgid                                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1548.001/T1548.001.md) |
| 51   | [T1548.003](https://attack.mitre.org/techniques/T1548/003): Sudo and Sudo Caching                                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1548.003/T1548.003.md) |
| 52   | [T1552.001](https://attack.mitre.org/techniques/T1552/001): Credentials In Files                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.001/T1552.001.md) |
| 53   | [T1552.003](https://attack.mitre.org/techniques/T1552/003): Bash History                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.003/T1552.003.md) |
| 54   | [T1552.004](https://attack.mitre.org/techniques/T1552/004): Private Keys                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.004/T1552.004.md) |
| 55   | [T1553.001](https://attack.mitre.org/techniques/T1553/001): Gatekeeper Bypass                                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1553.001/T1553.001.md) |
| 56   | [T1553.004](https://attack.mitre.org/techniques/T1553/004): Install Root Certificate                                  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1553.004/T1553.004.md) |
| 57   | [T1555.001](https://attack.mitre.org/techniques/T1555/001): Keychain                                                  | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.001/T1555.001.md) |
| 58   | [T1555.003](https://attack.mitre.org/techniques/T1555/003): Credentials from Web Browsers                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.003/T1555.003.md) |
| 59   | [T1560.001](https://attack.mitre.org/techniques/T1560/001): Archive via Utility                                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1560.001/T1560.001.md) |
| 60   | [T1562.001](https://attack.mitre.org/techniques/T1562/001): Disable or Modify Tools                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.001/T1562.001.md) |
| 61   | [T1562.003](https://attack.mitre.org/techniques/T1562/003): HISTCONTROL                                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1562.003/T1562.003.md) |
| 62   | [T1564.001](https://attack.mitre.org/techniques/T1564/001): Hidden Files and Directories                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1564.001/T1564.001.md) |
| 63   | [T1564.002](https://attack.mitre.org/techniques/T1564/002): Hidden Users                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1564.002/T1564.002.md) |
| 64   | [T1569.001](https://attack.mitre.org/techniques/T1569/001): Launchctl                                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1569.001/T1569.001.md) |

**Comment by alejandroortuno** [comment]
Taking task 15:  T1053.003: Cron

**Comment by remotephone** [comment]
Taking task T1016: System Network Configuration Discovery

There is no ART docs for macOS, I'll start there and then create sigma rules for both platforms.

**Comment by alejandroortuno** [comment]
Taking:

21	T1069.001: Local Groups
29	T1087.001: Local Account
34	T1136.001: Local Account

**Comment by omergunal** [comment]
I will take:


36 - T1201: Password Policy Discovery

**Comment by yugoslavskiy** [comment]
I'll work out 63.

**Comment by remotephone** [comment]
Taking  22  - T1070.002: Clear Linux or Mac System Logs

**Comment by alejandroortuno** [comment]
Taking:

10 	T1037.005: Startup Items
11 	T1040: Network Sniffing
12 	T1046: Network Service Scanning
16 	T1053.004: Launchd
19 	T1059.002: AppleScript

**Comment by remotephone** [comment]
Taking T1056.002: GUI Input Capture

**Comment by remotephone** [comment]
Taking:
Task 32 - T1113: Screen Capture

**Comment by alx1m1k** [comment]
Taking 
53  T1552.003: Bash History

**Comment by alejandroortuno** [comment]
Taking: 

Task 47  T1546.014: Emond

**Comment by alx1m1k** [comment]
Taking:
4 | T1027.001: Binary Padding
5 | T1030: Data Transfer Size Limits
25 | T1070.006: Timestomp
42 | T1529: System Shutdown/Reboot
52 | T1552.001: Credentials In Files

**Comment by tim1234567** [comment]
Taking "T1555.001: Keychain".

**Comment by yugoslavskiy** [comment]
I'll work out:

**Comment by alejandroortuno** [comment]
Out of timing for the sprint but as I am already doing it for Linux, will also take:

Task 2 T1018: Remote System Discovery
