### ISSUE TITLE
Develop Sigma rules for Atomic Red Team test (Windows)

### ISSUE THREAD

**Issue by yugoslavskiy** [SigmaHQ/sigma#1013]
- Subject: [Atomic Red Team project](https://github.com/redcanaryco/atomic-red-team/)
- Author: @redcanaryco
- Type: threat simulation tests
- Requirements: Create one Pull Request per Sigma rule

Please comment the issue with a task number that you are going to work out so the others will not intersect with you.

| Task #  | ATT&CK Technique name/link                                                                                           | ART test link                                                                                     | Comment                                             |
|:-------:|----------------------------------------------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------:|-----------------------------------------------------|
| 1       | [T1531](https://attack.mitre.org/techniques/T1531): Account Access Removal                                           | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1531/T1531.md)         |                                                     |
| 2       | [T1048.003](https://attack.mitre.org/techniques/T1048/003): Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1048.003/T1048.003.md) |                                                     |
| 3       | [T1546.002](https://attack.mitre.org/techniques/T1546/002): Screensaver                                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1546.002/T1546.002.md) |                                                     |
| 4       | [T1056.001](https://attack.mitre.org/techniques/T1056/001): Keylogging                                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1056.001/T1056.001.md) |                                                     |
| 5       | [T1552.004](https://attack.mitre.org/techniques/T1552/004): Private Keys                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1552.004/T1552.004.md) |                                                     |
| 6       | [T1070.005](https://attack.mitre.org/techniques/T1070/005): Network Share Connection Removal                         | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1070.005/T1070.005.md) |                                                     |
| 7       | [T1074.001](https://attack.mitre.org/techniques/T1074/001): Local Data Staging                                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1074.001/T1074.001.md) |                                                     |
| 8       | [T1095](https://attack.mitre.org/techniques/T1095): Non-Application Layer Protocol                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1095/T1095.md)         |                                                     |
| 9       | [T1114.001](https://attack.mitre.org/techniques/T1114/001): Local Email Collection                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1114.001/T1114.001.md) |                                                     |
| 10      | [T1115](https://attack.mitre.org/techniques/T1115): Clipboard Data                                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1115/T1115.md)         |                                                     |
| 11      | [T1119](https://attack.mitre.org/techniques/T1119): Automated Collection                                             | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1119/T1119.md)         |                                                     |
| 12      | [T1553.004](https://attack.mitre.org/techniques/T1553/004): Install Root Certificate                                 | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1553.004/T1553.004.md) |                                                     |
| 13      | [T1176](https://attack.mitre.org/techniques/T1176): Browser Extensions                                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1176/T1176.md)         |                                                     |
| 14      | [T1216](https://attack.mitre.org/techniques/T1216): Signed Script Proxy Execution                                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1216/T1216.md)         |                                                     |
| 15      | [T1216.001](https://attack.mitre.org/techniques/T1216/001): PubPrn                                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1216.001/T1216.001.md) |                                                     |
| 16      | [T1217](https://attack.mitre.org/techniques/T1217): Browser Bookmark Discovery                                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1217/T1217.md)         |                                                     |
| 17      | [T1518](https://attack.mitre.org/techniques/T1518): Software Discovery                                               | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518/T1518.md)         |                                                     |
| 18      | [T1518.001](https://attack.mitre.org/techniques/T1518/001): Security Software Discovery                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1518.001/T1518.001.md) |                                                     |
| 19      | [T1010](https://attack.mitre.org/techniques/T1010): Application Window Discovery                                     | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1010/T1010.md)         | this task could take a huge amount of time to solve |
| 20      | [T1055.004](https://attack.mitre.org/techniques/T1055/004): Asynchronous Procedure Call                              | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1055.004/T1055.004.md) | this task could take a huge amount of time to solve |
| 21      | [T1056.004](https://attack.mitre.org/techniques/T1056/004): Credential API Hooking                                   | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1056.004/T1056.004.md) | this task could take a huge amount of time to solve |
| 22      | [T1134.004](https://attack.mitre.org/techniques/T1134/004): Parent PID Spoofing                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1134.004/T1134.004.md) | this task could take a huge amount of time to solve |
| 23      | [T1555.003](https://attack.mitre.org/techniques/T1555/003): Credentials from Web Browsers                            | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.003/T1555.003.md) | this task could take a huge amount of time to solve |
| 24      | [T1556.002](https://attack.mitre.org/techniques/T1556/002): Password Filter DLL                                      | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1556.002/T1556.002.md) | this task could take a huge amount of time to solve |
| 25      | [T1559.002](https://attack.mitre.org/techniques/T1559/002): Dynamic Data Exchange                                    | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1559.002/T1559.002.md) | this task could take a huge amount of time to solve |
| 26      | [T1574.009](https://attack.mitre.org/techniques/T1574/009): Path Interception by Unquoted Path                       | [link](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1574.009/T1574.009.md) | this task could take a huge amount of time to solve |

**Comment by svch0stz** [comment]
6 - T1070.005: Network Share Connection Removal
12 - T1553.004: Install Root Certificate

**Comment by bczyz1** [comment]
2 - T1048.003: Exfiltration Over Unencrypted/Obfuscated Non-C2 Protocol

**Comment by bczyz1** [comment]
3 - T1546.002: Screensaver

**Comment by bczyz1** [comment]
4 - T1056.001: Keylogging

**Comment by NikitaStormwind** [comment]
17

**Comment by nasbench** [comment]
Closing this as complete.

As @frack113 mentioned Windows atomic tests are "all" covered in SIGMA and are constantly being updated/monitored for any new additions.
