### ISSUE TITLE
Folder structure on Linux Sigma Rules

### ISSUE THREAD

**Issue by alejandroortuno** [SigmaHQ/sigma#1048]
Hi,

Following the Linux sigma rules, I noticed that the folder structure for the rules is as follows:

linux
- auditd
- modsecurity

Although several rules not in the `auditd` folder but are using the `service: auditd` see for example `lnx_pers_systemd_reload.yml`.

Also thinking about the `unix` rules that might fit in the Linux / Macos solution as per https://github.com/Neo23x0/sigma/issues/1012 so the right folder structure can be in place for them.

**Comment by yugoslavskiy** [comment]
Hello @alejandroortuno!

Good point.
I believe that it make sense to change the file structure to the following:

```
rules
├── unix-like
│   ├── linux
│   │   ├── file_event
│   │   ├── process_creation
|   │   └── etc
│   └── macos
│       ├── file_event
│       ├── process_creation
|       └── etc
├── etc
```

Unix-like is the root, as both Linux and macOS are originated from Unix:

![2880px-Unix_history-simple svg](https://user-images.githubusercontent.com/13090109/95271169-83ab4900-083d-11eb-9abf-885e6f9a24f5.png)


As you might notice, I also propose to get rid of the `auditd` folder.
There are many logging tools/shippers (audit log, osquery, autidbeat, etc) that actually generate pretty much the same kind of events, that could be unified under the categories (`process_creation`, `file_event`), just like it was done for windows events.

@Neo23x0 @thomaspatzke what do you guys think?

**Comment by alejandroortuno** [comment]
Hi @yugoslavskiy,

When I was doing https://github.com/Neo23x0/sigma/pull/1091 when covering the atomic test, I noticed that there are specific ones that the same command will work on both macOs & Linux and other commands will be specific to each OS.

I think we can be good to assume, commands that works on both OS types, that they are a `unix` flavour and can go on the root folder structure, where specific ones can go each on their individual folders - ie Linux / MacOs.

I separated the into three separated folder although I have seen https://github.com/Neo23x0/sigma/pull/1086 from @remotephone is adding all under the same file. 

Might be worth getting into an agreement or at least a convention for the file naming to include the OS flavour.

**Comment by remotephone** [comment]
I'll update the pull request either way, but it might make sense to split them out and just have some duplicate logic or search terms within the rules but still allow people to deploy only the rules for platforms that they use. I think, in general, Linux would be more likely to be monitored by auditd like solutions and macOS more likely to be monitored by an EDR solution so it would make sense to have rules that can be deployed independently.

**Comment by thomaspatzke** [comment]
I fully agree, the Linux/Unix area in this repository needs some attention 😉 

To summarize and complete, there are few inconsistencies:

* Misassigned rules (auditd rules not in auditd folder)
* Inconsistent field naming
* modsecurity is not Linux not Unix. It also runs under Windows and belongs in the web folder
* Too many keyword rules assuming there's no structure, which is indeed the case for Unix logging. This is more a meta-problem, as we not only have to agree on a field naming scheme but also on specific parsing.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
