### ISSUE TITLE
syntax help: how to count for a fix number of  events seen with the same Source IP, Destination Port and different Destination IP in X minutes

### ISSUE THREAD

**Issue by happyCodingGirl-XD** [SigmaHQ/sigma#1255]
Hi,

I am new to SIGMA.  I looked at all the examples and rules in the project, but couldn't find an example of how to count for a number of  events seen with the same Source IP, Destination Port and different Destination IP in X minutes.  Usually, it goes like this in the condition section:
count(dst_ip) by src_ip > 40  # this counts the different destination ip from the same source
but how to specify "same Source IP, Destination Port and different Destination IP "?

Thanks

**Comment by thomaspatzke** [comment]
This is currently not possible in Sigma but might change in the future.
