### ISSUE TITLE
Trouble with logical operators AND(OR) 

### ISSUE THREAD

**Issue by mt1189** [SigmaHQ/sigma#1326]
Forgive me for not finding it else where. It's hard for me to search this issue. 

Anyway I am needing to achieve this logic. 

(((command_line:"exe" OR process_name:"exe" OR process_parent:"exe" OR file_company:"exe" OR file_product:"exe") AND (NOT (process_parent:"svc" OR command_line:("svc" OR "service")))) **AND (NOT ((client:x AND (hostname:host or username:user))**

I was able to achieve this by specifying the following:

<pre>
detection:
    condition: exe_included and not filter_legit and not (filter_client_id and filter_client_user)
    exe_included:
        - command_line: exe
        - process_name: exe
    filter_legit:
        - process_parent: parent
        - command_line:
            - svc
            - service
    filter_client_1_id:
        clientid:
            - client_1
    filter_client_1_user:
        - hostname: host
        - domain_username: user
</pre>

Is there a better way to achieve the bolded statement? or is this the proper approach?

I assumed for a couple hundred troubleshooting attempts that the following should work:
<pre>
    filter_client:
          clientid: client   
              - hostname: host
              - domain_username: user
</pre>
But I was met with this error:

 is no valid YAML: mapping values are not allowed here

Thanks for assisting if you can!

**Comment by thomaspatzke** [comment]
I think the rules are more readable if you don't nest detections into YAML structures but split the different condition parts into separate detections and refer to them in a condition.
