### ISSUE TITLE
Pass the Hash Activity - query

### ISSUE THREAD

**Issue by kowsikbabu** [SigmaHQ/sigma#1328]
In pass the hash activity, the actual detection goes like this:

_detection:
    selection:
        - EventID: 4624
          LogonType: '3'
          LogonProcessName: 'NtLmSsp'
          WorkstationName: '%Workstations%'
          ComputerName: '%Workstations%'
        - EventID: 4625
          LogonType: '3'
          LogonProcessName: 'NtLmSsp'
          WorkstationName: '%Workstations%'
          ComputerName: '%Workstations%'_

In this we have MACRO like value '%Workstations%', is this the actual value to be printed in the eventviewer, or does this represent an actual workstation name.

a)
 Process Information:
	Process ID:		0x0
	Process Name:		-

Network Information:
	Workstation Name:	%Workstations%
	Source Network Address:	10.154.12.53
	Source Port:		53384

Detailed Authentication Information:
	Logon Process:		Kerberos
	Authentication Package:	Kerberos
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0
	

OR 

b)
Process Information:
	Process ID:		0x0
	Process Name:		-

Network Information:
	Workstation Name:	CONTOSOLOCAL
	Source Network Address:	10.154.12.53
	Source Port:		53384

Detailed Authentication Information:
	Logon Process:		Kerberos
	Authentication Package:	Kerberos
	Transited Services:	-
	Package Name (NTLM only):	-
	Key Length:		0

**Comment by thomaspatzke** [comment]
These are placeholders which should represent the list of workstations or workstation patterns.

Placeholders are not supported by the current converter, the next release will support them.
