### ISSUE TITLE
Add support for LogRhythm

### ISSUE THREAD

**Issue by HackerzWorkshop** [SigmaHQ/sigma#1333]
Hi, 
I would like to suggest adding LogRhythm to your supported platforms.
You can use as a reference the following article: 
https://github.com/LogRhythm-Labs/Sigma

**Comment by thegoatreich** [comment]
I'm interested and willing to attempt help.

**Comment by thegoatreich** [comment]
I have a working win event config for LogRhythm using Lucene with a slightly modded es-ql backend. If you're interested I'll send a pull request.

**Comment by thegoatreich** [comment]
#1705

**Comment by frack113** [comment]
Hi, Can be close ?

**Comment by frack113** [comment]
No reply
