### ISSUE TITLE
Regexes aren't supported? If not pls add full support

### ISSUE THREAD

**Issue by micioffe** [SigmaHQ/sigma#1347]
Hello.
It's a great tool with great capabilities, but I am afraid regular expressions aren't fully supported and wiki is poor on description of that
for example, I need to check a registry event for base 64 encoded value
logsource:
  product: windows
  service: security

detection:
  selection1:
      EventID: 
         - 4657
 
      New Value:
          - '^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$'
      
 
   
  condition: selection1

As you can see there is right regex to check string for base 64 pattern, but when I translate it into SIEM search I receive

For QRADAR
SELECT UTF8(payload) as search_payload from events where LOGSOURCETYPENAME(devicetype)='Microsoft Windows Security Event Log' and ("EventID" = '4657') and ("New Value" **ilike '^([A-Za-z0-9+/]{4})%([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$')**

FOR Splank
(source="WinEventLog:Security" (EventCode="4657") (New Value=**"^([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$"))**

And so on. Seems it searches it not as a regex, but rather as an exact string, which shouldn't happen, if I specify 'string', which should use regexes

upd:
regexes that match any number of characters, like .* or [/s/S]?* are shown as part of a string with or without escape characters respectively:

*\:\\[\".*\"].cs - > \\\[\\\".*\\\"\].cs*
 *\:.*.cs -> *\\\:.*.cs*

**Comment by thomaspatzke** [comment]
Regular expressions must be declared with the *re* modifier, e.g.: `fieldname|re: reg.*ex`. Currently regular expressions aren't supported by all backends, especially not by the Splunk backend.
