### ISSUE TITLE
Not able to run sigmac tool inside a dockerized container

### ISSUE THREAD

**Issue by patraabinash** [SigmaHQ/sigma#1352]
Team,
I am trying to use the `sigmac` tool and build a few apis around it. I tried putting this in a docker container and provided the `sigmatools` pip package in the conda `environment.yml`. I wrote a python script which is internally using `subprocess` library to call  the `sigmac` tool inside the container. When the container is started , the python script is run is over a gunicorn server. It throws the following error:
`Traceback (most recent call last):
  File "/opt/miniconda3/envs/<env_name>/bin/sigmac", line 5, in <module>
    from sigma.sigmac import main
ModuleNotFoundError: No module named 'sigma.sigmac'`

But, if I exec into the container, activate the conda environment and the run the `sigmac` command from the command line, it works perfectly fine.
I am not really sure what's happening here. Any help will be greatly appreciated.

**Comment by thomaspatzke** [comment]
I'm not familar with this specific setup (conda etc.), but it seems to me that Sigma and your webapp reside within different virtual environments or use different Python interpreters.

By the way, the Sigma converter can also be used as library. I think this should work better than calling sigmac with subprocess.
