### ISSUE TITLE
[Feature Request] Sigmac filter

### ISSUE THREAD

**Issue by V1D1AN** [SigmaHQ/sigma#1353]
Hello,

can you add the possibility to make a "not" in the "filter" function of sigmac.

Exemple: 
/root/sigma/tools/sigmac -t elastalert -c /root/file.yml --backend-config /root/backend.yml -o /tmp/rule.yml -r /root/sigma/rules/linux/ --filter logsource=auth and not logsource=syslog

or 

/root/sigma/tools/sigmac -t elastalert -c /root/file.yml --backend-config /root/backend.yml -o /tmp/rule.yml -r /root/sigma/rules/linux/ --filter logsource!=guacamole

Thanks to the Sigma team

**Comment by frack113** [comment]
Hello,
I am working on the filter #1497.
Use the **'not'** seen a bit hard for me, but I can try to  add a new filter `logsource!=`

**Comment by wagga40** [comment]
I think it is simpler with `logsource!=` and I think it follows the way the "--filter" was originally designed to work.

**Comment by V1D1AN** [comment]
Thanks frack113
