### ISSUE TITLE
[Feature Request] Using sigma rules directly on endpoint

### ISSUE THREAD

**Issue by tanguySnoeck** [SigmaHQ/sigma#1401]
Hello,

I am working on a sysmon events analysis tool and I would like to use sigma rules as part of the project. 
Do you have any advice on how to best parse sigma rules against a list of sysmon events on a local computer ?

**Comment by wagga40** [comment]
Hi, 

you can try my tool wich has been made exactly for this use case : [https://github.com/wagga40/Zircolite](https://github.com/wagga40/Zircolite)

**Comment by thomaspatzke** [comment]
The sigmac PowerShell backend could be used for this or the [THOR APT Scanner](https://www.nextron-systems.com/thor/)
