### ISSUE TITLE
Replace full path with *lsass.exe

### ISSUE THREAD

**Issue by jaegeral** [SigmaHQ/sigma#1457]
I think replacing the fullpath in 
 https://github.com/SigmaHQ/sigma/blob/c877a9a68dc9aca87dc849f75b0c49f676e03409/rules/windows/create_remote_thread/sysmon_password_dumper_lsass.yml#L15

With ```*lsass.exe``` might be more robust esp if people have installed windows on something else then c:

**Comment by frack113** [comment]
I agree , but in best practice way :
`TargetImage|endswith: '\lsass.exe'`
