### ISSUE TITLE
Rule: suspicious msiexec directory

### ISSUE THREAD

**Issue by TekBear** [SigmaHQ/sigma#1468]
re: https://github.com/SigmaHQ/sigma/pull/528

Is this a false positive and if so is this rule really worth getting a "HIGH" rating?

https://www.mumble.info/downloads/
  Mumble Version 1.3.4 (x86)
  https://dl.mumble.info/latest/stable/client-windows-x86
    https://www.virustotal.com/gui/file/eb2f452dccaa60f64409356815f7ee834aa07823f92410eefe3a2628cf90d52e/detection

**Comment by Karneades** [comment]
Current rule is https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_susp_msiexec_cwd.yml which has a filter set which was missing in the initial PR. Could you give some more details about the process path of your msiexec.exe?

**Comment by TekBear** [comment]
Just from virus total scan there was a message latest scan is clear. Assume was fixed.
