### ISSUE TITLE
Need help in creating sigma rules

### ISSUE THREAD

**Issue by shrishti01** [SigmaHQ/sigma#1501]
Hi all,
I am new to creating sigma rules, please help in making the sigma rules
 for the file attached.
[sigma.txt](https://github.com/SigmaHQ/sigma/files/6530218/sigma.txt)

**Comment by frack113** [comment]
Hello,
Rule are agains log so I use to works with the windows events.

### artefact
command_line contains : \temp\\
process_name endwith: lsass.exe

**Comment by shrishti01** [comment]
Hi,
How can I convert this sigma rule for the SIEM system.

**Comment by nasbench** [comment]
Hi and thanks for opening the issue.

As @frack113 said SIGMA is written against log entries and other outputs. An example of a log entry would: `auditd`, `access logs`, `Windows event logs`...etc.

Perhaps you could re-execute the sample and collect windows logs and check if there is anything interesting in there that can be used as an anchor for detection or behaviour.

To get started with writing SIGMA rules I suggest you take a look at the following repo called [SIGMA Resources](https://github.com/nasbench/SIGMA-Resources/). Which contains multiple resources around sigma and how to get started. If you have specific issues or any further questions you are more than welcome to open a new issue and we would happily answer it as best we can.

Regarding your last question on how to convert SIGMA rules to SIEM system. There are a couple of options you could use but the easiest that I could suggest to get started is using a tool like [uncoder.io](https://uncoder.io/). You simply need to plug the sigma rule on the left and choose the SIEM on the right and click **translate**

Once you are familiar with this you could take a look at tools like [SIGMAC](https://github.com/SigmaHQ/sigma/blob/master/tools/README.md) (which will be soon end of life) or [PySIGMA](https://github.com/SigmaHQ/pySigma/) (which is the supported way on how to translate SIGMA rules into different SIEM/EDR backends)

Hope this helps and thanks for your contribution :)
