### ISSUE TITLE
all https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/ links are dead or outdated

### ISSUE THREAD

**Issue by zambomarcell** [SigmaHQ/sigma#1507]
please upgrade the rule referers because all https://github.com/Cyb3rWard0g/ThreatHunter-Playbook/ links are dead.

For examle:
https://github.com/OTRF/ThreatHunter-Playbook/tree/master/playbooks/windows/06_credential_access/T1003_credential_dumping/domain_dpapi_backupkey_extraction.md -> 404

thx, bye

**Comment by Neo23x0** [comment]
Let's see if someone finds the time to fix this some day.

**Comment by zambomarcell** [comment]
Hi, may i fixing?

**Comment by StevenDias33** [comment]
> Let's see if someone finds the time to fix this some day.

Hi someone did that and opened up a PR for it :D 

#1498
