### ISSUE TITLE
Proposal for update sysmon.yml with missing EventID

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#1525]
###  Purpose

I want to cover the events of sysmon not taken into account in the mapping

### current state

[sysmon.yml](https://github.com/SigmaHQ/sigma/blob/master/tools/config/generic/sysmon.yml)

product | category | EventID
-------- | --------- | ---------
windows | process_creation | 1
windows | SYSMON_FILE_TIME |
windows | network_connection | 3
windows | SYSMON_SERVICE_STATE_CHANGE | 
windows | process_termination | 5
windows | driver_load | 6
windows | image_load | 7
windows | create_remote_thread | 8
windows | raw_access_thread | 9
windows | process_access | 10
windows | file_event | 11
windows | registry_event | 12, 13, 14 
windows | create_stream_hash | 15
windows | SYSMONEVENT_SERVICE_CONFIGURATION_CHANGE |
windows | pipe_created | 17, 18
windows | wmi_event | 19, 20, 21
windows | dns_query | 22
windows | file_delete  | 23
windows | SYSMON_CLIPBOARD |
windows | SYSMON_PROCESS_IMAGE_TAMPERING |
windows | SYSMON_ERROR |

### Proposal

EventID | Sysmon name | Sigma category
-------- | --------- | ---------
2 | SYSMON_FILE_TIME | [file_change](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/file-create-time-change.md)
4 | SYSMON_SERVICE_STATE_CHANGE | [sysmon_status](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/operational-events.md)
16 | SYSMONEVENT_SERVICE_CONFIGURATION_CHANGE | [sysmon_status](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/operational-events.md)
24 | SYSMON_CLIPBOARD | [clipboard_capture](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/clipboard-capture.md)
25 | SYSMON_PROCESS_IMAGE_TAMPERING | [process_tampering](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/process-tampering.md)
255 | SYSMON_ERROR | [sysmon_status](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/operational-events.md)

### End words

don't hesitate to share your opinion

**Comment by thomaspatzke** [comment]
Looks good!

**Comment by frack113** [comment]
PR Merged
