### ISSUE TITLE
IP Ranges

### ISSUE THREAD

**Issue by mgraf444** [SigmaHQ/sigma#1536]
Is there a way to define IP ranges in a rule? Example: [1.1.1.0 to 1.1.1.255] It doesn't look like it based on the examples in the repo here but wanted to double check. Excluding 1918 IP addresses seems pretty tedious and length in the examples found in the repo.

**Comment by Karneades** [comment]
Such a feature is unknown to me. One possibility would be to use regex, but many backends lack that feature. But you would be able to document and share that and everyone has to convert themselves into the correct regex form in their backends.

**Comment by Karneades** [comment]
I had a similar thought recently, how to exclude the three private IP ranges in a rule.

**Comment by frack113** [comment]
Hi,
I have push #1563 to add a new modifiers to convert CIDR to list of ip.
It should do the trick.

**Comment by frack113** [comment]
It is in the new https://pypi.org/project/pysigma/
