### ISSUE TITLE
Sigma Rule Constraints

### ISSUE THREAD

**Issue by mgraf444** [SigmaHQ/sigma#1537]
Wondering if there are any constraints with the Sigma rules, example if its a process based rule focusing on parent and child processes and their command lines and other attributes, can I also filter on a network connection IP address or domain the child process may have made or does it have to be focused on one event type only (e.g. process creation, or network connection).

**Comment by frack113** [comment]
Hi,
The ultimate goal of sigma rules is to be converted to a SIEM.
To keep the greatest compatibility, it is better to make simple rules by category.
It is better to avoid regex `|re:` as not all support it.
You can look [sysmon_abusing_windows_telemetry_for_persistence.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/sysmon/sysmon_abusing_windows_telemetry_for_persistence.yml),if you convert it you get 2 rules from the file.
Or you make 2 files like : 
- sysmon_abusing_windows_telemetry_for_persistence_registry.yml
- sysmon_abusing_windows_telemetry_for_persistence_creation.yml

I hope I was useful

**Comment by frack113** [comment]
More information here : https://github.com/SigmaHQ/sigma-specification
