### ISSUE TITLE
Support for Datadog Backend

### ISSUE THREAD

**Issue by annapauxdog** [SigmaHQ/sigma#1559]
I'm trying to gauge interest in having a Datadog backend for Sigma. Datadog is a monitoring service that allows querying logs and alerting on detections. https://www.datadoghq.com/

For example, the [aws_cloudtrail_disable_logging rule](https://github.com/SigmaHQ/sigma/blob/master/rules/cloud/aws_cloudtrail_disable_logging.yml) could end up looking like:
`service:cloudtrail @eventSource:cloudtrail.amazonaws.com @eventName:(StopLogging OR UpdateTrail OR DeleteTrail)`

Is there interest in this feature?

**Comment by austinsonger** [comment]
@annapauxdog 

Curious... Why?

Datadog literally has a rule already just for your example
- https://docs.datadoghq.com/security_platform/default_rules/cloudtrail-aws-cloudtrail-configuration-modified/

**Comment by Neo23x0** [comment]
Maybe for the rest of the rules? My guess is that the mentioned rule just served as an example.

**Comment by annapauxdog** [comment]
Update: We just merged the Datadog backend! 🎉 https://github.com/SigmaHQ/sigma/pull/2514 
Apologies for the late reply - yes now any Sigma query can be converted into Datadog's Log Search Syntax.
