### ISSUE TITLE
MSI Spawned Cmd and Powershell Spawned Processes - Invalid Field

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#1646]
For the rule located at [rules/windows/process_creation/sysmon_always_install_elevated_msi_spawned_cmd_and_powershell_spawned_processes.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/sysmon_always_install_elevated_msi_spawned_cmd_and_powershell_spawned_processes.yml), there is an invalid field - `ParentOfParentImage`.

There does not appear to be another way to have this rule, since there is no field in Sysmon that represents the parent process of the parent's process, from my understanding.

**Comment by frack113** [comment]
Hi,
it is not a invalid field but a custom field :cry:
So this rule is useless ...

**Comment by leegengyu** [comment]
@frack113 I see.

Since the rule cannot be used, should it be deleted/deprecated then? (Is there such a practice?)

**Comment by frack113** [comment]
While not more in rules-unsupported.
And add

 ```
ref  https://www.slideshare.net/heirhabarov/hunting-for-privilege-escalation-in-windows-environment
Works only if  Enrich Sysmon events with additional information about process Result of enrichment with information about process 
```
