### ISSUE TITLE
CarbonBlack modifiers not honored on sigmac exe

### ISSUE THREAD

**Issue by marcurdy** [SigmaHQ/sigma#1653]
The "contains", "endswith", "startswith" are not being honored for CB outputs. Here's an example with cb and splunk. With Splunk, you can see it injecting the leading wildcard.

**./sigmac -c splunk-windows --target splunk ../rules/windows/process_creation/win_mshta_spawn_shell.yml**
(ParentImage="*\\mshta.exe" ((Image="*\\cmd.exe" OR Image="*\\powershell.exe" OR Image="*\\wscript.exe" OR Image="*\\cscript.exe" OR Image="*\\sh.exe" OR Image="*\\bash.exe" OR Image="*\\reg.exe" OR Image="*\\regsvr32.exe") OR (Image="*\\BITSADMIN*"))) | table CommandLine,ParentCommandLine

**./sigmac --target carbonblack -c carbon-black-eedr ../rules/windows/process_creation/win_mshta_spawn_shell.yml**
(parent_name:\\mshta.exe AND ((process_name:\\cmd.exe OR process_name:\\powershell.exe OR process_name:\\wscript.exe OR process_name:\\cscript.exe OR process_name:\\sh.exe OR process_name:\\bash.exe OR process_name:\\reg.exe OR process_name:\\regsvr32.exe) OR (process_internal_name:\\cmd.exe OR process_internal_name:\\powershell.exe OR process_internal_name:\\wscript.exe OR process_internal_name:\\cscript.exe OR process_internal_name:\\sh.exe OR process_internal_name:\\bash.exe OR process_internal_name:\\reg.exe OR process_internal_name:\\regsvr32.exe) OR (process_name:\\BITSADMIN) OR (process_internal_name:\\BITSADMIN)))

**Comment by frack113** [comment]
Hi,
Got this https://developer.carbonblack.com/resources/query_overview.pdf
page 4
```
Leading Wildcards
The use of leading wildcards in a query is not recommended unless absolutely necessary, and is blocked by default.
Leading wildcards carry a significant performance penalty for the search.
For example, the following query is notrecommended:
filemod:*/system32/ntdll.dll
The same results would be returned by thefollowing query, and the search would be much more efficient:
filemod:system32/ntdll.dll
```

**Comment by marcurdy** [comment]
Testing that I see it does substrings. This wouldn't work in Splunk, but it
does for CB.

e.g. event_type:filemod process_name:windows\\explorer.exe

Thanks.
