### ISSUE TITLE
Winlogbeat (modules enabled) Config - Hash-related Fields

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#1668]
In #1667, `Imphash` was addressed in a straightforward manner.

However, in the same configuration file (`winlogbeat-modules-enabled.yml`), there are 2 other hash-related fields:

1. Line 142 - `Hashes: winlog.event_data.Hashes`
2. Line 143 - `file_hash: winlog.event_data.Hashes`

In Winlogbeat's Sysmon processor module found at https://raw.githubusercontent.com/elastic/beats/master/x-pack/winlogbeat/module/sysmon/config/winlogbeat-sysmon.js, we see at line 423 that `winlog.event_data.Hashes` is removed via `evt.Delete(hashField);`. This is because the parameter `hashField` contains the value `winlog.event_data.Hashes` as seen in lines 445 and 453.

In place of `winlog.event_data.Hashes`, for non-Imphash hashes, there is either `process.hash.md5` or `process.hash.sha256`. There is also the `related.hash` field which contains all the types of hashes (if present) as its value.

Thus, I think lines 142 and 143 in `winlogbeat-modules-enabled.yml` requires updating, in coordination with the updating of the rules that uses hashes as well.

**Comment by frack113** [comment]
So the best way should be to use `related.hash`.

**Comment by leegengyu** [comment]
@frack113 Not so sure about that. If we use `related.hash`, we would have to pre-process the field's contents, because `related.hash` may contain more than 1 type of hash. Also, the hash is always prepended with the hash name (i.e. the field's value could be `MD5=[MD5_hash]`), even if Sysmon is configured to collect 1 type of hash.

From what I understand, the field which it should be mapped to would depend on what hash is used by the rule. In non-Imphash cases, as long as not all rules (that make use of hash as a detection) use the same hash, the field cannot cover all cases. In such a situation, supposing that most of these rules use MD5 hash in the detection, then perhaps using `process.hash.md5` can cover most of the hash-related rules.

Disclaimer: I did not find out what is the most common type of hash used prior to my above comments (or if there is actually only 1 type of hash used in hash-related detection rules).

**Comment by frack113** [comment]
If I were force to write a rule with an md5 hash of sysmon, I would write : 
```
 Hashes|contains|all:
    - 'MD5='
    - '7c0ee77d537c9b08ff4ab64a5f5e8693'
OR
 Hashes|contains: 'MD5=7c0ee77d537c9b08ff4ab64a5f5e8693'

NEVER
 MD5: '7c0ee77d537c9b08ff4ab64a5f5e8693'
```

Because:

1. SIGMA rule must be universal (not splunk or ELK...)
2. Allways use original name field , use mapping for the SIEM
3. it's a bad idea to think that hashes are THE solution to rule detection for my point of view

So trouble here is **winlogbeat** alter original information and don't keep it...

**Comment by leegengyu** [comment]
@frack113 Agreed! Thanks so much for clarifying it in a clear manner.

(due to my inexperience with Sigma rules, did not know that those options that you spelt out were available)

**Comment by frack113** [comment]
HI, 
Get the same trouble with user in windows log 'domain\user' in winlogbeat user.user AND user.domain :unamused:
@leegengyu  thanks your your works on mapping

**Comment by frack113** [comment]
Hi, 
I am testing some config in winlogbeat-modules-enabled.yml
```yaml
    # SYSMON Hashes
    Hashes: winlog.event_data.Hashes
    # extraction from Hashes not original field
    md5:
        category=process_creation: process.hash.md5
        category=driver_load: hash.md5
        category=image_load: file.hash.md5
        category=file_delete: process.hash.md5
        category=clipboard_capture: process.hash.md5
    sha256:
        category=process_creation: process.hash.sha256
        category=driver_load: hash.sha256
        category=image_load: file.hash.sha256
        category=file_delete: process.hash.sha256
        category=clipboard_capture: process.hash.sha256
    imphash: 
        category=process_creation: process.pe.imphash
        category=driver_load: hash.imphash
        category=image_load: file.hash.imphash
        category=file_delete: process.pe.imphash
        category=clipboard_capture: process.hash.imphash
```
But when convert `md5: 'Azerty'` get a ` AND process.hash.md5:("AZERTY" OR "azerty")` 😒
