### ISSUE TITLE
Winlogbeat (modules not enabled) Config - Hash-related Fields

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#1670]
In #1669, the mapping was changed only this basis:
* that the `winlog.event_data.Imphash` field does not exist in a log where Winlogbeat's modules are not enabled (in particular, the Sysmon module), and
* that the `winlog.event_data.Hashes` field exists instead.

However, this change is only a dirty fix, and for users who do not use Winlogbeat's Sysmon module, this rule does not appear to work for them because the `winlog.event_data.Hashes` field does not contain the hash alone.

If the machine's Sysmon is configured such that all events with event ID 1 will display all the available type of hashes, this value will be seen in `winlog.event_data.Hashes` - `MD5=[value],SHA256=[value],IMPHASH=[value]`.

Even if Sysmon is configured such that only imphashes are captured in the events, the value will still contain the `IMPHASH=` prefix.

Not sure how to fix the above for such a use-case, or if it is just a limitation that rules using such hashes will not work for users who do not use Winlogbeat's Sysmon module.

**Comment by frack113** [comment]
Hi,
As it is merged you can close it.
Thanks

**Comment by leegengyu** [comment]
The main issue remains (despite the PR), but I will still close this issue since there appears to be no resolution in the near-term.

Thanks @frack113!
