### ISSUE TITLE
auditd rules

### ISSUE THREAD

**Issue by small-greenfinger** [SigmaHQ/sigma#1677]
Are all of auditd rules required to write config in audit.rules?

**Comment by frack113** [comment]
I'm only use one time auditd but look at  https://github.com/Neo23x0/auditd

**Comment by nasbench** [comment]
> Are all of auditd rules required to write config in audit.rules?

If you're using a service like the default `auditd` on CentOS or similar. Then the rules are located on `audit.rules` and are read from the location `/etc/audit/rules.d/audit.rules`. If you use elastic then you might use a tool like auditbeat which will replace auditd as the client for the logs and the location of the rules can be set from a config file. 

Whatever you choose the location of the rules is documented in the docs and SIGMA is independent of that.

To give you a quick explanation. The auditd rules found in the SigmaHQ repository use a log source called `service: auditd`. This log source is mapped to different backends here are a couple of examples.

- [Hawk Config](https://github.com/SigmaHQ/sigma/blob/14cb2f32eb714f08006a07d325409fc872e2a564/tools/config/hawk.yml#L83-L85)
- [ECS Auditd](https://github.com/SigmaHQ/sigma/blob/14cb2f32eb714f08006a07d325409fc872e2a564/tools/config/ecs-auditd.yml#L16-L21)
- [ECS Auditbeat](https://github.com/SigmaHQ/sigma/blob/14cb2f32eb714f08006a07d325409fc872e2a564/tools/config/ecs-auditbeat-modules-enabled.yml#L16-L21)

During rule conversion, SIGMA will convert the rules based on these fields and it has nothing to do with the configuration of `auditd` on a system. 

So you can use whatever you like just make sure that everything is set up correctly.

Hope this helps.
