### ISSUE TITLE
Monitoring For Persistence Via BITS - Query's Regex

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#1685]
For [this rule](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/win_monitoring_for_persistence_via_bits.yml), it uses regex for detection.

First, Sigmac was used to convert the rule.

The relevant options that I used include:
* `-t es-rule`
* `-c tools/config/generic/sysmon.yml`
* `-c tools/config/winlogbeat-modules-enabled.yml`
* `--backend-option keyword_field=""`

The query produced by Sigmac results in this query (for use in Elasticsearch):

`((winlog.event_id:1 AND winlog.channel:Microsoft\-Windows\-Sysmon\/Operational) AND (process.command_line:/(?i).*bitsadmin.*/SetNotifyCmdLine.*(%COMSPEC%|cmd.exe|regsvr32.exe).*/ OR process.command_line:/(?i).*bitsadmin.*/Addfile.*(http|https|ftp|ftps):.*/))`

In Elasticsearch, it gives false positives in many cases:

Example 1:
`process.command_line`: `""C:\Program Files\[snipped]""`

Example 2:
`process.command_line`: `"rundll32.exe AppXDeploymentExtensions.OneCore.dll,ShellRefresh"`

Example 3:
`process.command_line`: `"C:\WINDOWS\system32\rundll32.exe sysmain.dll,PfSvWsSwapAssessmentTask"`

**Comment by frack113** [comment]
Hi,
I've test in kibana v 7.13.3: 
- process.command_line:/.\*/ua.\*/ :red_circle:
- process.command_line:/.\*\\/ua.\*/ :heavy_check_mark:

So can you check if this query work ?
```
((winlog.event_id:1 AND winlog.channel:Microsoft\-Windows\-Sysmon\/Operational) AND (process.command_line:/(?i).*bitsadmin.*\/SetNotifyCmdLine.*(%COMSPEC%|cmd.exe|regsvr32.exe).*/ OR process.command_line:/(?i).*bitsadmin.*\/Addfile.*(http|https|ftp|ftps):.*/))
```

**Comment by leegengyu** [comment]
Thanks @frack113! I do not have the above-mentioned false-positives anymore.

(did not test out the true positives though)

**Comment by frack113** [comment]
Thanks @leegengyu , 
I have to update the rule as the regex is not good. (test on **https://regex101.com/**)
