### ISSUE TITLE
Devo is not recognized as a valid target

### ISSUE THREAD

**Issue by JDownham** [SigmaHQ/sigma#1765]
Error output:

sigmac.py: error: argument --target/-t: invalid choice: 'devo'

steps to reproduce

Download latest branch

pip3 install sigmatools

./sigmac.py -t devo -c ../config/devo-network.yml ../../rules/network/net_dns_c2_detection.yml 
./sigmac.py -O devo.py -t devo -c ../config/devo-network.yml ../../rules/network/net_dns_c2_detection.yml 
./sigmac.py -O devo.py -t devo -c ../config/devo-network.yml ../../rules/network/net_dns_c2_detection.yml -I -d

Note as per the readme:
_For example, in order to translate a windows-related Sigma rule, one would use:_

tools/sigmac -t devo -c tools/config/devo-windows.yml rules/windows/sysmon/sysmon_wmi_susp_scripting.yml

produces same error:

sigmac.py: error: argument --target/-t: invalid choice: 'devo' (choose from 'sumologic', 'netwitness', 'crowdstrike', 'sqlite', 'sumologic-cse', 'sumologic-cse-rule', 'arcsight', 'powershell', 'qradar', 'qualys', 'splunk', 'splunkxml', 'grep', 'elastalert', 'xpack-watcher', 'stix', 'limacharlie', 'humio', 'kibana-ndjson', 'ala', 'graylog', 'ee-outliers', 'fireeye-helix', 'arcsight-esm', 'carbonblack', 'es-rule', 'netwitness-epl', 'kibana', 'uberagent', 'fieldlist', 'elastalert-dsl', 'csharp', 'logiq', 'es-qs', 'es-dsl', 'logpoint', 'mdatp', 'sysmon', 'ala-rule', 'sql')

**Comment by frack113** [comment]
On my VM windows 10 python 3.9.0
Update to last
```
git checkout master
git pull
```
Fisrt test
```
C:\FrackSigma\sigma\tools>python sigmac -t devo -c .\config\devo-windows.yml ..\rules\windows\sysmon\sysmon_wmiprvse_wbemcomn_dll_hijack.yml
from box.all.win where (serviceFileName = "System" and matches(serviceFileName, nameglob("*\\wbem\\wbemcomn.dll"))) select *
from box.all.win where (matches(serviceFileName, nameglob("*\\wmiprvse.exe")) and matches(serviceFileName, nameglob("*\\wbem\\wbemcomn.dll"))) select *
```
Second test
```
python setup.py install
C:\FrackSigma\sigma>sigmac -t devo -c tools\config\devo-windows.yml rules\windows\sysmon\sysmon_wmiprvse_wbemcomn_dll_hijack.yml
from box.all.win where (serviceFileName = "System" and matches(serviceFileName, nameglob("*\\wbem\\wbemcomn.dll"))) select *
from box.all.win where (matches(serviceFileName, nameglob("*\\wmiprvse.exe")) and matches(serviceFileName, nameglob("*\\wbem\\wbemcomn.dll"))) select *

**Comment by wagga40** [comment]
Hi, the devo backend is only available when you get Sigmac from the git repository. It was added after the last release available on Pypi.

**Comment by frack113** [comment]
Hi,
As it is a normal behavior, can you close this issue ?
thanks

**Comment by JDownham** [comment]
Was using WSL but switched Py for Win and working, thanks for the assistance.
