### ISSUE TITLE
DRL 1.1 Proposal (license change)

### ISSUE THREAD

**Issue by Neo23x0** [SigmaHQ/sigma#1768]
I'd like to announce a change to the detection rule license that ensures that credits are also given in cases in which only a match is shown to the users. It includes "in any reasonable manner" to allow for some flexibility. 

This is the new section that I'd like to include in the license:
```
If you use the Rules (including in modified form) on data, messages based on matches with 
the Rules must retain the following if it is supplied within the Rules:

     identification of the authors(s) ("author" field) of the Rule and any others designated to 
     receive attribution, in any reasonable manner requested by the Rule author 
     (including by pseudonym if designated).
```

https://github.com/SigmaHQ/sigma/blob/drl-1.1/LICENSE.Detection.Rules.md

**Comment by frack113** [comment]
HI,
I agree this should be natural.
A update of https://github.com/SigmaHQ/sigma/wiki/Specification could be to promote from optional to mandatory

- https://github.com/SigmaHQ/sigma/wiki/Specification#author-optional  

- https://github.com/SigmaHQ/sigma/wiki/Specification#license-optional

**Comment by Neo23x0** [comment]
The author field is and should stay optional from a technical point. 
The license states that "if an author is given" he/she has to be mentioned in outputs generated with this rule.
