### ISSUE TITLE
SIGMA to Elastalert issue

### ISSUE THREAD

**Issue by Jackson-Pollock** [SigmaHQ/sigma#1781]
I have converted my MISP events to SIGMA (which are having multiple detection conditions) and then SIGMA to ElastAlert using Sigmac but that multiple conditions getting converted to multiple rules within single file. Is there any way to split those multiple rules with multiple files?

**Comment by frack113** [comment]
Hi,
Yes  and no 😄 
check #1779

**Comment by frack113** [comment]
Otherwise #552

**Comment by Jackson-Pollock** [comment]
Thank you! will look in to it.
