### ISSUE TITLE
Proposal Schema add new Attribute

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#1804]
Hello,
I think to add new schema components:

1.  [tlp](https://www.cisa.gov/tlp) optional
add to test  must be RED,AMBER,GREEN or WHITE and  if red or amber get '[ERROR] tlp not allowed on internet'
add a filter to select `tlp`

2. `cover` optional
the rule is for "server","workstation","iot",.. 
exemple `cover: server` for a AD only rule 
add a filter to select `cover`

If you have any ideas don't hesitate to share 
Thanks

**Comment by wagga40** [comment]
Hi, 
(Very) good ideas.
- TLP RED is allowed on the Internet, I think what you meant is that TLP RED (and it is true for GREEN and AMBER too) must not be shared "_via publicly accessible channels_" and therefore not available on an public GitHub repository. I think adding the `tlp` field would be great but you have to choose between these options for the rule testing : 
    - Only allow the TLP to be "WHITE" to validate the test
    - Only test if the value is equal to "RED", "AMBER", "GREEN" or "WHITE"
    - Both 😀
- For the `Cover` field, I think `Target` would be more suited.

**Comment by frack113** [comment]
Hi,
I think "Both" as sigma is use for internal porpose  by many.
yes I translate "via publicly accessible channels" to my mind to "internet" as this is a public repo.

 I chose `cover` like in "this rule covers servers" but `target` is find to me too

**Comment by frack113** [comment]
I left it open after the merger in case you find or need anything more.
