### ISSUE TITLE
How manage Key-Value string event

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#1843]
Hi,
Some event are raw string with Key-Value (KV) in it.
Like Powershell id400 , iptables , stormshied , trendmicro in CEF format,...
The way to deal with

1. use keywords rule type
2. think of a modifier `|KV` but get a headache 
3. use  extract field name and add a warning in the logsource (definition: fields have to be extract)  

**3** is for me the best way

If you have any thoughts or ideas

**Comment by Neo23x0** [comment]
I prefer solution 1. 

Warning in logsource is something that a user has to notice. Most rules get processed by machines / programs and no-one ever notices a faulty detection.
