### ISSUE TITLE
 False positive - WMI Modules Loaded

### ISSUE THREAD

**Issue by gifrate** [SigmaHQ/sigma#1871]
Should this executable be added to the filter section of that rule?

C:\Windows\System32\wbem\WMIADAP.exe

I am detecting it on the latest Microsoft provided Windows evaluation VM 

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

with the Security Onion Playbook

**Comment by Neo23x0** [comment]
Will be fixed with this pull request https://github.com/SigmaHQ/sigma/pull/1872
