### ISSUE TITLE
Support for generating loki rules

### ISSUE THREAD

**Issue by james-callahan** [SigmaHQ/sigma#1986]
[Loki](https://grafana.com/docs/loki/latest/) is a log centralisation and search system.

I'd like a sigma tool to exist that generates loki queries/rules from sigma rules.
The query/rule format used by Loki is [LogQL](https://grafana.com/docs/loki/latest/logql/).

For alerting, you put logql queries into the "ruler" component: https://grafana.com/docs/loki/latest/rules/

**Comment by kelnage** [comment]
@james-callahan et al. - good news! We've just officially released our first version of [pySigma-backend-loki](https://github.com/grafana/pySigma-backend-loki). This allows sigma-cli to produce LogQL queries (both plain LogQL queries and in the ruler format), and includes a couple of pipelines for Windows Event Monitor and Grafana-logfmt style logs - we've also [written a blogpost to guide users](https://grafana.com/blog/2022/12/15/a-guide-to-cyber-threat-hunting-with-promtail-grafana-loki-sigma-and-grafana-cloud/) through the process of getting started with it (in the context of Grafana Cloud, Promtail and Windows - although the tool certainly isn't limited to any of those).

Hopefully this is part of the way towards what you are looking for - if there's any features, pipelines for specific formats, etc. you'd like to see, please do feel free to open an issue (or if you'd prefer, a pull request!) - we're actively looking to add more options that'll help you use Sigma rules within Loki 👍

**Comment by nasbench** [comment]
cc @thomaspatzke to include in SigmaHQ maybe?

**Comment by thomaspatzke** [comment]
Definitely! Integration into CLI will get easy when the plugin system is done!

**Comment by nasbench** [comment]
Since the original question is now answered via the creation of the new LOKI PySIGMA backend. I would close this issue as complete. Thanks to everyone for their contribution :)

To any future reader having questions about the LOKI backend please refer to the above-mentioned repo by the authors.
