### ISSUE TITLE
Backend definitions in various config files do not match new sigmac backend list

### ISSUE THREAD

**Issue by tvfischer** [SigmaHQ/sigma#2033]
Was trying to convert convert to elastic-zeek and crate elasticsearch-rules. 
I found that the backend definitions in the [ecs-zeek-corelight ](https://github.com/SigmaHQ/sigma/blob/master/tools/config/ecs-zeek-corelight.yml) and as a matter of fact a few others in the config folder have outdate backend definitions.

I think in this section` elasticsearch-rule` should be `es-rule`. I am not sure what else needs changing as i couldn't find any documentation or when these changed in the tool.

https://github.com/SigmaHQ/sigma/blob/7298225cbeea4a17fe32bc523be71394e98e0764/tools/config/ecs-zeek-corelight.yml#L4-L17

**Comment by frack113** [comment]
Hi,
I make a quick check tools

Valid : 209  Invalid : 16 No Backend : 7

 Valid backend name: ['ala', 'ala-rule', 'arcsight', 'arcsight-esm', 'carbonblack', 'chronicle', 'crowdstrike', 'csharp', 'devo', 'ee-outliers', 'elastalert', 'elastalert-dsl', 'es-dsl', 'es-eql', 'es-qs', 'es-qs-lr', 'es-rule', 'es-rule-eql', 'fieldlist', 'fireeye-helix', 'graylog', 'grep', 'humio', 'kibana', 'kibana-ndjson', 'lacework', 'limacharlie', 'logiq', 'logpoint', 'mdatp', 'netwitness', 'netwitness-epl', 'opensearch-monitor', 'powershell', 'qradar', 'qualys', 'sentinel-rule', 'splunk', 'splunkdm', 'splunkxml', 'sql', 'sqlite', 'stix', 'sumologic', 'sumologic-cse', 'sumologic-cse-rule', 'sysmon', 'uberagent', 'xpack-watcher']

|file|Configuration|check
|---|---|---
|ala-azure-activitylogs.yml                    | ala                            | OK 
|ala-azure-activitylogs.yml                    | ala-rule                       | OK 
|ala-azure-ad_auditlogs.yml                    | ala                            | OK 
|ala-azure-ad_auditlogs.yml                    | ala-rule                       | OK 
|ala-azure-aws_cloudtrail.yml                  | ala                            | OK 
|ala-azure-aws_cloudtrail.yml                  | ala-rule                       | OK 
|ala-suricata.yml                              | ala                            | OK 
|ala-suricata.yml                              | ala-rule                       | OK 
|ala.yml                                       | ala                            | OK 
|ala.yml                                       | ala-rule                       | OK 
|ala.yml                                       | sentinel-rule                  | OK 
|arcsight-zeek.yml                             | arcsight                       | OK 
|arcsight-zeek.yml                             | arcsight-esm                   | OK 
|arcsight.yml                                  | arcsight                       | OK 
|arcsight.yml                                  | arcsight-esm                   | OK 
|carbon-black-eedr.yml                         | carbonblack                    | OK 
|carbon-black-eedr.yml                         | cb                             | NOK
|carbon-black.yml                              | carbonblack                    | OK 
|carbon-black.yml                              | cb                             | NOK
|chronicle.yml                                 | chronicle                      | OK 
|crowdstrike.yml                               | crowdstrike                    | OK 
|devo-network.yml                              | devo                           | OK 
|devo-web.yml                                  | devo                           | OK 
|devo-windows.yml                              | devo                           | OK 
|ecs-auditd.yml                                | es-qs                          | OK 
|ecs-auditd.yml                                | es-dsl                         | OK 
|ecs-auditd.yml                                | es-rule                        | OK 
|ecs-auditd.yml                                | es-rule-eql                    | OK 
|ecs-auditd.yml                                | es-eql                         | OK 
|ecs-auditd.yml                                | kibana                         | OK 
|ecs-auditd.yml                                | kibana-ndjson                  | OK 
|ecs-auditd.yml                                | xpack-watcher                  | OK 
|ecs-auditd.yml                                | elastalert                     | OK 
|ecs-auditd.yml                                | elastalert-dsl                 | OK 
|ecs-auditd.yml                                | elasticsearch-rule             | NOK
|ecs-auditd.yml                                | ee-outliers                    | OK 
|ecs-azure-activitylogs.yml                    | es-qs                          | OK 
|ecs-azure-activitylogs.yml                    | es-rule                        | OK 
|ecs-azure-ad_auditlogs.yml                    | es-qs                          | OK 
|ecs-azure-ad_auditlogs.yml                    | es-rule                        | OK 
|ecs-cloudtrail.yml                            | es-qs                          | OK 
|ecs-cloudtrail.yml                            | es-dsl                         | OK 
|ecs-cloudtrail.yml                            | es-rule                        | OK 
|ecs-cloudtrail.yml                            | kibana                         | OK 
|ecs-cloudtrail.yml                            | kibana-ndjson                  | OK 
|ecs-cloudtrail.yml                            | xpack-watcher                  | OK 
|ecs-cloudtrail.yml                            | elastalert                     | OK 
|ecs-cloudtrail.yml                            | elastalert-dsl                 | OK 
|ecs-dns.yml                                   | es-qs                          | OK 
|ecs-dns.yml                                   | es-dsl                         | OK 
|ecs-dns.yml                                   | elasticsearch-rule             | NOK
|ecs-dns.yml                                   | kibana                         | OK 
|ecs-dns.yml                                   | kibana-ndjson                  | OK 
|ecs-dns.yml                                   | xpack-watcher                  | OK 
|ecs-dns.yml                                   | elastalert                     | OK 
|ecs-dns.yml                                   | elastalert-dsl                 | OK 
|ecs-filebeat.yml                              | es-qs                          | OK 
|ecs-filebeat.yml                              | es-dsl                         | OK 
|ecs-filebeat.yml                              | es-rule                        | OK 
|ecs-filebeat.yml                              | es-rule-eql                    | OK 
|ecs-filebeat.yml                              | es-eql                         | OK 
|ecs-filebeat.yml                              | kibana                         | OK 
|ecs-filebeat.yml                              | kibana-ndjson                  | OK 
|ecs-filebeat.yml                              | xpack-watcher                  | OK 
|ecs-filebeat.yml                              | elastalert                     | OK 
|ecs-filebeat.yml                              | elastalert-dsl                 | OK 
|ecs-filebeat.yml                              | elasticsearch-rule             | NOK
|ecs-filebeat.yml                              | ee-outliers                    | OK 
|ecs-okta.yml                                  | es-qs                          | OK 
|ecs-okta.yml                                  | es-dsl                         | OK 
|ecs-okta.yml                                  | es-rule                        | OK 
|ecs-okta.yml                                  | kibana                         | OK 
|ecs-okta.yml                                  | kibana-ndjson                  | OK 
|ecs-okta.yml                                  | xpack-watcher                  | OK 
|ecs-okta.yml                                  | elastalert                     | OK 
|ecs-okta.yml                                  | elastalert-dsl                 | OK 
|ecs-proxy.yml                                 | es-qs                          | OK 
|ecs-proxy.yml                                 | es-dsl                         | OK 
|ecs-proxy.yml                                 | es-rule                        | OK 
|ecs-proxy.yml                                 | corelight_elasticsearch-rule   | NOK
|ecs-proxy.yml                                 | kibana                         | OK 
|ecs-proxy.yml                                 | kibana-ndjson                  | OK 
|ecs-proxy.yml                                 | xpack-watcher                  | OK 
|ecs-proxy.yml                                 | elastalert                     | OK 
|ecs-proxy.yml                                 | elastalert-dsl                 | OK 
|ecs-proxy.yml                                 | ee-outliers                    | OK 
|ecs-suricata.yml                              | es-qs                          | OK 
|ecs-suricata.yml                              | es-dsl                         | OK 
|ecs-suricata.yml                              | es-rule                        | OK 
|ecs-suricata.yml                              | kibana                         | OK 
|ecs-suricata.yml                              | xpack-watcher                  | OK 
|ecs-suricata.yml                              | elastalert                     | OK 
|ecs-suricata.yml                              | elastalert-dsl                 | OK 
|ecs-zeek-corelight.yml                        | es-qs                          | OK 
|ecs-zeek-corelight.yml                        | corelight_es-qs                | NOK
|ecs-zeek-corelight.yml                        | es-dsl                         | OK 
|ecs-zeek-corelight.yml                        | elasticsearch-rule             | NOK
|ecs-zeek-corelight.yml                        | corelight_elasticsearch-rule   | NOK
|ecs-zeek-corelight.yml                        | kibana                         | OK 
|ecs-zeek-corelight.yml                        | kibana-ndjson                  | OK 
|ecs-zeek-corelight.yml                        | corelight_kibana               | NOK
|ecs-zeek-corelight.yml                        | xpack-watcher                  | OK 
|ecs-zeek-corelight.yml                        | corelight_xpack-watcher        | NOK
|ecs-zeek-corelight.yml                        | elastalert                     | OK 
|ecs-zeek-corelight.yml                        | elastalert-dsl                 | OK 
|ecs-zeek-corelight.yml                        | ee-outliers                    | OK 
|ecs-zeek-elastic-beats-implementation.yml     | es-qs                          | OK 
|ecs-zeek-elastic-beats-implementation.yml     | es-dsl                         | OK 
|ecs-zeek-elastic-beats-implementation.yml     | es-rule                        | OK 
|ecs-zeek-elastic-beats-implementation.yml     | elasticsearch-rule             | NOK
|ecs-zeek-elastic-beats-implementation.yml     | kibana                         | OK 
|ecs-zeek-elastic-beats-implementation.yml     | kibana-ndjson                  | OK 
|ecs-zeek-elastic-beats-implementation.yml     | xpack-watcher                  | OK 
|ecs-zeek-elastic-beats-implementation.yml     | elastalert                     | OK 
|ecs-zeek-elastic-beats-implementation.yml     | elastalert-dsl                 | OK 
|ecs-zeek-elastic-beats-implementation.yml     | ee-outliers                    | OK 
|elk-defaultindex-filebeat.yml                 | no backend set                 | -  
|elk-defaultindex-logstash.yml                 | no backend set                 | -  
|elk-defaultindex.yml                          | no backend set                 | -  
|elk-linux.yml                                 | no backend set                 | -  
|elk-windows.yml                               | no backend set                 | -  
|elk-winlogbeat-sp.yml                         | no backend set                 | -  
|elk-winlogbeat.yml                            | no backend set                 | -  
|filebeat-defaultindex.yml                     | es-qs                          | OK 
|filebeat-defaultindex.yml                     | es-dsl                         | OK 
|filebeat-defaultindex.yml                     | es-rule                        | OK 
|filebeat-defaultindex.yml                     | kibana                         | OK 
|filebeat-defaultindex.yml                     | kibana-ndjson                  | OK 
|filebeat-defaultindex.yml                     | xpack-watcher                  | OK 
|filebeat-defaultindex.yml                     | elastalert                     | OK 
|filebeat-defaultindex.yml                     | elastalert-dsl                 | OK 
|filebeat-defaultindex.yml                     | ee-outliers                    | OK 
|fireeye-helix.yml                             | fireeye-helix                  | OK 
|helk.yml                                      | es-qs                          | OK 
|helk.yml                                      | es-dsl                         | OK 
|helk.yml                                      | es-rule                        | OK 
|helk.yml                                      | kibana                         | OK 
|helk.yml                                      | kibana-ndjson                  | OK 
|helk.yml                                      | xpack-watcher                  | OK 
|helk.yml                                      | elastalert                     | OK 
|helk.yml                                      | elastalert-dsl                 | OK 
|humio.yml                                     | humio                          | OK 
|limacharlie.yml                               | limacharlie                    | OK 
|logpoint-windows.yml                          | logpoint                       | OK 
|logrhythm_winevent.yml                        | es-qs-lr                       | OK 
|logstash-defaultindex.yml                     | es-qs                          | OK 
|logstash-defaultindex.yml                     | es-dsl                         | OK 
|logstash-defaultindex.yml                     | es-rule                        | OK 
|logstash-defaultindex.yml                     | kibana                         | OK 
|logstash-defaultindex.yml                     | kibana-ndjson                  | OK 
|logstash-defaultindex.yml                     | xpack-watcher                  | OK 
|logstash-defaultindex.yml                     | elastalert                     | OK 
|logstash-defaultindex.yml                     | elastalert-dsl                 | OK 
|logstash-defaultindex.yml                     | ee-outliers                    | OK 
|logstash-linux.yml                            | es-qs                          | OK 
|logstash-linux.yml                            | es-dsl                         | OK 
|logstash-linux.yml                            | es-rule                        | OK 
|logstash-linux.yml                            | kibana                         | OK 
|logstash-linux.yml                            | kibana-ndjson                  | OK 
|logstash-linux.yml                            | xpack-watcher                  | OK 
|logstash-linux.yml                            | elastalert                     | OK 
|logstash-linux.yml                            | elastalert-dsl                 | OK 
|logstash-linux.yml                            | ee-outliers                    | OK 
|logstash-windows.yml                          | es-qs                          | OK 
|logstash-windows.yml                          | es-dsl                         | OK 
|logstash-windows.yml                          | es-rule                        | OK 
|logstash-windows.yml                          | kibana                         | OK 
|logstash-windows.yml                          | kibana-ndjson                  | OK 
|logstash-windows.yml                          | xpack-watcher                  | OK 
|logstash-windows.yml                          | elastalert                     | OK 
|logstash-windows.yml                          | elastalert-dsl                 | OK 
|logstash-windows.yml                          | ee-outliers                    | OK 
|logstash-zeek-default-json.yml                | es-qs                          | OK 
|logstash-zeek-default-json.yml                | es-dsl                         | OK 
|logstash-zeek-default-json.yml                | elasticsearch-rule             | NOK
|logstash-zeek-default-json.yml                | kibana                         | OK 
|logstash-zeek-default-json.yml                | kibana-ndjson                  | OK 
|logstash-zeek-default-json.yml                | xpack-watcher                  | OK 
|logstash-zeek-default-json.yml                | elastalert                     | OK 
|logstash-zeek-default-json.yml                | elastalert-dsl                 | OK 
|netwitness-epl.yml                            | netwitness-epl                 | OK 
|netwitness.yml                                | netwitness                     | OK 
|powershell.yml                                | powershell                     | OK 
|qradar.yml                                    | qradar                         | OK 
|qualys.yml                                    | qualys                         | OK 
|splunk-windows-index.yml                      | splunk                         | OK 
|splunk-windows-index.yml                      | splunkxml                      | OK 
|splunk-windows-index.yml                      | splunkdm                       | OK 
|splunk-windows.yml                            | splunk                         | OK 
|splunk-windows.yml                            | splunkxml                      | OK 
|splunk-windows.yml                            | splunkdm                       | OK 
|splunk-zeek.yml                               | splunk                         | OK 
|splunk-zeek.yml                               | splunkxml                      | OK 
|splunk-zeek.yml                               | corelight_splunk               | NOK
|stix-custom.yml                               | stix                           | OK 
|stix-shifter.yml                              | stix                           | OK 
|stix2.0.yml                                   | stix                           | OK 
|sumologic-cse.yml                             | sumologic-cse                  | OK 
|sumologic-cse.yml                             | sumologic-cse-rule             | OK 
|sumologic.yml                                 | sumologic                      | OK 
|thor.yml                                      | thor                           | NOK
|winlogbeat-modules-enabled.yml                | es-qs                          | OK 
|winlogbeat-modules-enabled.yml                | es-dsl                         | OK 
|winlogbeat-modules-enabled.yml                | es-rule                        | OK 
|winlogbeat-modules-enabled.yml                | es-rule-eql                    | OK 
|winlogbeat-modules-enabled.yml                | es-eql                         | OK 
|winlogbeat-modules-enabled.yml                | kibana                         | OK 
|winlogbeat-modules-enabled.yml                | kibana-ndjson                  | OK 
|winlogbeat-modules-enabled.yml                | xpack-watcher                  | OK 
|winlogbeat-modules-enabled.yml                | elastalert                     | OK 
|winlogbeat-modules-enabled.yml                | elastalert-dsl                 | OK 
|winlogbeat-modules-enabled.yml                | elasticsearch-rule             | NOK
|winlogbeat-modules-enabled.yml                | ee-outliers                    | OK 
|winlogbeat-old.yml                            | es-qs                          | OK 
|winlogbeat-old.yml                            | es-dsl                         | OK 
|winlogbeat-old.yml                            | es-rule                        | OK 
|winlogbeat-old.yml                            | kibana                         | OK 
|winlogbeat-old.yml                            | kibana-ndjson                  | OK 
|winlogbeat-old.yml                            | xpack-watcher                  | OK 
|winlogbeat-old.yml                            | elastalert                     | OK 
|winlogbeat-old.yml                            | elastalert-dsl                 | OK 
|winlogbeat-old.yml                            | ee-outliers                    | OK 
|winlogbeat.yml                                | es-qs                          | OK 
|winlogbeat.yml                                | es-dsl                         | OK 
|winlogbeat.yml                                | es-rule                        | OK 
|winlogbeat.yml                                | kibana                         | OK 
|winlogbeat.yml                                | kibana-ndjson                  | OK 
|winlogbeat.yml                                | xpack-watcher                  | OK 
|winlogbeat.yml                                | elastalert                     | OK 
|winlogbeat.yml                                | elastalert-dsl                 | OK 
|winlogbeat.yml                                | ee-outliers                    | OK 
|winlogbeat.yml                                | opensearch-monitor             | OK
