### ISSUE TITLE
Detection logic sysmon_uac_bypass_sdclt

### ISSUE THREAD

**Issue by frack113** [SigmaHQ/sigma#2043]
Hi,
Not sure the detection is correct when I read the references.

In the rule
```yaml
  # usrclass.dat is mounted on HKU\USERSID_Classes\...
        TargetObject|startswith: 'HKU\'
        TargetObject|endswith: '_Classes\exefile\shell\runas\command\isolatedCommand'
```

When I read that must be `HKCU:\Software\Classes\exefile\shell\runas\command\isolatedCommand`

Can find the `HKU\USERSID_Classes` logic.
Same logic in [sysmon_uac_bypass_shell_open.yml](https://github.com/SigmaHQ/sigma/blob/a4f91be7a82bf206eb760858f07759bf18606266/rules/windows/registry_event/sysmon_uac_bypass_shell_open.yml)
If you have a clue...

**Comment by Neo23x0** [comment]
I'd say "HKU" is always wrong. Should be HKCU or HKLM.

**Comment by Neo23x0** [comment]
If unclear, I'd remove it and work with "endswith" only

**Comment by Neo23x0** [comment]
HKU could be "HKEY_USERS", but that Hive is most likely not the one that should be used

**Comment by frack113** [comment]
hi,
It is the `USERSID_Classes` or `_Classes` that is very strange for me . 

```yaml
TargetObject|endswith: Software\Classes\exefile\shell\runas\command\isolatedCommand
```
Seen more correct

**Comment by Neo23x0** [comment]
Yes, let's do it this way
