### ISSUE TITLE
Category file_event doesn't only search for file events

### ISSUE THREAD

**Issue by maederm** [SigmaHQ/sigma#2044]
Hi

Rule [sysmon_cve_2021_26858_msexchange.yml](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file_event/sysmon_cve_2021_26858_msexchange.yml) has defined `category: file_event` but the translated elasticsearch query is `(process.executable:(*\\UMWorkerProcess.exe) AND (NOT (file.path:(*CacheCleanup.bin OR *.txt OR *.log OR *.cfg OR *cleanup.bin))))`

This also matches other non-file events. Shouldn't the `file_event` category also add a clause such as `event.category: file`? This is my understanding of [the spec](https://github.com/SigmaHQ/sigma/wiki/Specification#log-source).

Best @maederm

**Comment by frack113** [comment]
You should have a Eventid
my fast try
```bash
python sigmac -t es-qs -c config\generic\sysmon.yml -c config\winlogbeat-modules-enabled.yml ..\rules\windows\file_event\sysmon_cve_2021_26858_msexchange.yml
```
get
```
((event.code:"11" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational") AND process.executable.keyword:*UMWorkerProcess.exe AND (NOT (file.path.keyword:(*CacheCleanup.bin OR *.txt OR *.LOG OR *.cfg OR *cleanup.bin))))
```

**Comment by frack113** [comment]
@maederm is it good to close or need more digging ?

**Comment by maederm** [comment]
@frack113 looks great, I wasn't aware I can specify multiple `-c` configs. Thanks.
