### ISSUE TITLE
Sigmac and "condition" precedence order?!

### ISSUE THREAD

**Issue by Snp3r** [SigmaHQ/sigma#2089]
Hi there!

Just found an issue, in rule: rules/windows/builtin/win_susp_lsass_dump_generic.yml
```
...
condition: selection_1 or selection_2 and not filter1 and not filter2
...
```

If I convert this with sigmac -t elastalert-dsl (or graylog), the generated query gives a lot of false results. After a while I figured out that the filters was going to the wrong level. Canged the condition to: `(selection_1 or selection_2) and not filter1 and not filter2` and I have the good results now.

Not sure if its sigmac problem or just missing the parentheses from the original rule.

Thank you for your efforts!

**Comment by Neo23x0** [comment]
Thanks, fixed
