### ISSUE TITLE
sigmac - invalid value in STATE filter

### ISSUE THREAD

**Issue by al3t** [SigmaHQ/sigma#2140]
In specification it states that there are three statuses:
* stable
*  test
* experimental 
https://github.com/SigmaHQ/sigma/wiki/Specification#status-optional

Problem arises when  using sigmac with filter option and trying to filter out status **test**, because in filter options it states that status is one of these values: experimental, testing, stable.
Specification says **test**, but filter looks for status **testing**.
```
--filter FILTER, -f FILTER
                        Define comma-separated filters that must match (AND-
                        linked) to rule to be processed. Valid filters:
                        level<=x, level>=x, level=x, status=y, logsource=z,
                        tag=t. x is one of: low, medium, high, critical. y is
                        one of: experimental, testing, stable. z is a word
                        appearing in an arbitrary log source attribute. t is a
                        tag that must appear in the rules tag list, case-
                        insensitive matching. Multiple log source
                        specifications are AND linked.
                        

```

sigma-master\tools\sigma\filter.py
`line 27: STATES = ["experimental", "testing", "stable"] `

**Comment by frack113** [comment]
Thanks,
Will fix when possible if nobody do it before
