### ISSUE TITLE
Incorrect field name generated by winlogbeat config file winlogbeat-modules-enabled.yml

### ISSUE THREAD

**Issue by al3t** [SigmaHQ/sigma#2162]
There is an issue with rule /rules/windows/builtin/win_admin_share_access.yml and when winlogbeat modules are enabled. This rule uses EventID: 5140 which is generated from security logs, but winlogbeat security module doesn't have any transformations for this ID (The module has transformations for the following event IDs: https://www.elastic.co/guide/en/beats/winlogbeat/7.x/winlogbeat-module-security.html )
The issue is that when I'm using config file winlogbeat-modules-enabled.yml it converts field winlog.event_data.SubjectUserName to user.name but the actuall system doesn't have field name user.name for ID 5140 it has the defaultl one winlog.event_data.SubjectUserName

lines form winlogbeat-modules-enabled.yml
```
    SubjectUserName:
        service=security: user.name
        default: winlog.event_data.SubjectUserName
```

**Comment by frack113** [comment]
Can I close it, as it will take years for elastic to evolve ?
