### ISSUE TITLE
win_susp_svchost_no_cli.yml wrong behavior

### ISSUE THREAD

**Issue by RazviAlex** [SigmaHQ/sigma#2209]
Hi,

'Testing the rule **process_creation/win_susp_svchost_no_cli.yml** 
I have noticed that when test this alert (_sigmac -t graylog rule.yml_) it does not make much sense. Alert parsed: 
`((CommandLine: * svchost.exe AND Image: * svchost.exe) AND (NOT (ParentImage: (* rpcnet.exe * rpcnetp.exe) OR NOT _exists_: CommandLine)))`

Returns the following results:
![image](https://user-images.githubusercontent.com/51793648/139219769-05d54fac-7019-4b5f-bdb8-989d8b5c14af.png)

Results in which the commandline contains parameters, and according to the description of the rule, the commandline does not have any parameters for it to occur.

![image](https://user-images.githubusercontent.com/51793648/139220310-f707a00c-45db-415f-a8c5-c1d842ca2d3c.png)

I understand that the transformation with sigmac adds an additional **NOT** that with the previous one is canceled and therefore this result comes out. If I manually remove the NOT from commandline it works fine.

**Comment by frack113** [comment]
`CommandLine: null` is that the field `CommandLine` do not  exist or is empty (null).
No parameters in Commandline **could** be (no test done) a space after the exe `CommandLine|contains: 'exe '`

**Comment by Neo23x0** [comment]
I think this could be a backend problem, as the condition should be
```
AND _exists_: CommandLine
```

the `null` value makes problems in some backends.

**Comment by Neo23x0** [comment]
Could you show us the result of this part of the query only?
```
(CommandLine: * svchost.exe AND Image: * svchost.exe)
```

**Comment by RazviAlex** [comment]
I forgot to comment, the key was in how the information was saved. 
Graylog uses elasticsearch, when activating regex for a field ( i.e. commandline), elasticsearch by default applies a standard analyzer and stores the information separating it "by pieces". Something like that: 
<img width="277" alt="image" src="https://user-images.githubusercontent.com/51793648/144086644-fa0ceabf-0bb6-404a-9fc3-fab2965af673.png">

So when using the query` CommandLine:"*svchost.exe"` returns as true since it is stored that way... after fix that, the query works great!! 
Thank you
