### ISSUE TITLE
Wildcard symbol `*` not escaped in some cases

### ISSUE THREAD

**Issue by Neo23x0** [SigmaHQ/sigma#2339]
A co-worker recently noticed that one of my exclusions didn't match because of an unescaped wildcard character (`*`). 

![Screenshot 2021-11-29 at 10 02 25](https://user-images.githubusercontent.com/2851492/143838334-401eae75-8733-4891-b71b-afba81643283.png)

I then checked the rule set and noticed other cases in which the rule author most likely missed the wildcard escape and wrote the value in a way that misses the escape, e.g. `path: \\*\IPC$`. I think, in these cases it should actually be `path: \\\*\IPC$`. 

![Screenshot 2021-11-29 at 10 01 20](https://user-images.githubusercontent.com/2851492/143838110-b31cefcd-87a0-48aa-981b-440c0d90b2f9.png)

@frack113 @thomaspatzke : Am I right? Should correct these errors? I'd do this on my `rule-devel` branch.

**Comment by thomaspatzke** [comment]
Yes, this error is quite common, fix them. I've also fixed some recently where pySigma failed to parser as it's more strict here.
