### ISSUE TITLE
[Request] QRadar Evolution

### ISSUE THREAD

**Issue by ishusoka** [SigmaHQ/sigma#237]
Hello,

Sigma works very well for SIEM QRadar. it allows us to convert sigma rules to AQL format rules for QRadar, but we usually use it for investigate in events logs.
Use AQL to create a QRadar rules is ressource consuming.
Actually, QRadar works with pre-built conditions with "AND" and "AND NOT" operators.
Do you think it will get a evolution about this ?
Is Sigma will be mapped with pre-built QRadar conditions ?

Thank you in advance,
Regards,
Ishu

**Comment by thomaspatzke** [comment]
Definitely something we would need help for from someone with QRadar knowledge. I have no contact with QRadar and it's unlikely to change in the near future.

Perhaps our friends form @socprime can tell something about this? They already contributed the QRadar backend.

**Comment by james0d0a** [comment]
If I understand the question correctly I think your asking if Qradar can support Sigma rules.  Qradar already supports AQL as a test criteria at least through 7.2.8+. You can use a rule test for AQL via `when this event matches this AQL filter query` or for a flow rule `when the flow matches this AQL filter query`.

You only need the section of the AQL query that would be the WHERE clause. For example:

`SELECT UTF8(payload) as search_payload from events where (EventID='4624' and LogonType='10' and AuthenticationPackageName='Negotiate' and AccountName ilike 'Admin-%')`

You would only need the following section in the AQL rule test criteria:

`(EventID='4624' and LogonType='10' and AuthenticationPackageName='Negotiate' and AccountName ilike 'Admin-%')`

Hope that helps.

**Comment by ishusoka** [comment]
Hi james0d0a,

I know that QRadar supports AQL, but rules using AQL aren't optimzed.
So i would like to base my rules on the existing QRadar built-in, like "When the event(s) were detected by one or more of Microsoft Windows Security Event Log.

It's for that i asked if Sigma will be mapped with Pre-built qradar rules.

Regards,
Florian

**Comment by james0d0a** [comment]
Are you using a config file?  The current qradar config file that is in the project has a mapping for the logsourcetype filed your asking about.  Here is the same rule ran with and without the config file for example. additionally you can make your own config file for whatever specific fields you need in your environment.

with config:
```bash
$tools/sigmac --target=qradar -c tools/config/qradar.yml rules/windows/builtin/win_admin_rdp_login.yml
SELECT UTF8(payload) as search_payload from events where (deviceProduct='LOGSOURCETYPENAME(devicetype)=Microsoft Windows Security Event Log' and "Event ID Code"='4624' and LogonType='10' and AuthenticationPackageName='Negotiate' and AccountName ilike 'Admin-%')
```

and without the config file:

```bash
$tools/sigmac --target=qradar  rules/windows/builtin/win_admin_rdp_login.yml
SELECT UTF8(payload) as search_payload from events where (EventID='4624' and LogonType='10' and AuthenticationPackageName='Negotiate' and AccountName ilike 'Admin-%')
```
