### ISSUE TITLE
Wrong filter field in win_pass_the_hash_2.yml

### ISSUE THREAD

**Issue by stbe** [SigmaHQ/sigma#2410]
Hi! I believe the following rule has a bug:
https://github.com/SigmaHQ/sigma/blob/a502f316efdcc8c174b7cf412029dfae5b3552c8/rules/windows/builtin/security/win_pass_the_hash_2.yml#L30

I think the filter for `AccountName: 'ANONYMOUS LOGON'` in this rule should be a filter for `TargetUserName: 'ANONYMOUS LOGON'`. I can imagine this error originates from the fact that the rendered display template of the 4624 calls this "Account Name", but the field in the underlying event log is in fact called "TargetUserName". Would be good though if someone can double check and confirm

A screenshot of the rendered message and the event XML from MS: https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624

**Comment by frack113** [comment]
Yes it is `TargetUserName`
- https://car.mitre.org/analytics/CAR-2016-04-004/

**Comment by Neo23x0** [comment]
I guess, this also affects https://github.com/SigmaHQ/sigma/blob/04f72b9e78f196544f8f1331b4d9158df34d7ecf/rules/windows/builtin/security/win_pass_the_hash.yml

**Comment by stbe** [comment]
Yes, I would say it is also affected. Just added a commit to the PR to also address this
