### ISSUE TITLE
Problem with "Initiated" and "IP" field

### ISSUE THREAD

**Issue by r1d3th3wav3s** [SigmaHQ/sigma#2512]
Hi,

When I convert rule sysmon_excel_outbound_network_connection.yml to elastalert, I get the following query:

`((process.executable.keyword:*\\excel.exe AND network.direction:"true" AND DestinationIsIpv6:"false") AND (NOT (destination.ip.keyword:(10.* OR 192.168.* OR 172.16.* OR 172.17.* OR 172.18.* OR 172.19.* OR 172.20.* OR 172.21.* OR 172.22.* OR 172.23.* OR 172.24.* OR 172.25.* OR 172.26.* OR 172.27.* OR 172.28.* OR 172.29.* OR 172.30.* OR 172.31.* OR 127.0.0.1*) AND DestinationIsIpv6:"false")))`

But it should be:

`((process.executable:*\\EXCEL.EXE AND network.direction:"outbound" AND DestinationIsIpv6:"false") AND (NOT (destination.ip:(10.0.0.0/8 OR 192.168.0.0/16 OR 172.16.0.0/16 OR 172.17.0.0/16 OR 172.18.0.0/16 OR 172.19.0.0/16 OR 172.20.0.0/16 OR 172.21.0.0/16 OR 172.22.0.0/16 OR 172.23.0.0/16 OR 172.24.0.0/16 OR 172.25.0.0/16 OR 172.26.0.0/16 OR 172.27.0.0/16 OR 172.28.0.0/16 OR 172.29.0.0/16 OR 172.30.0.0/16 OR 172.31.0.0/16 OR 127.0.0.1) AND DestinationIsIpv6:"false")))`

Issues:
- For renaming excel.exe to EXCEL.EXE I created pull-request #2511
- For the .keyword issue I updated issue #459
- `Initiated: 'true'` should be converted to `network.direction:"outbound"`instead of `network.direction:"true"`
- Regarding the IP ranges, should the rule be converted to use `DestinationIp|ipcidrv4: 192.168.0.0/16` etc instead of `DestinationIp|startswith: '192.168.'`etc? Maybe this breaks conversions to other backends?

**Comment by frack113** [comment]
`ipcidrv4` will be in [pySigma](https://github.com/SigmaHQ/pySigma).

**Comment by frack113** [comment]
As sigmac is now at only best efforts
Take a look at https://github.com/SigmaHQ/pySigma-backend-elasticsearch
