### ISSUE TITLE
What should be the new line behaviour?

### ISSUE THREAD

**Issue by asalih** [SigmaHQ/sigma#2537]
Hello,
`python sigmac.py --target splunk ..\\..\\rules\\linux\\builtin\\lnx_susp_dev_tcp.yml -c sysmon`
Turns into;
("cat </dev/tcp/" OR "exec 3<>/dev/tcp/" OR "echo >/dev/tcp/" OR "bash -i >& /dev/tcp/" OR "sh -i >& /dev/udp/" OR "0<&196;exec 196<>/dev/tcp/" OR "exec 5<>/dev/tcp/" OR "(sh)0>/dev/tcp/" OR "bash -c 'bash -i >& /dev/tcp/" OR "echo -e '#!/bin/bash
bash -i >& /dev/tcp/")

At line 24, there is a \n char. Should this be escaped? Because converter creates splunk query with new line.

https://github.com/SigmaHQ/sigma/blob/962051e4d7235ee525b0617ac39bbb29c8fee605/rules/linux/builtin/lnx_susp_dev_tcp.yml#L24
Thank you.

**Comment by frack113** [comment]
It is a funny yaml trick : 
- Single quotes let you put almost any character in your string.
- Double quotes parse escape codes

And here the rule double because the search string have a single quotes ...

**Comment by asalih** [comment]
Oh now I got it; line 24 must be in single quotes, but the single quote literal in the rule must be doubled like this;
`- 'echo -e ''#!/bin/bash\nbash -i >& /dev/tcp/'`

https://yaml.org/spec/1.2-old/spec.html#style/flow/single-quoted
