### ISSUE TITLE
win_lsass_dump.yml logic

### ISSUE THREAD

**Issue by tcmcgahanred** [SigmaHQ/sigma#2579]
https://github.com/SigmaHQ/sigma/blob/ab814cbc408234eddf538bc893fcbe00c32ca2e9/rules/windows/process_creation/win_lsass_dump.yml

recommend changing condition to:

(selection1 and not selection2) or selection3

(I'm assuming this is the logic we're looking for here. Otherwise, selection1 and selection3 seem to contradict each other.)

**Comment by frack113** [comment]
Hello
yes , from ref it is `(selection1 and not selection2) or selection3`
Or split in 2 rules.
