### ISSUE TITLE
Clear PowerShell History incorrect field

### ISSUE THREAD

**Issue by tcmcgahanred** [SigmaHQ/sigma#2602]
https://github.com/SigmaHQ/sigma/blob/eb382c4a59b6d87e186ee269805fe2db2acf250e/rules/windows/powershell/powershell_module/posh_pm_clear_powershell_history.yml

The rule calls for Payload, however, I believe it should be EID 4104 specific field "ScriptBlockText", as seen in the image below:

![image](https://user-images.githubusercontent.com/67395486/151035398-0f8f2395-b8c2-45cf-b1dc-3ba50fb75b26.png)

Recommend changing 'Payload' to 'ScriptBlockText' throughout.

**Comment by frack113** [comment]
Thanks for the repport, I working on it
