### ISSUE TITLE
windows defender service stop with trustedinstaller token impersonation rule

### ISSUE THREAD

**Issue by mahdihtm** [SigmaHQ/sigma#2650]
Hi
this is my rule for defender service stop with token impersonation

[defenderstop_2.txt](https://github.com/SigmaHQ/sigma/files/8010298/defenderstop_2.txt)

`title: defender stop with trustedinstaller token impersonation
id:
status: experimental
description: detect windows defender service stop with openscmanager and token impersonation
author: '@mahdi_htm - mahdi hatami'
refrences: 
  - https://github.com/dosxuz/DefenderStop/blob/main/Program.cs
date: 2022/02/03
logsource:
  product: windows
  service: security
detection:
  selection: 
    EventID: 4672
    Privileges|contains|all:
      - 'SeAssignPrimaryTokenPrivilege'
      - 'SeTcbPrivilege'
      - 'SeSecurityPrivilege'
      - 'SeTakeOwnershipPrivilege'
      - 'SeLoadDriverPrivilege'
      - 'SeBackupPrivilege'
      - 'SeRestorePrivilege'
      - 'SeDebugPrivilege'
      - 'SeAuditPrivilege'
      - 'SeSystemEnvironmentPrivilege'
      - 'SeImpersonatePrivilege'
      - 'SeDelegateSessionUserImpersonatePrivilege'
  condition: selection
falsepositives:
   - Unknown
level: high
tags: T1134

`

**Comment by nasbench** [comment]
Hi and thanks for submitting this rule. I went ahead and tested it and unfortunately, the current logic doesn't work as it generates FP.

As explained in the MSDN doc. The EID 4672 is generated for new account logons if certain sensitive privileges are assigned to the new logon session (See [here](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4672) for list). In this case, this event is generated when `DefenderStop` start the TrustedInstaller service [here](https://github.com/dosxuz/DefenderStop/blob/28f6674a1a8fd46716a7ae9ca45a216ec2717ba1/Program.cs#L222-L225). Before, you can see a 4624 event with logon type 5 for service accounts.

Other interesting indicators to detect this would be looking at EID 10 from Sysmon with Granted Access 0x1f3fff for example. The rule `250ae82f-736e-4844-a68b-0b5e8cc887da` look for something similar.
