### ISSUE TITLE
PowerShell Backend can't convert windows, process_creation to Sysmon\Operational queries correctly 

### ISSUE THREAD

**Issue by JohnConnorRF** [SigmaHQ/sigma#2659]
Hey All,

The PowerShell backend with the default sysmon configuration won't produce the correct output PowerShell query.

It fails to add in a LogName value for the query and as a result makes a call to Get-WinEvent with no filter (resulting in widespread failures due to querying too many values).

Updating the sysmon config value [like this](https://github.com/SigmaHQ/sigma/compare/master...JohnConnorRF:powershell_logsource_fix?expand=1) makes it work, but I think is probably the wrong approach since that is supposed to apply a rewrite for the product and service that would be recognized by the PowerShell config.

**Comment by frack113** [comment]
Hi,
Can you give me your sigmac commandline and the right result that should have.
Thanks

**Comment by frack113** [comment]
what do you think of
```
frack113@vm:~/git/sigma/tools$ python sigmac -t powershell -c config/generic/sysmon.yml -c config/powershell.yml ../rules/windows/process_creation/win_uac_bypass_cleanmgr.yml
Get-WinEvent -LogName Microsoft-Windows-Sysmon/Operational | where {($_.ID -eq "1" -and $_.message -match "CommandLine.*.*\"\\system32\\cleanmgr.exe /autoclean /d C:" -and $_.message -match "ParentCommandLine.*C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Schedule" -and ($_.message -match "High" -or $_.message -match "System")) } | select TimeCreated,Id,RecordId,ProcessId,MachineName,Message
frack113@vm:~/git/sigma/tools$
```

**Comment by JohnConnorRF** [comment]
Ah that does work! 

Thanks for helping figure that out. 

Cheers!
