### ISSUE TITLE
Conditional field mapping is not translated correctly.

### ISSUE THREAD

**Issue by molecula2788** [SigmaHQ/sigma#2707]
For example in this rule:

https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/win_net_python.yml

compiled with `sigmac -t elastalert -c sysmon -c helk`

the resulting query is `(event_id:"3" AND Initiated:"true" AND process_path.keyword:*python*)`, although it should be `network_initiated:"true"`, because, according to `helk.yml`:
```
Initiated:                                                                                                                                                                                
     EventID=3: network_initiated
```

**Comment by frack113** [comment]
hi
If I change **helk.yml** like in the other config file  to 
```yaml
    Initiated:
        category=network_connection: network_initiated
```
get 
```bash
- query:
    query_string:
      query: (event_id:"3" AND network_initiated:"true" AND process_path.keyword:*python*)
```
