### ISSUE TITLE
Incorrectly referenced Windows events in multiple rules

### ISSUE THREAD

**Issue by b1t-hunter** [SigmaHQ/sigma#2724]
I am automatically analyzing Windows-related rules for event dependencies and found some inconsistencies in the selection of the events, i.e., channel, provider, and event code. Multiple of the selected events in the rules do not exist in Windows installations.

Following list shows the details of those three rules with a proposed correction:

| Rule | Channel | Provider_Name | EventID | Issue |
| ---| ------ | ------ | --- | --- |
| win_susp_eventlog_cleared.yml | Security | Microsoft-Windows-Eventlog | 517 | Provider should be `Security` | 
| win_wmiprvse_wbemcomn_dll_hijack.yml | Security | Microsoft-Windows-Eventlog | 5145 | Provider should be `Microsoft-Windows-Security-Auditing` |
| win_invoke_obfuscation_clip_services_security.yml | Security | Service Control Manager | 4697 | Provider should be `Microsoft-Windows-Security-Auditing` |

**Comment by frack113** [comment]
Thanks for the works
