### ISSUE TITLE
The specification yaml in the wiki needs to be updated with specification yaml file

### ISSUE THREAD

**Issue by devinbfergy** [SigmaHQ/sigma#2743]
https://github.com/SigmaHQ/sigma/wiki/Specification#rx-yaml

The rx-yaml file is outdated compared to the new https://github.com/SigmaHQ/sigma/blob/master/sigma-schema.rx.yml

Should be a basic fix, but I am struggling to figure out how I contribute to the wiki.

**Comment by Neo23x0** [comment]
fixed thanks

FYI: you can clone the wiki repo just like any other repo, but I'm not sure how anyone could provide pull requests for it
![Screenshot 2022-03-05 at 11 30 19](https://user-images.githubusercontent.com/2851492/156879423-2120928b-813e-412a-ad7f-79fb05553eda.png)
