### ISSUE TITLE
Invalid channel specification in winlogbeat.yml

### ISSUE THREAD

**Issue by b1t-hunter** [SigmaHQ/sigma#2768]
The windows-bits-client log source has a channel specified that corresponds to a Splunk Windows TA channel name, but the channel is specification for logbeat. `winlog.channel: WinEventlog:Microsoft-Windows-Bits-Client/Operational` should be changed to `winlog.channel: Microsoft-Windows-Bits-Client/Operational`

**Comment by Neo23x0** [comment]
fixed in https://github.com/SigmaHQ/sigma/commit/335ed247517ea3b1a9cff2f572555c12228f4b13
