### ISSUE TITLE
Splunk Backend Prefix

### ISSUE THREAD

**Issue by Neo23x0** [SigmaHQ/sigma#2772]
@frack113 : I think you've added this line recently. Shouldn't this have a `WinEventLog:` prefix like the others?

https://github.com/SigmaHQ/sigma/blob/9595cef06e18a1299fbada52f34139b901ff3a46/tools/config/splunk-windows.yml#L129

The same goes for 
https://github.com/SigmaHQ/sigma/blob/9595cef06e18a1299fbada52f34139b901ff3a46/tools/config/splunk-windows.yml#L134

**Comment by frack113** [comment]
My bad, adding a single channel to all backends without errors is complicated.
Will make the fix.
