### ISSUE TITLE
Invalid AST generated by optimization

### ISSUE THREAD

**Issue by gaelmuller** [SigmaHQ/sigma#2806]
Hello, we have come across what I think is a bug in the optimization of the AST. The generated AST seems invalid when one of the selection contains another:

```python
from io import StringIO

from sigma.parser.collection import SigmaCollectionParser
from sigma.parser.condition import dumpNode

rule = StringIO("""
detection:
    selection1:
        field|contains|all:
            - str1
            - str2
    selection2:
        field|contains|all:
            - str1
            - str2
            - str3
            - str4
    condition: 1 of selection*
""")


parsers = [parser.condparsed for parser in SigmaCollectionParser(rule).parsers]
for parser in parsers:
    for condition in parser:
        dumpNode(condition.parsedSearch)
```

Prints the following output:

```
NodeSubexpression<ConditionAND>
  ConditionAND<list>
    tuple=('otherfield', '*str1*')
    tuple=('otherfield', '*str2*')
    tuple=('otherfield', '*str3*')
    tuple=('otherfield', '*str4*')
```

This is equivalent to `selection2` instead of the requested `1 of selection*`

**Comment by thomaspatzke** [comment]
Confirmed, this appears to be a bug. I'll try to fix it.

@gaelmuller I strongly recommend to use [pySigma](https://github.com/SigmaHQ/pySigma) instead of the legacy sigmatools from this repository, as these are deprecated and will be replaced by pySigma.

**Comment by thomaspatzke** [comment]
Fixed the bug by removal of the faulty optimization.

**Comment by thomaspatzke** [comment]
Merged to master
