### ISSUE TITLE
idea/feature request: back-references and capture groups

### ISSUE THREAD

**Issue by vbr-cts** [SigmaHQ/sigma#2845]
Hi all.

So, I have a feature request that I'm really uncertain how it might be implemented. Basically, I would like the ability to perform matching where the value depends on another field. I have multiple use-cases:

1. matching on equality between two fields (e.g. detect execs where ParentImage = Image)

2. matching on arithmetic comparisons between two fields (e.g. sc-bytes > cs-bytes)

3. matching on a format string based on another field (e.g. event  "vpn-%{orig_cc}")

I'm unsure what is the right way to implement this in sigma ?

**Comment by thomaspatzke** [comment]
See my [comment here](https://github.com/SigmaHQ/sigma/issues/2925#issuecomment-1137069020) on a similar issue.
