### ISSUE TITLE
Wrong ATT&CK Tag?

### ISSUE THREAD

**Issue by megan201296** [SigmaHQ/sigma#2886]
The Atomics reference indicates that this is related to T1218, not T1562. Not sure where the t1562.001 association came from.

https://github.com/SigmaHQ/sigma/blob/ac5346c2a57151aafc5ccb304ee3c5a3a14dd6ba/rules/windows/process_creation/proc_creation_win_infdefaultinstall.yml#L12

**Comment by frack113** [comment]
Well , I think it was a bad copy and paste.
