### ISSUE TITLE
Minor typos in the wiki

### ISSUE THREAD

**Issue by Aegide** [SigmaHQ/sigma#2904]
I wanted to do a pull request, but Github won't allow me to do that easily.
<br>
https://github.com/SigmaHQ/sigma/wiki/Specification#log-source
> You can use the values of 'category, 'product' and 'service' to point the converters to a certain index.

1°) single-quotes are used, while double-quotes are used just above
2°) unclosed quotes around the word category
<br>
https://github.com/SigmaHQ/sigma/wiki/Specification#placeholders
> Placeholders map a an identifier to a user defined value

3°) the sequence "a an" looks like a typo

**Comment by frack113** [comment]
Wiki move to https://github.com/SigmaHQ/sigma-specification
