### ISSUE TITLE
False positives: Plethora of Sigma rule issues on new (beta) upload of my software

### ISSUE THREAD

**Issue by CyberGonzo** [SigmaHQ/sigma#2949]
I uploaded two new betas a few days ago and I get all these rules' issues I have never seen before when I check with virustotal.com.
It's quite stressful as a software vendor, living from his software, to see all that !?  Certainly if you know that the software is super safe and anything but malicious !  The rules allude messing with Windows defender and Windows firewall.  I do no such thing (Frankly I wouldn't know how)

The 32 bit upload (Installer built with an older 5.x Inno Setup) https://www.virustotal.com/gui/file/095baa18542b6513bf9c610d02be08f1c5942009c61359316c6a71a1e6323ca2
The 64 bit upload (Installer built with the latest 6.x Inno Setup (which no doubt accounts for the dodgy AV false positive - issue reported)
https://www.virustotal.com/gui/file/6fd92d4fcd90d055ea82d8f6343d60cdb32b269b58c3a1519f288ccaaa5e3d2f?nocache=1

PS. when I check my program's executable (not in installer) there are no rule collisions.  So I'm guessing you have a problem with Inno Setup ?  Please fix !  I will be releasing a final version of my software soon and I can't have the many non technical users spooked by this ! Thanks !
The beta downloads fyi: https://www.isobuster.com/beta/

**Comment by Neo23x0** [comment]
> and I get all these rules' issues I have never seen before 

Could you elaborate further on that remark? I don't understand your problem.

**Comment by wagga40** [comment]
<img width="873" alt="Screenshot 2022-04-27 at 09 46 38" src="https://user-images.githubusercontent.com/6437862/165468198-ad03c4c1-fc76-4b15-aa03-c41ddc123d88.png">

I think there is a problem with VT, Sigma rules seem to be applied on actions related to VT sandbox configuration scripts.
VT should use sigma only on actions related to the files submitted.

We will see a lot of people coming here to complain if it is the case.... In fact, the problem appears to be the same here (despite the fact the poster doesn't understand the purpose of Sigma at all) : https://github.com/SigmaHQ/sigma/discussions/2924

**Comment by CyberGonzo** [comment]
@Neo23x0, well yeah, I've never seen this before.  I have been submitting my software to virustotal for many many years now, usually squeaky clean, but if there is a false positive I can have the AV company fix it.  But after I uploaded my latest versions I suddenly noticed all these issues, with HIGH threat levels, mention of Windows firewall and defender.  This is going to turn away many of my users and will create a lot of support overhead. 

@wagga40 
> We will see a lot of people coming here to complain if it is the case....

Welcome to my world.

> In fact, the problem appears to be the same here (despite the fact the author doesn't understand at all the purpose of Sigma)

I'm in the same camp then.  I have no clue what this is about and I'm fairly technical.  Imagine how less technical people will freak out.  Of course for me there's the added dimension of actually having to live of my software

**Comment by Neo23x0** [comment]
So, users that are logged into Virustotal with an account, also see the Sigma matches. Okay. 
Is that the normal user base of you software? 
Do users of IsoBuster have Virustotal accounts? 

Okay, I see the problem if only 1% of the users also have a VT account. 
I'll forward this to my contact at VT.

**Comment by CyberGonzo** [comment]
> > versions I suddenly noticed all these issues, with HIGH threat levels, mention of Windows firewall and defender.
> 
> > This is going to turn away many of my users and will create a lot of support overhead.
> 
> I mean, how? The matching sigma rules are only visible to users with Virustotal Enterprise access. Normal uses don't have that.

OMG, I am indeed logged on to virustotal ... I just logged out and you're right !
I had NO idea.  I sincerely apologize for freaking out

**Comment by CyberGonzo** [comment]
> Okay, I see the problem if only 1% of the users also have a VT account.
> I'll forward this to my contact at VT.

I can't say for sure how many people will see it ... but enough people I'm afraid.  It's not going to make life easier and if VT is doing something wrong then they really should fix it, so thank you for escalating this !

**Comment by Neo23x0** [comment]
The issue has been resolved by Virustotal. They've added the rules to a filter list and removed the findings from your samples.

**Comment by CyberGonzo** [comment]
Thank you very much !  I appreciate the effort.
