### ISSUE TITLE
Service names filter-out

### ISSUE THREAD

**Issue by cgiampoulakis** [SigmaHQ/sigma#3067]
https://github.com/SigmaHQ/sigma/blob/eb382c4a59b6d87e186ee269805fe2db2acf250e/rules/windows/builtin/security/win_susp_rc4_kerberos.yml#L23
Hi! Shouldn't that be:

` ServiceName|endswith: '$' `

**Comment by cgiampoulakis** [comment]
Hello, Should I need to create a pull requested with the corrected sigma rule? Is there a guide? Thanks in advance!

**Comment by Neo23x0** [comment]
Already fixed, thanks
