### ISSUE TITLE
Wiki - Taxonomy - Broken link

### ISSUE THREAD

**Issue by Aegide** [SigmaHQ/sigma#3140]
I can't do a pull requests for wiki, so here is what i found.

<br><br>

**Wiki** : https://github.com/SigmaHQ/sigma/wiki/Taxonomy

> We align our field names to the field names that Sysmon uses. You can find all possible field values in the [Sysmon Community Guide](https://github.com/trustedsec/SysmonCommunityGuide/blob/master/Sysmon.md) and on UltimateWindowsSecurity.com.

**Working link** : https://github.com/trustedsec/SysmonCommunityGuide/blob/master/chapters/Sysmon.md

**Comment by frack113** [comment]
Thank I change it .
