### ISSUE TITLE
regular expression please!

### ISSUE THREAD

**Issue by SigmaStar** [SigmaHQ/sigma#3152]
[sigma](https://github.com/SigmaHQ/sigma)/[rules](https://github.com/SigmaHQ/sigma/tree/master/rules)/[windows](https://github.com/SigmaHQ/sigma/tree/master/rules/windows)/[process_creation](https://github.com/SigmaHQ/sigma/tree/master/rules/windows/process_creation)/proc_creation_win_powershell_susp_parameter_variation.yml:

        r' -win?d?o?w?s?t?y?l?e? hi?d?d?e?',
        r' -NoPr?o?f?i?l?e?',
        r' -nonint?e?r?a?c?t?i?v? ',
        r' -enc?o?d?e?d?C?o?m?m?a?n? ',
        r' -ec',
        r' -executionp?o?l?i?c? ',
        r' -exe?c?u?t?i?o?n? bypass',
        r' -ep bypass',

use regex above, please.

**Comment by Neo23x0** [comment]
Sorry, but no.

- most backends don't support regular expressions
- you'd miss the details 

e.g.
``` 
      - ' -windows h'
      - ' -windo h'
```
In this case `-window hidden` would trigger the rule, only `-windo hidden` or `-windows hidden`
