### ISSUE TITLE
[Feature Request] Convert single Splunk query to Sigma notation

### ISSUE THREAD

**Issue by noperle** [SigmaHQ/sigma#330]
Hi :)
Can you create a converter from Splunk query to Sigma notation/template?

**Comment by thomaspatzke** [comment]
Already got related requests, thinking about a solution (alkso for other query languages).

Anyways, would take a while. Currently occupied with other stuff.

**Comment by Xyz00777** [comment]
Hi, awesome Project!
What is the state of these request? I would like to try out Sigma rules and would like to convert a few SPLs to Sigma to know how they need to look, but I don't want to use undercoder.io because I think the translate into Sigma there is happening on there server... 

Greetings

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
