### ISSUE TITLE
Usage of Sysinternals Tools - Command-Line Parameter

### ISSUE THREAD

**Issue by leegengyu** [SigmaHQ/sigma#3309]
In [this rule](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_eula_accepted.yml), the `selection` is `CommandLine|contains: ' -accepteula'`.

The above is 1 way to accept EULA, and it is also documented by Microsoft for PsExec (a Sysinternals tool) in [here](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec).

However, I found that `/accepteula` also works.

Would suggest that we include the slash variation of the command-line parameter to the detection rule too.

**Comment by frack113** [comment]
It is the new [windash](https://github.com/SigmaHQ/sigma/wiki/Specification#modifier-types) modifier case.
Never use , so need to test

**Comment by Neo23x0** [comment]
I'm not sure but I think the converter already supports `windash` but we haven't introduced the modifier in all rules to avoid a huge coverage loss for anyone that uses an older version of the converter.

**Comment by frack113** [comment]
I have keep it simple with a 'OR'
