### ISSUE TITLE
Found Malware 

### ISSUE THREAD

**Issue by ryoppippi** [SigmaHQ/sigma#3319]
https://twitter.com/stephenlacy/status/1554697077430505473/photo/1

Did you see this tweet?
I found this ugly address in this repo

**Comment by wget** [comment]
I confirm. While checking if Collabora Online was impacted or not (hopefully we aren't), I found this sigma repo being vulnerable.

URL to confirm the problem: https://github.com/search?l=YAML&q=ovz1.j19544519.pr46m.vps.myjino.ru&type=Code

Direct tweet link: https://twitter.com/stephenlacy/status/1554698532824576000

**Comment by Shichiha** [comment]
```title: Github Repo Compromise Domain MyJino RU
id: 3a9f4c77-8e2e-45eb-abc1-4754f670d3a9
status: test
description: Detects connections to the host used in a big repository compromise discovered in August 2022
```
they **do** know 😓

**Comment by Neo23x0** [comment]
![6orgd1](https://user-images.githubusercontent.com/2851492/182561998-54270f92-1c72-4c3e-a0b9-82c1d303fead.jpg)

**Comment by mattn** [comment]
This file was added after that tweet. So it is expected.

https://github.com/SigmaHQ/sigma/commit/72dbfffc0f18e63910c2b0f5693a4d8e8ee90bde

**Comment by ryoppippi** [comment]
so sorry guys...

**Comment by ryoppippi** [comment]
If so, sorry guys.
Close this Issue plz
