### ISSUE TITLE
Change rule filter https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml. Where it has ObjectType it should be ObjectClass.

### ISSUE THREAD

**Issue by gabrielvrcamara** [SigmaHQ/sigma#3339]
Change rule filter https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_account_backdoor_dcsync_rights.yml.
Where it has ObjectType it should be ObjectClass as evidenced in the following links.

https://twitter.com/menasec1/status/1111556090137903104
https://docs.microsoft.com/pt-br/windows/security/threat-protection/auditing/event-5136
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adsc/9abb5e97-123d-4da9-9557-b353ab79b830?redirectedfrom=MSDN

It can be noticed that there is no Object Type parameter and yes, what would fit in this rule condition would be the ObjectClass.

**Comment by frack113** [comment]
https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-5136
