### ISSUE TITLE
Issue with Creation of an Executable by an Executable by frack113 from Sigma Integrated Rule Set (GitHub)

### ISSUE THREAD

**Issue by leemidgley** [SigmaHQ/sigma#3405]
two problems with this:-

An extracted exe from a rar archive exe is detected, this is an existing exe not a created exe.
And this doesn't take into account that the exe extracted has a digital certificate so is not malicious at all.

**Comment by frack113** [comment]
Hi,
the rule is `low` as there is mamy possible FP.
It would be nice if we could have information about the created file but sysmon only gives :
- UtcTime
- ProcessGuid
- ProcessId
- Image
- TargetFilename
- CreationUtcTime

**Comment by frack113** [comment]
My start point was like this
![image](https://user-images.githubusercontent.com/62423083/185746227-b91b97d2-b68a-410e-8491-9ba68b7cbe01.png)

'C:\Program Files\' and 'C:\Program Files (x86)\' are exclude so if you use a installed version of rar there must be no FP.

**Comment by leemidgley** [comment]
ok, it doesn't use rar to unpack, it is a rar sfx exe. e.g.

![image](https://user-images.githubusercontent.com/100586601/185755332-63688746-886b-4525-a0ba-a26d61423539.png)

the settings in the sfx to extract to windows temp, then run a setup.exe extracted to install.

Any ideas how to get around it?
does it look at rar sfx archives to know that it's not been created and been extracted?

**Comment by frack113** [comment]
With sysmon no.
With  aurora lite I can add a filter `Description: '7z SFX'` or `OriginalFileName: '7z.sfx.exe'` to exclude 7-zip Sfx archive

**Comment by leemidgley** [comment]
no problem - I just wanted to make you aware of it as been an extract rather than a creation of an exe, I've attached two examples 32bit and 64bit.     the type I unusually create in winrar are actually zip sfx.   rename them to .exe

[test32.exe.zip](https://github.com/SigmaHQ/sigma/files/9388900/test32.exe.zip)
[test64.exe.zip](https://github.com/SigmaHQ/sigma/files/9388901/test64.exe.zip)

Click view archive in properties to see what it is.
these are flagged as suspicious  (low) when they auto extract the contents to windows temp and run a setup.exe within.   (no setup.exe included in these attached examples, just a simple txt file).

Thanks,
Lee.
p.s. it's no biggie just wanted to make you aware of it.

**Comment by frack113** [comment]
@leemidgley when try in my VM your exe, I get a error missing setup.exe

**Comment by leemidgley** [comment]
yeah I left it out in that example. normally it would have the installshield setup.exe in and run it after extraction.
do you need another example?

**Comment by Neo23x0** [comment]
Yes, please don't change the rule. It's level `low` and that is what that category is meant to match on - suspicious activity, which is often legitimate but sometimes malicious.

**Comment by frack113** [comment]
@leemidgley , I think the answer has been given.
