### ISSUE TITLE
"bigger" or "lower" condition

### ISSUE THREAD

**Issue by naxonez** [SigmaHQ/sigma#3411]
Hi,

Is there an option that allows me to search if a field is greater or lower than a given number?

Example in SQL:
select * from logs where column_int < 10 and column_int > 5

Im reviewing the documentation and I viewed that are options as "contains" or "endswith" but i dont how to make this condition using sigma :(

Thanks!

**Comment by frack113** [comment]
With https://github.com/SigmaHQ/pySigma
