### ISSUE TITLE
Import statement support for elastalert backend

### ISSUE THREAD

**Issue by haam3r** [SigmaHQ/sigma#344]
An option I've also been using (Will try to make a PR soon) Is to utilize the import keyword supported by elastalert. Related to #256 

With this option, you could have Sigma generate the elastalert rule and append a single line at the end like: import: /path/to/extra/config.conf

Then in /path/to/extra/config.conf you can add additional elastalert options like:

alert: post
http_post_url: "http://example.com/api"
http_post_payload:
  ip: clientip
http_post_static_payload:
  apikey: abc123

But this in its current format is a simple append contents of file, but makes it so you can add common options to multiple rules when elastalert loads them.

In the same frame I've been toying with the idea of teaching this elastalert import keyword some yaml merging capabilites, so you could have common options in the import config file and override or extend specific keys in the rule file.

**Comment by christophetd** [comment]
@haam3r I solved this by specifying the configuration parameters you mention in the main Elastalert configuration file. I don't think this is needed on a per-rule basis?

**Comment by haam3r** [comment]
@christophetd Yes, for the common options instead of the import keyword you could use the main config file too. But with the import keyword you can use different import files for different rule groups. Additionally with yaml merging, I could merge for example Hive configs, so adding common observable mappings or tags to multiple rules as a base and then specifying additional tags like MITRE ATT&CK techniques or observable mappings per rule. Hope that illustrates things a bit better.

**Comment by defensivedepth** [comment]
@haam3r I am interested in seeing what you have already done - is it up somewhere publicly?

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
