### ISSUE TITLE
sigmac splunk backend: Wrong conversion for |contains|all

### ISSUE THREAD

**Issue by phantinuss** [SigmaHQ/sigma#3443]
Hi,

I suspect a wrong conversion for the `|contains|all` pipeline for the splunk backend. As an example I create a conversion for following rule.
```
$ sigmac -t splunk rules/windows/network_connection/net_connection_win_remote_powershell_session_network.yml -c tools/config/splunk-windows.yml 
(((DestinationPort="5985" OR DestinationPort="5986") Initiated="true") NOT (((User="*NETWORK SERVICE*" OR User="*NETZWERKDIENST*" OR User="*SERVIZIO DI RETE*" OR User="*SERVICIO DE RED*") OR User="*SERVICE R*" User="*SEAU*" OR SourceIp="0:0:*" OR (Image="C:\\Program Files\\Avast Software\\Avast\\AvastSvc.exe" OR Image="C:\\Program Files (x86)\\Avast Software\\Avast\\AvastSvc.exe")) OR (SourceIp="::1" DestinationIp="::1")))
```
The part from the rule:
```
    - User|contains|all:
        - 'SERVICE R'
        - 'SEAU'
```
is translated to:
```
[...] OR User="*SERVICE R*" User="*SEAU*" OR [...]
```
But I think it should be:
```
[...] OR (User="*SERVICE R*" User="*SEAU*") OR [...]
```

Differently as usual in splunk OR has precedence over AND (in search):
https://docs.splunk.com/Documentation/SplunkCloud/latest/Search/Booleanexpressions
![image](https://user-images.githubusercontent.com/79651203/187235030-d0fde88b-90c8-4a78-a35c-be2b4bc9fd32.png)

I can also verify this on my splunk instance where adding parentheses resolves the issue.

I think we are lucky to detect it, as it happened here on a filter out condition --> we get FPs. On most other cases we just get no detection.

Can you verify that behaviour and that the parentheses should be present? @thomaspatzke

**Comment by thomaspatzke** [comment]
Definitely a bug, OR has a higher precedence in Splunk than AND. I think this could be caused by the optimizer, but this is just a guess. Will check it later this week.
