### ISSUE TITLE
Issue with a lot of rules created by @nasbench

### ISSUE THREAD

**Issue by Kucharskov** [SigmaHQ/sigma#3491]
Hi! I really dont know where i can put this, but i really was forced to publish something like that manifesto.
I dont have issue with whole sigma project, I have issue with a lot rules created by @nasbench.

Few examples of stupid ideas:
- [Yea, why not catch all as an allert](https://github.com/SigmaHQ/sigma/blob/fbc7519b9468f40db042fc2b19a4a7c95f08daa5/rules/windows/sysmon/sysmon_file_block_exe.yml)
- [Why not detect each exectuion, cus its LOLBAS ONE ONE111!!!](https://github.com/SigmaHQ/sigma/blob/268b0a803815e7d46469c6026ee87fa1e18cf696/rules/windows/process_creation/proc_creation_win_lolbin_device_credential_deployment.yml)

Or problem with damages rules like these:
- [Problem with urls in definiton](https://github.com/SigmaHQ/sigma/blob/367e2fd0f96a6aa085a9e57c938e03319c3af204/rules/windows/network_connection/net_connection_win_susp_cmstp.yml)
- [How TF the twitter with 2 IP leads you to create this?](https://github.com/SigmaHQ/sigma/blob/ff6e50bc4396e5c8080333e5ae4b03aeb7ecb9f1/rules/windows/process_creation/proc_creation_win_query_session_exfil.yml)

Im working as SIEM Engineer and sigma is a wonderfull place to find a lot of ideas, detections and ways to make our world safer. But if @nasbench and other persons will be creating simmilar rules the sigma will be unviewable! The funniest part is that his surname in my local language sounds simmilar to "i maked a shit" and he really does it! PLEASE STOP.

Because im created an automation tool to summary new ideas of new sigmas my co-workers asks me to create an auto comment for rules created by that person. I reviewed a lot of then and i can barely says that 90% of his detections can be deleted.  If he just want to join this project for next row in CV like "im participated in sigma project" of course. Do it! But do it with your mind, not just blah-blah yadda yadda, paste antyhing...

Thanks!

**Comment by Kucharskov** [comment]
I've thought through what I wrote, and apparently that's the reality of open-source projects, that anyone can help.
I will solve the "problem" on my side, and close the issue on github, as it is not related to the sigma project.

Thats all have a nice day!

**Comment by nasbench** [comment]
Hello,

Thanks for being so expressive. If you have issues with any of the rules I wrote or any rules of that matter you are more than welcome to create a PR with the proposed fixes and the FPs generated in your env (redacted ofc). That way they can be properly reviewed by people who know how to write rules.

Regards.
