### ISSUE TITLE
Condition syntax error in proc_creation_win_susp_whoami_anomaly.yml

### ISSUE THREAD

**Issue by s7ryph** [SigmaHQ/sigma#3556]
When the second filter condition was added to the rule in commit a231aa7 it was treated as an and statement which continued with filter 3.

`( selection and not filter1 and not filter2 and not filter3 ) or selection_special`

the this excludes all filters by requiring a combination of parent processes including null. Correct syntax should be

`( selection and not 1 of filter* ) or selection_special`

**Comment by Neo23x0** [comment]
Thanks for the heads up
