### ISSUE TITLE
[sigmac][graylog] sigmac appends .keyword on field names

### ISSUE THREAD

**Issue by dmuensterer** [SigmaHQ/sigma#3577]
I'm not sure how the issue is caused but when using sigmac to parse rules of different kinds using the graylog backend, there's somehow always a `.keyword` behind the correct field names which I couldn't find on how to specify/remove.
E.g.:
`(EventID:("8" "10") AND SourceImage.keyword:(*\\powershell.exe *\\pwsh.exe) AND TargetImage.keyword:*\\lsass.exe)
((OriginalFilename.keyword:(*.lnk *.rtf *.pst *.docx *.xlsx *.jpg *.jpeg *.png *.pdf) AND TargetFilename.keyword:(*.lnk.* *.rtf.* *.pst.* *.docx.* *.xlsx.* *.jpg.* *.jpeg.* *.png.* *.pdf.*)) AND (NOT ((TargetFilename.keyword:(*.tmp *.bak *.old *.orig *.backup *.temp)) OR (TargetFilename.keyword:C\:\\ProgramData\\Anaconda3\\* AND TargetFilename.keyword:*.c\~))))`

I did a `grep -rnw config -e keyword` but couldn't find where and why the `.keyword `is being added

**Comment by frack113** [comment]
Graylog backend use ElasticsearchQuerystringBackend.
Where there is an option `keyword_field`
"Keyword sub-field name (default is: '.keyword'). Set blank value if all keyword fields are the base(top-level) field. Additionally see 'keyword_base_fields' for more granular control of the base & subfield situation."
