### ISSUE TITLE
CI rule test does not allow for EventID: 1 to be used

### ISSUE THREAD

**Issue by YamatoSecurity** [SigmaHQ/sigma#3618]
The CI rule test will give an error that rules that use EID 1 need to use the `category: process_creation` instead.
However, there are many non-sysmon EID 1 events so it should not be assumed that all EID 1 events are sysmon events and make an exception that if `Channel `or `service` is defined to allow for EID 1 rules to be used. In particular, the Application and System event logs but there are probably more examples.

Example of it failing: https://github.com/SigmaHQ/sigma/actions/runs/3296843692/jobs/5436974781

**Comment by phantinuss** [comment]
working on it

**Comment by phantinuss** [comment]
should be fixed after merging #3619. You need to rebase your branch with the changes from master after the merge to get green checks on your PR.

**Comment by YamatoSecurity** [comment]
Thank you so much!
