### ISSUE TITLE
rule could need modification in windows/builtin/application

### ISSUE THREAD

**Issue by H-cognna** [SigmaHQ/sigma#3622]
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/application/win_av_relevant_match.yml

The rule detect keywords field
But I don't think the keyword fields could have these values in windows application event logs
It could be available in the eventdata field
So it is better to change this field in the sigma rule to Eventdata or Data, is my conclusion right?

**Comment by frack113** [comment]
Hello,
Here it is not a field name "keywords"  but [a search against all the log](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_1_0_1.md#lists).

Some anti-virus store alert in a raw Data section other can use named field.

Some rule use Data but with the warning
`# warning: The 'data' field used in the detection section is the container for the event data as a whole. You may have to adapt the rule for your backend accordingly`

Perhaps a discussion on the use of the `Data` field should be opened [here](https://github.com/SigmaHQ/sigma-specification/discussions)

**Comment by H-cognna** [comment]
Alright i get it now, thanks

**Comment by frack113** [comment]
https://github.com/SigmaHQ/sigma-specification/discussions/21
