### ISSUE TITLE
Need help with this rule rules/windows/builtin/code_integrity/win_codeintegrity_failed_driver_load.yml

### ISSUE THREAD

**Issue by H-cognna** [SigmaHQ/sigma#3623]
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/code_integrity/win_codeintegrity_failed_driver_load.yml

I am trying to use chainsaw tool to convert this sigma and hunt for it
https://github.com/WithSecureLabs/chainsaw

It suppose to catch this sentence: 'that did not meet the Microsoft signing level requirements'
however in the event itself, I can find it in general , but I can't find it in the XML view

![image](https://user-images.githubusercontent.com/112784902/197407784-6646665d-1e69-4f4b-8841-aef505331e4c.png)

![image](https://user-images.githubusercontent.com/112784902/197407680-96d4b662-8a59-4289-a483-b24d630ac2a9.png)

so i want to ask which field should i put in the mapping here so that it catch it? 
i tried keywords to Event.EventData.Data, it did not work
could you please help
https://github.com/WithSecureLabs/chainsaw/blob/master/mappings/sigma-event-logs-all.yml

**Comment by nasbench** [comment]
Hi,

Thanks for pointing this out. There seems to be an issue with the rule that needs to be fixed. The text it's searching for isn't part of the event XML (Which is what is checked for detection).

We'll update the rule accordingly.

**Comment by frack113** [comment]
Hi,
Here it is a [global search](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_1_0_1.md#lists) so should be map to a "full log" or "message".
Sigmac use the [not_bound_keyword option](https://github.com/SigmaHQ/sigma/blob/90aeea92bf0b1cbe6a3740591b7f9f8ae656efd2/tools/sigma/backends/elasticsearch.py#L72) for this.

From https://github.com/nasbench/EVTX-ETW-Resources
```xlm
</Template>
            </Event>
            <Event>
                <Id>3033</Id>
                <Version>0</Version>
                <Channel>Microsoft-Windows-CodeIntegrity/Operational</Channel>
                <Level>Error</Level>
                <Task>CreateSection</Task>
                <Opcode>PolicyFailure</Opcode>
                <Message><![CDATA[ Code Integrity determined that a process (%4) attempted to load %2 that did not meet the %5 signing level requirements.]]></Message>
                <Template><![CDATA[ <template xmlns="http://schemas.microsoft.com/win/2004/08/events">
  <data name="FileNameLength" inType="win:UInt16" outType="xs:unsignedShort"/>
  <data name="FileNameBuffer" inType="win:UnicodeString" outType="xs:string" length="FileNameLength"/>
  <data name="ProcessNameLength" inType="win:UInt16" outType="xs:unsignedShort"/>
  <data name="ProcessNameBuffer" inType="win:UnicodeString" outType="xs:string" length="ProcessNameLength"/>
  <data name="RequestedPolicy" inType="win:UInt8" outType="xs:unsignedByte"/>
  <data name="ValidatedPolicy" inType="win:UInt8" outType="xs:unsignedByte"/>
  <data name="Status" inType="win:UInt32" outType="xs:unsignedInt"/>
</template>
]]></Template>
```
Here RequestedPolicy is 8 for "Microsoft" but I did not found documention about it.
There are 46 math for "that did not meet the %5 signing level requirements" in the file.

If the rule is not for "Microsoft" only, need to check the all eventid and select the good one.

**Comment by frack113** [comment]
On my Windows 11 get many FP ( I hope 🥲 )
![image](https://user-images.githubusercontent.com/62423083/197451435-cac869d6-849b-4d0f-9931-a8d6db9cef78.png)
![image](https://user-images.githubusercontent.com/62423083/197451483-70e89010-ed96-4357-8079-b5a061a239d6.png)

**Comment by H-cognna** [comment]
Hello @nasbench @frack113 
Thanks for your response

I think the [not_bound_keyword option](https://github.com/SigmaHQ/sigma/blob/90aeea92bf0b1cbe6a3740591b7f9f8ae656efd2/tools/sigma/backends/elasticsearch.py#L72) you mentioned is not available for all backends, I have tried it with qradar for example it is not working

**Comment by nasbench** [comment]
Hi,

As I said the rule has an issue and currently won't ever trigger. It assumes the string `that did not meet the Microsoft signing level requirements` is part of the XML but it actually isn't. It's just part of the ETW `message` which isn't something we can use in the detection.

We will create a fix for the rule and let you know when it's done.
