### ISSUE TITLE
Rules could need modification /rules/windows/file/file_access/

### ISSUE THREAD

**Issue by H-cognna** [SigmaHQ/sigma#3634]
Hello
I have checked the rules in this folder, and one of the fields it is checking is:
FileName

However, I don't think there is a field to be checked with this name, I think here what it meant to be is:
TargetFilename

could you confirm this please?

**Comment by H-cognna** [comment]
Alright, I was actually looking on the sysmon event only, did not know about Microsoft-Windows-Kernel-File

It would be great to know the log source to match and confirm
Anyway, thanks a lot for clearing this out

**Comment by nasbench** [comment]
The log sources mapping is mentioned in the Sigma Taxonomy [here](https://github.com/SigmaHQ/sigma-specification/blob/main/Taxonomy_1_1_0.md). But now I see that `file_access` is missing and I will add it :)

**Comment by frack113** [comment]
It is not only for [Aurora](https://www.nextron-systems.com/aurora/) but is the easiest way to get sigma on ETW.
Will add information in the logsource section
