### ISSUE TITLE
Rules could need modification in /rules/windows/powershell/powershell_classic/

### ISSUE THREAD

**Issue by H-cognna** [SigmaHQ/sigma#3635]
Hello
I have checked the rules in this folder, and the fields that it is checking are:
ProviderName
HostName
HostApplication
EngineVersion
HostVersion

However, when seeing the event from 'Windows Powershell'
We can see that there are no such fields, they are all embeded in the event data

![image](https://user-images.githubusercontent.com/112784902/197743395-657c826e-148a-430e-896a-6a7c16349c5a.png)

I have checked it for both windows 10 and 11

So, I believe it should be changed
could you confirm this please?

**Comment by nasbench** [comment]
Hi,

Thanks for taking the time to review these.

You are correct in your logic. But as it's clearly stated in the rules in the `definition` section:

`definition: fields have to be extracted from event`

It's expected that the SIEM collecting these events to parse them and extract them into separate fields.

It could be worth discussing whether it's worth the effort to change them to use the `data` field similar to some other rules.

cc @frack113

**Comment by H-cognna** [comment]
Oh I believe I missed the definition on this one
Thanks for clearing this out
The thing is I am using Chainsaw tool to look for events in the endpoint, so I am not using SIEM for this task
however knowing this certainly help, Thanks!
