### ISSUE TITLE
Add attack.t1620 to proc_creation_win_base64_reflective_assembly_load.yml

### ISSUE THREAD

**Issue by sysradwin** [SigmaHQ/sigma#3698]
This is the most relevant MITRE technique to this rule.

Sorry, I've never done this before and I'm not sure if this is how you go about making a change to a project.

**Comment by nasbench** [comment]
Hi, 

Thanks for pointing this out and for contributing to the SIGMA project. What you could do is, fork this project and then modify the file by adding this tag to the list and then open a pull request.

If you're not familiar with this no worries just tell me and I'll add the tag myself :) 

Regards.

**Comment by sysradwin** [comment]
Thanks for helping me! I would like to attempt it myself for the learning experience, but what do you mean when you say "adding this tag to the list"? I think I can manage the other pieces.

**Comment by sysradwin** [comment]
Hello again, I think I did it correctly....it should be under #3707. Thanks again for your support

**Comment by nasbench** [comment]
Resolved in #3707
