### ISSUE TITLE
Rules with same title

### ISSUE THREAD

**Issue by jstnk9** [SigmaHQ/sigma#3699]
Hi guys

I just realized that there are some rules with the same `title` field. 

**title**: Remote Schedule Task Lateral Movement via SASec
**Rules**:

- https://github.com/SigmaHQ/sigma/tree/master/rules/application/rpc_firewall/rpc_firewall_sasec_recon.yml
- https://github.com/SigmaHQ/sigma/tree/master/rules/application/rpc_firewall/rpc_firewall_sasec_lateral_movement.yml

Is that a normal behavior or the rules should be renamed?

Thank you

**Comment by frack113** [comment]
Title should  be updated.
