### ISSUE TITLE
Change microsoft365_pst_export_alert.yml rule conditions

### ISSUE THREAD

**Issue by nikitah4x** [SigmaHQ/sigma#3701]
Hey,
During research I did on Office365 logs and alerts, I noticed that you just mentioned under the PST Export Rule a condition based on "eventName: 'eDiscovery search started or exported'".
This event name is based on eDiscovery Alert that can be disabled, and then this condition will not work.
During my research, I found that you can correlate with eventSource: SecurityComplianceCenter and ExtendedProperties contain ("-Export" AND "New-ComplianceSearchAction").

**Comment by nasbench** [comment]
Hi,

Thanks for opening this issue. You can open a PR by forking the project and applying the fix you suggest.

Please include any public reference that links back to the suggestion you're making as it'll make it easier for other readers and users of the rule to understand the reasoning

**Comment by nasbench** [comment]
Resolved in #3705
