### ISSUE TITLE
Spelling error in title of proc_creation_macos_susp_execution_macos_script_editor.yml

### ISSUE THREAD

**Issue by 4A616D6573** [SigmaHQ/sigma#3706]
```title: Suspicious Exeution via macOS Script Editor```, should be ```title: Suspicious Execution via macOS Script Editor```

I would do a pull request on this but I don't have the "correct" tools from the device I had available right now.

https://github.com/SigmaHQ/sigma/blob/a3e6856764318c151e6661411f26ac3f4271fabc/rules/macos/process_creation/proc_creation_macos_susp_execution_macos_script_editor.yml

**Comment by nasbench** [comment]
Good catch. Will be fixed later today.
