### ISSUE TITLE
Deprecate broken rule: builtin/Mimikatz

### ISSUE THREAD

**Issue by defensivedepth** [SigmaHQ/sigma#3871]
The following is what I recently posted on the Sigma Slack:

```
@defensivedepth 
The Logsource on this rule is simply Windows - How do you all typically map this? Without further mapping, it just generates a rule that looks for a bunch of strings in all the fields.
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/win_alert_mimikatz_keywords.yml

The sigma spec / log sources page doesn't have any guidance on this type of configuration.
```
From that discussion, there was a point made that yes, this rule is broken, and that a good candidate for targeted fields would be command_line.

However, there are already a couple good quality commandline rules focused on mimikatz:
- https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mimikatz_command_line.yml

- https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_system_user_anomaly.yml

With this being the case, I would recommend that the builtin mimikatz rule be deprecated & retired.

**Comment by nasbench** [comment]
Hi and thanks for opening this issue.

The rule you mentioned isn't broken and is meant to work as you described.

When only a category is specified with no specific fields. It's called a `keyword` rule. The point of a keyword rule is to match on any field for that specific category in this case all event logs/etw logs that you collect from windows.

The reason behind this rule is that. Mimikatz was/is still a very relevant threat and the keywords used are very specific to it. You might get a `process_creation` event with a command line that uses those strings or you might get an AV alert that has those strings. Or perhaps an application log that logged an application crashing and contain some of those strings...etc.

Hope this clears things up for you.

**Comment by defensivedepth** [comment]
@nasbench Thanks for the quick response & the additional context.

I understand what you are saying, but the practical implementation of this logsource is not documented, clearly defined on how it should work, nor is it part of the sigma logsource spec.

How should I be implementing this in production? Sounds like I should somehow map this logsource to _all_ of the WEL fields in my environment?

**Comment by Neo23x0** [comment]
Yes, the alternative would be to duplicate the rule 3-10 times and change the log source to a more specific log source. 

```yaml
logsource:
     product: windows
     service: application
```
```yaml
logsource:
     product: windows
     service: security
```
etc.

**Comment by Neo23x0** [comment]
> Is that the suggested way of implementing this?

Yes. 
Some backends are able to apply these keywords to `_raw`, some are not. We know and accept that. 
But I figured that the `logsource` selection is the problem here.

**Comment by defensivedepth** [comment]
hmmm. I'll need to dig into this further on my end. I'm not sure that mapping it to a single index (elasticsearch backend) is going to fix the performance issues I am seeing.

**Comment by nasbench** [comment]
There is no "performance issue" if the rule is not focusing on that. As showcased above. You need to duplicate it X amount of time where X is the number of channels you want to target. The performance issue is accepted by those who want to run it.

It has one point which is to look at every event in any channel. If you want to make it performant then make it focus on a specific channel.

**Comment by defensivedepth** [comment]
There may be a miscommunication happening here. I understand the point of the rule. I need to go back to my custom field mapping config and see what I can tweak.

**Comment by Neo23x0** [comment]
Keyword rules in general can be pretty cost intensive. I remember them being the overkill for an ArcSight instance of a customer back then in 2018. 

The SIEM admins were like "To which field should we apply these strings?" Me: "to all of them". 
I can still see their faces.

**Comment by defensivedepth** [comment]
@Neo23x0 Right, I think that's probably the crux of the issue for me. If this is working as expected, that's fine, but I think it would be useful to call out these types of rules (`keyword`) in some way, and document it as such. They are currently mixed in with non-Keyword rules and it would be helpful if there was some type of distinction made.

ie 

"When only a category is specified with no specific fields. It's called a keyword rule. The point of a keyword rule is to match on any field for that specific category. This can be cost intensive, and these rules should be implemented with that in mind. These rules can be identified by ......"

**Comment by nasbench** [comment]
Here is an example of `Keywords` explained in the spec [here](https://github.com/nasbench/sigma-specification/blob/main/Sigma_specification.md#lists)

Rules similar to the one you mention are very rare in the SIGMA project (practically this is the only rule that searches all fields in windows in such a greedy manner). Other rules might use this sometimes but it's not a **special** case. It's a conscious decision by the rule author and part of the spec.

Regarding the performance. My opinion is that this is similar to a regular expression rule. You should treat these greedy rules with the same mindset. No need for a special clasification.

**Comment by frack113** [comment]
Hi, @defensivedepth 
- Elastic performance issue
The trouble is when you use ".*: somethink" , you ask elastic to check every field.
If you have the original log in raw text (message , event.original,...) can can search the words ***only*** into it.

- Keywords "rule"
Some rules are only keywords, but other are mix of field and keywords search.
Keywords (Lists) search is a possibility offered by the sigma language

When I order many file , I have keep it in the builtin folder.
Perhaps it is necessary a repertory for this type of rule (product only no field) to help the people who collect the rules.
If you want you can open a discution to find a generic name , and I will do some tidying up.

**Comment by Neo23x0** [comment]
Maybe it isn't a bad idea to somehow mark / sort out the keyword rules and maintain them in a separate folder / sub folder or add a field that indicates the `type` of a rule.

**Comment by frack113** [comment]
I was more thinking of a rules/__os__/generic when the rule have only a os as product.
Most of the gereric os rules are list selection only, it is a good side effect.
We started ordering the rule by logsource , I don't add subfolder for the selection type.

**Comment by nasbench** [comment]
You are extrapolating a problem that doesn't exist. There aren't any other rules that are greedy such as this one. This one is important because it's mimikatz that's why it's not removed

Also, the keyword logic is part of the rule-creation process. It's the same as using regex or any other field. It's a choice, not a generic way to be classified as special.

**Comment by frack113** [comment]
I think we can close it as it is a elesticsearch trouble not a sigma one.

**Comment by defensivedepth** [comment]
I think there is some confusion in this thread around terminology.  `keyword` rule etc. This may have muddied the waters a bit.

As I mentioned in the initial post and my follow-up -  from my perspective, the core of the issue is the Logsource.

At a minimum, I would suggest documenting the logsource for this rule: https://github.com/SigmaHQ/sigma-specification/blob/main/Taxonomy_specification.md#windows-folder

**Comment by frack113** [comment]
OK , 
It is not a rule or sigmac issue.

Can you open a discution on [sigma-specification](https://github.com/SigmaHQ/sigma-specification/discussions) to update Taxonomy.
