### ISSUE TITLE
Passing yaml detection rule name to be available in config

### ISSUE THREAD

**Issue by tiag01** [SigmaHQ/sigma#394]
Hi all,

I couldn't find where the detection rule file name is stored in the config - I could be missing something.

Use Case
During generation of the sigma rule to a backend, I put the rule filename within the detection, so people making changes to the rule, can go back to the source (the actual rule) and make the corresponding changes to the yml file.  Otherwise there is no lineage that can audited. 

I made a quick hack to support this:
- I updated collection.py with the init function to support the rulefilenname optional 
`def __init__(self, content, config=None, rulefilter=None, **rulefilename=None**)`
- In tools, sigmac,  I did a one line fix:
` parser=SigmaCollectionParser(f, sigmacongs, rulefilter, sigmafile)`

I would ideally like this to be core part of the product.  I am not married to my solution, anything that makes sense in your architecture would work for me - I just want the outcome where I can use this rule filename.

thanks!

**Comment by thomaspatzke** [comment]
Currently, the name of the file is not passed to the parser. Can you provide your code as pull request? I think my solution would look quite similar.

**Comment by tiag01** [comment]
Sure, I will see if I can get to that today.  I have been doing lots of feature adding to Sigma

**Comment by frack113** [comment]
Hello ,
I have  do it for my PR #1519
