### ISSUE TITLE
Bad rule match with proc_creation_win_copy_browser_data.yml

### ISSUE THREAD

**Issue by fritz-fritz** [SigmaHQ/sigma#3968]
Recently installed Aurora Agent Lite which utilizes Sigma rules and am triggering a match on [47147b5b-9e17-4d76-b8d2-7bac24c5ce1b](https://github.com/SigmaHQ/sigma/blob/0.22-1840-gff7b10445/rules/windows/process_creation/proc_creation_win_copy_browser_data.yml) which doesn't seem to be right.

Matching on:
move in CommandLine
\Mozilla\Firefox\Profiles in CommandLine

The command line:
"C:\Program Files\Mozilla Firefox\firefox.exe" --backgroundtask re<b>move</b>Directory C:\Users\username\AppData\Local<b>\Mozilla\Firefox\Profiles</b>\u4u4z8w5.default-release "" 0 .purge.bg_rm

It doesn't seem this rule is doing what was intended.

Perhaps there should be a space in the string before 'move'  to prevent this match. I think this would fix this particular case but not address the intended behavior of the rule.

**Comment by frack113** [comment]
Thank you for the reporting
As it is the command [move](https://www.geeksforgeeks.org/move-cmd-command/) it is `- 'move '`
