### ISSUE TITLE
Update MITRE ATT&CK Tag in "Port Forwarding Attempt Via SSH"

### ISSUE THREAD

**Issue by Kalatasme** [SigmaHQ/sigma#4005]
Hi Team,

The experimental detection for "Port Forwarding Attempt Via SSH" ([Link](https://github.com/SigmaHQ/sigma/blob/6c153bff3f3b5bc7f0edefe430b2a6f903fd98b2/rules/windows/process_creation/proc_creation_win_ssh_port_forward.yml)) is currently tagged with attack.t1021.001 for Remote Services: Remote Desktop, when it should probably be attack.t1021.004 for SSH.

**Comment by nasbench** [comment]
Hi,

Thanks for the heads up, will add the tag. But the current `attack.t1021.001` is also valid imo as it's targeting the usage of ssh as a reverse ssh tunnel to allow RDP traffic. An example on the MITRE page is stating how `S0382 - ServHelper` used that.
