### ISSUE TITLE
broken references for threathunterplaybook.com

### ISSUE THREAD

**Issue by zambomarcell** [SigmaHQ/sigma#4015]
Hi

The following links are dead (404) in rule **references**:

- https://threathunterplaybook.com/evals/apt29/detections/1.A.1_DFD6A782-9BDB-4550-AB6B-525E825B095E.html
- https://threathunterplaybook.com/evals/apt29/detections/3.B.2_C36B49B5-DF58-4A34-9FE9-56189B9DEFEA.html
- https://threathunterplaybook.com/evals/apt29/detections/3.C.1_22A46621-7A92-48C1-81BF-B3937EB4FDC3.html
- https://threathunterplaybook.com/evals/apt29/detections/4.A.3_09F29912-8E93-461E-9E89-3F06F6763383.html
- https://threathunterplaybook.com/evals/apt29/detections/4.B.2_59A9AC92-124D-4C4B-A6BF-3121C98677C3.html
- https://threathunterplaybook.com/evals/apt29/detections/4.B.4_83D62033-105A-4A02-8B75-DAB52D8D51EC.html
- https://threathunterplaybook.com/evals/apt29/detections/5.B.1_611FCA99-97D0-4873-9E51-1C1BA2DBB40D.html
- https://threathunterplaybook.com/evals/apt29/detections/6.B.1_6392C9F1-D975-4F75-8A70-433DEDD7F622.html
- https://threathunterplaybook.com/evals/apt29/detections/7.A.1_3B4E5808-3C71-406A-B181-17B0CE3178C9.html
- https://threathunterplaybook.com/evals/apt29/detections/7.A.2_F4609F7E-C4DB-4327-91D4-59A58C962A02.html
- https://threathunterplaybook.com/evals/apt29/detections/7.B.4_C10730EA-6345-4934-AA0F-B0EFCA0C4BA6.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190410151110.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190511223310.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190610201010.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190810201010.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190811201010.html
- https://threathunterplaybook.com/notebooks/windows/02_execution/WIN-190815181010.html
- https://threathunterplaybook.com/notebooks/windows/05_defense_evasion/WIN-180719170510.html
- https://threathunterplaybook.com/notebooks/windows/05_defense_evasion/WIN-190101151110.html
- https://threathunterplaybook.com/notebooks/windows/05_defense_evasion/WIN-190407183310.html
- https://threathunterplaybook.com/notebooks/windows/06_credential_access/WIN-170105221010.html
- https://threathunterplaybook.com/notebooks/windows/06_credential_access/WIN-180815210510.html
- https://threathunterplaybook.com/notebooks/windows/06_credential_access/WIN-190620024610.html
- https://threathunterplaybook.com/notebooks/windows/07_discovery/WIN-190625024610.html
- https://threathunterplaybook.com/notebooks/windows/07_discovery/WIN-190725024610.html
- https://threathunterplaybook.com/notebooks/windows/07_discovery/WIN-190826010110.html
- https://threathunterplaybook.com/notebooks/windows/08_lateral_movement/WIN-200902020333.html
- https://threathunterplaybook.com/notebooks/windows/08_lateral_movement/WIN-201009173318.html
- https://threathunterplaybook.com/notebooks/windows/08_lateral_movement/WIN-201009183000.html

relevant rules (45):
- [pipe_created_alternate_powershell_hosts_pipe.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/pipe_created/pipe_created_alternate_powershell_hosts_pipe.yml)
- [pipe_created_powershell_execution_pipe.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/pipe_created/pipe_created_powershell_execution_pipe.yml)
- [file_delete_win_sysinternals_sdelete_file_deletion.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/file/file_delete/file_delete_win_sysinternals_sdelete_file_deletion.yml)
- [file_event_win_susp_pfx_file_creation.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/file/file_event/file_event_win_susp_pfx_file_creation.yml)
- [file_event_win_startup_folder_file_write.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/file/file_event/file_event_win_startup_folder_file_write.yml)
- [file_event_win_wmiprvse_wbemcomn_dll_hijack.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/file/file_event/file_event_win_wmiprvse_wbemcomn_dll_hijack.yml)
- [registry_add_sysinternals_sdelete_registry_keys.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_add/registry_add_sysinternals_sdelete_registry_keys.yml)
- [registry_delete_removal_com_hijacking_registry_key.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_delete/registry_delete_removal_com_hijacking_registry_key.yml)
- [registry_set_wdigest_enable_uselogoncredential.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_set/registry_set_wdigest_enable_uselogoncredential.yml)
- [registry_set_terminal_server_tampering.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_set/registry_set_terminal_server_tampering.yml)
- [registry_set_terminal_server_suspicious.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_set/registry_set_terminal_server_suspicious.yml)
- [registry_set_new_application_appcompat.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/registry/registry_set/registry_set_new_application_appcompat.yml)
- [proc_creation_win_susp_webdav_client_execution.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_susp_webdav_client_execution.yml)
- [proc_creation_win_non_interactive_powershell.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_non_interactive_powershell.yml)
- [proc_creation_win_high_integrity_sdclt.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_high_integrity_sdclt.yml)
- [proc_creation_win_powershell_get_clipboard.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_powershell_get_clipboard.yml)
- [proc_creation_win_wmiprvse_spawning_process.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_wmiprvse_spawning_process.yml)
- [proc_creation_win_sdclt_child_process.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_sdclt_child_process.yml)
- [proc_creation_win_remote_powershell_session_process.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/process_creation/proc_creation_win_remote_powershell_session_process.yml)
- [image_load_scrcons_imageload_wmi_scripteventconsumer.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/image_load/image_load_scrcons_imageload_wmi_scripteventconsumer.yml)
- [image_load_alternate_powershell_hosts_moduleload.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/image_load/image_load_alternate_powershell_hosts_moduleload.yml)
- [image_load_susp_system_drawing_load.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/image_load/image_load_susp_system_drawing_load.yml)
- [image_load_wmiprvse_wbemcomn_dll_hijack.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/image_load/image_load_wmiprvse_wbemcomn_dll_hijack.yml)
- [image_load_wmi_module_load.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/image_load/image_load_wmi_module_load.yml)
- [posh_pc_alternate_powershell_hosts.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml)
- [posh_pc_remote_powershell_session.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/powershell/powershell_classic/posh_pc_remote_powershell_session.yml)
- [posh_pm_decompress_commands.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/powershell/powershell_module/posh_pm_decompress_commands.yml)
- [posh_pm_remote_powershell_session.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/powershell/powershell_module/posh_pm_remote_powershell_session.yml)
- [posh_pm_get_clipboard.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/powershell/powershell_module/posh_pm_get_clipboard.yml)
- [net_connection_win_remote_powershell_session_network.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/network_connection/net_connection_win_remote_powershell_session_network.yml)
- [win_security_protected_storage_service_access.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_protected_storage_service_access.yml)
- [win_security_scrcons_remote_wmi_scripteventconsumer.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_scrcons_remote_wmi_scripteventconsumer.yml)
- [win_security_lsass_access_non_system_account.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_lsass_access_non_system_account.yml)
- [win_security_syskey_registry_access.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_syskey_registry_access.yml)
- [win_security_scm_database_privileged_operation.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_scm_database_privileged_operation.yml)
- [win_security_wmiprvse_wbemcomn_dll_hijack.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_wmiprvse_wbemcomn_dll_hijack.yml)
- [win_security_dcom_iertutil_dll_hijack.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_dcom_iertutil_dll_hijack.yml)
- [win_security_ad_replication_non_machine_account.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_ad_replication_non_machine_account.yml)
- [win_security_ad_object_writedac_access.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_ad_object_writedac_access.yml)
- [win_security_sam_registry_hive_handle_request.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_sam_registry_hive_handle_request.yml)
- [win_security_dpapi_domain_masterkey_backup_attempt.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_dpapi_domain_masterkey_backup_attempt.yml)
- [win_security_remote_powershell_session.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_remote_powershell_session.yml)
- [win_security_dpapi_domain_backupkey_extraction.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_dpapi_domain_backupkey_extraction.yml)
- [win_security_scm_database_handle_failure.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/builtin/security/win_security_scm_database_handle_failure.yml)
- [create_remote_thread_win_loadlibrary.yml](https://github.com/SigmaHQ/sigma/tree/master//rules/windows/create_remote_thread/create_remote_thread_win_loadlibrary.yml)

**Comment by tibczy** [comment]
![image](https://user-images.githubusercontent.com/30168997/217245452-85003ab7-1790-45d9-84ba-2e516ddf2da9.png)

**Comment by nasbench** [comment]
Hi and thanks for pointing this out. I will work on replacements later today.
