### ISSUE TITLE
Mailbox Export to Exchange Webserver FP

### ISSUE THREAD

**Issue by jack-shirley** [SigmaHQ/sigma#4083]
### Rule UUID

516376b4-05cd-4122-bae0-ad7641c38d48

### Example EventLog

{"@timestamp":"2022-08-04T12:36:14.997Z","@metadata":{"beat":"winlogbeat","type":"_doc","version":"8.3.2"},"agent":{"type":"winlogbeat","version":"8.3.2","ephemeral_id":"fab1f587-df1e-4fa7-beed-f6288c833217","id":"e7bf2298-cbe5-4870-9799-37e0172984b8","name":"DESKTOP-RBMBVBJ"},"event":{"action":"Image loaded (rule: ImageLoad)","created":"2022-08-04T12:36:15.763Z","code":"7","kind":"event","provider":"Microsoft-Windows-Sysmon"},"log":{"level":"information"},"message":"Image loaded:\nRuleName: -\nUtcTime: 2022-08-04 12:36:14.988\nProcessGuid: {d470b00b-bd3e-62eb-ff03-000000000400}\nProcessId: 1848\nImage: C:\\Windows\\System32\\LocationNotificationWindows.exe\nImageLoaded: C:\\Windows\\System32\\user32.dll\nFileVersion: 10.0.19041.1503 (WinBuild.160101.0800)\nDescription: Multi-User Windows USER API Client DLL\nProduct: Microsoft® Windows® Operating System\nCompany: Microsoft Corporation\nOriginalFileName: user32\nHashes: SHA1=B27AFE066B8F194A367F8479D0F14C83F410DDC3,MD5=3D2A6411D06E658A2AB3C893CA691EA3,SHA256=0178536E572F7443CE276C92EC19A2265CEBF223BE3B535423E537F8F8A14080,IMPHASH=2ECEA936F51BE6BBAAA693392AB6C7B0\nSigned: true\nSignature: Microsoft Windows\nSignatureStatus: Valid\nUser: DESKTOP-RBMBVBJ\\matthew","host":{"architecture":"x86_64","name":"DESKTOP-RBMBVBJ","os":{"kernel":"10.0.19041.1826 (WinBuild.160101.0800)","build":"19044.1826","type":"windows","platform":"windows","version":"10.0","family":"windows","name":"Windows 10 Home"},"id":"d470b00b-9118-4e1b-9165-2b0c95dd0ab7","ip":["fe80::88bb:9077:abb2:2353","10.0.2.15","fe80::44dd:eab4:a9f9:8280","192.168.56.107"],"mac":["08:00:27:94:96:72","08:00:27:c8:f2:64"],"hostname":"DESKTOP-RBMBVBJ"},"winlog":{"computer_name":"DESKTOP-RBMBVBJ","task":"Image loaded (rule: ImageLoad)","version":3,"channel":"Microsoft-Windows-Sysmon/Operational","opcode":"Info","user":{"type":"User","identifier":"S-1-5-18","domain":"NT AUTHORITY","name":"SYSTEM"},"event_data":{"SignatureStatus":"Valid","ProcessGuid":"{d470b00b-bd3e-62eb-ff03-000000000400}","Signed":"true","Signature":"Microsoft Windows","User":"DESKTOP-RBMBVBJ\\matthew","Company":"Microsoft Corporation","Hashes":"SHA1=B27AFE066B8F194A367F8479D0F14C83F410DDC3,MD5=3D2A6411D06E658A2AB3C893CA691EA3,SHA256=0178536E572F7443CE276C92EC19A2265CEBF223BE3B535423E537F8F8A14080,IMPHASH=2ECEA936F51BE6BBAAA693392AB6C7B0","RuleName":"-","Image":"C:\\Windows\\System32\\LocationNotificationWindows.exe","Product":"Microsoft® Windows® Operating System","FileVersion":"10.0.19041.1503 (WinBuild.160101.0800)","OriginalFileName":"user32","ImageLoaded":"C:\\Windows\\System32\\user32.dll","UtcTime":"2022-08-04 12:36:14.988","ProcessId":"1848","Description":"Multi-User Windows USER API Client DLL"},"event_id":"7","provider_guid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","provider_name":"Microsoft-Windows-Sysmon","process":{"pid":5512,"thread":{"id":1476}},"api":"wineventlog","record_id":235336},"ecs":{"version":"8.0.0"}}

### Description

This Sigma Rule:

> title: Mailbox Export to Exchange Webserver
id: 516376b4-05cd-4122-bae0-ad7641c38d48
status: experimental
description: Detects a successful export of an Exchange mailbox to untypical directory or with aspx name suffix which can be used to place a webshell or the needed role assignment for it
references:
    - https://blog.orange.tw/2021/08/proxylogon-a-new-attack-surface-on-ms-exchange-part-1.html
author: Florian Roth (Nextron Systems), Rich Warren, Christian Burkard (Nextron Systems)
date: 2021/08/09
modified: 2022/10/26
tags:
    - attack.persistence
    - attack.t1505.003
logsource:
    service: msexchange-management
    product: windows
detection:
    export_command:
        - 'New-MailboxExportRequest'
        - ' -Mailbox '
    export_params:
        - '-FilePath "\\\\' # We care about any share location
        - '.aspx'
    role_assignment:
        - 'New-ManagementRoleAssignment'
        - ' -Role "Mailbox Import Export"'
        - ' -User '
    condition: all of export_* or role_assignment
falsepositives:
    - Unlikely
level: critical

The "or" in the condition is causing any log with the string " -User " detection to be positive. Unsure if the "or" is supposed to be an "and" instead.

> condition: all of export_* **_and_** role_assignment

**Comment by nasbench** [comment]
Hey, @jack-shirley thanks for reporting. It seems there was a typo in the condition the last time this rule was updated. Going to get a fix for it asap.
