### ISSUE TITLE
Search Functionality Broken

### ISSUE THREAD

**Issue by HeckSec** [SigmaHQ/sigma#4137]
### Detailed Description of the Issue

When someone attempts to search the SIGMA HQ GitHub repo, no code (and thus no sigma rules) are displayed in the results. Only Commits and issues are typically displayed. This prevents users from searching for things like "regsvr32" or "wmic" and locating relevant rules. 

### Steps to Reproduce

(from browser)
1. Click the GitHub search bar in the top left of the page
2. Type in "wmic" and ensure that the "In this repository" search criteria is selected
3. Hit "return"/"enter"
4. Notice that the output does not contain any code repos, only commits and issues. 

### Expected Behavior

The expected behavior is for the search functionality to return code relevant to the search term. When searching for "wmic" it should return sigma rules relevant to this term (sigma rules that contain this term). 

### Actual Behavior

Search returns no code (relevant sigma rules) relating to search term. 

### Environment

Attempted on MacOS and Windows 10 from Chrome and Firefox browsers.

**Comment by HeckSec** [comment]
![sigma_hq_search_issue](https://user-images.githubusercontent.com/51425481/227262559-2e181b51-ef62-4395-b95c-c9c16e419445.png)

**Comment by HeckSec** [comment]
> This is not an issue of SIGMA but an issue of GitHub.

How are you able to confirm this? I'm not certain it is a GitHub issue. Searching other repos across various GitHub repositories and I have no issues.

**Comment by Neo23x0** [comment]
It's a Github issue. We don't write our rules with invisible ink. 

You can use https://sigmasearchengine.com/ as an alternative for what you want to accomplish.

**Comment by nasbench** [comment]
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/8741929/228399210-7570269b-40d0-4cda-aae3-2ef64df85fd2.png">

@HeckSec Its working as you can see :)

You can use many other features to search if it doesn't work for you
- @Neo23x0  suggestion https://sigmasearchengine.com/ 
- Github VsCode functionality by clicking `.`while you're on a repo
- Cloning the repo is an option and using the SIGMA VsCode extension
- Using Github Search while its still alive https://cs.github.com/SigmaHQ/sigma/

**Comment by nasbench** [comment]
@HeckSec after some searching it seems that you need to enable new GH search by visiting this https://github.com/search?type=code&auto_enroll=true and use this query `repo:SigmaHQ/sigma rundll32` afterwards it should be working fine.

Let me know if it worked for you.
