### ISSUE TITLE
Identify event sequencing

### ISSUE THREAD

**Issue by monkeyspirit** [SigmaHQ/sigma#4169]
Hello,

I was wondering if there are any plans or already a way for Sigma to identify event sequencing. I read about the **_near_** operator on the issues but I don't see it in the docs. Are there any specifications for events' aggregation?

Thanks

**Comment by nasbench** [comment]
Hi,

What you're looking for is called SIGMA correlation. It was "supported" in the old [legacy sigma tools](https://github.com/SigmaHQ/legacy-sigmatools) and you can read more about it here in the [spec](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md) just search for aggregation or near operator.

As the name suggest legacy sigma tools are going out of support and currently are being replaced by [PySIGMA](https://github.com/SigmaHQ/pySigma). There are plans to continue support of correlation with a new and enhanced version. You can read the draft spec of correlation V2 [here](https://github.com/SigmaHQ/sigma-specification/blob/version_2/Sigma_meta_rules.md).
