### ISSUE TITLE
Error in proc_creation_win_tscon_rdp_redirect.yml?

### ISSUE THREAD

**Issue by L015H4CK** [SigmaHQ/sigma#4241]
Hello everyone,

when looking into the [proc_creation_win_tscon_rdp_redirect](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tscon_rdp_redirect.yml) rule, I noticed a difference in the command line field compared to the referenced sources.

- the rule checks if the command line contains ` /dest:rdp-tcp:`.
- the referenced sources ([1](http://www.korznikov.com/2017/03/0-day-or-feature-privilege-escalation.html), [2](https://doublepulsar.com/rdp-hijacking-how-to-hijack-rds-and-remoteapp-sessions-transparently-to-move-through-an-da2a1e73a5f6)) contain the following command line: `sc create sesshijack binpath= "cmd.exe /k tscon 1 /dest:rdp-tcp#55"`
- the difference is in the `:`/`#` charachter right after `rdp-tcp`.

Executing the given example command lines results in an event that would not trigger the rule.
Does the rule work as intended and tries to detect something different than referenced in the sources or does the rule contain a typo?

Info:
- The [tscon documentation](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/tscon) does not give any hints about the given session name with `/dest`
- This [RDP Hijacking example by red canary](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1563.002/T1563.002.md) also shows `rdp-tcp#55`

**Comment by nasbench** [comment]
Fixed in #4242

**Comment by L015H4CK** [comment]
Hello nasbench, thank you for the quick response and resolving the issue! :)
