### ISSUE TITLE
Error in proc_creation_win_apt_sofacy.yml?

### ISSUE THREAD

**Issue by L015H4CK** [SigmaHQ/sigma#4245]
Hello everyone,

when looking into the [proc_creation_win_apt_sofacy](https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2018/TA/APT28/proc_creation_win_apt_sofacy.yml) rule, I noticed a difference in the command line field compared to the referenced sources.

- the rule checks if the command line contains `%APPDATA%\`
- the referenced sources state that "the loader will then create the batch file %LOCALAPPDATA% ..." [[1]](https://unit42.paloaltonetworks.com/unit42-sofacy-attacks-multiple-government-entities/) and show the command line `rundll32.exe "C:\Users\admin\AppData\Local\cdnver.dll",#1"`[[2]](https://twitter.com/ClearskySec/status/960924755355369472/photo/4)
- the difference is, that `%appdata%` resolves to `C:\Users\user\AppData\Roaming` and `%localappdata%` resolves to `C:\Users\user\AppData\Local`

I understand that (according to the [Sigma specification](https://sigmahq.github.io/sigma-specification/Sigma_specification.html) for placeholders) the placeholders are resolved during the rule conversion according to a config file. Still, I think using %APPDATA% instead of %LOCALAPPDATA% could be a bit misleading at this point.
When I understand the rule correctly, it should should not trigger the referenced command lines as it is now, since it checks for `C:\Users\User\AppData\Roaming\` and the command line contains `C:\Users\User\AppData\Local\`.

Proposed change:
- replace `%APPDATA%` with `%LOCALAPPDATA%` in the rule
- or replace `%APPDATA%` with `\AppData\Local\` in the rule

If my understanding is correct, I will gladly implement the proposed change and open a pull request.

Additional info:
- state of the rule: `test`
- the second reference is outdated and redirects to https://hybrid-analysis.com/
  - old: https://www.reverse.it/sample/e3399d4802f9e6d6d539e3ae57e7ea9a54610a7c4155a6541df8e94d67af086e?environmentId=100
  - proposed update: https://www.hybrid-analysis.com/sample/ff808d0a12676bfac88fd26f955154f8884f2bb7c534b9936510fd6296c543e8?environmentId=110

**Comment by nasbench** [comment]
Thanks @L015H4CK for the issue. I'll look into it and report back :)

**Comment by nasbench** [comment]
Fixed and should be merged later today :)
