### ISSUE TITLE
Question regarding whitespace in proc_creation_win_susp_eventlog_clear command line detection

### ISSUE THREAD

**Issue by L015H4CK** [SigmaHQ/sigma#4275]
Hello everyone,

when looking into the [proc_creation_win_susp_eventlog_clear](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_eventlog_clear.yml) rule, I noticed that some command line detections might have unnecessary or even too much whitespace.

The rule has three parts: wevtutil, powershell and wmic. For the first two parts, for some cases I wonder if there is a reason to include spaces at the end, e.g. `'clear-log '` or `'Clear-EventLog '`, or if these can be cut off. I understand that for the short detections like `' cl '` and `' sl '` the spaces are necessary to avoid false positives.

But for the wmic part, I think the spaces at the end even break the rule. The rule detects a command line containing `' ClearEventLog '` but clearing event logs using wmic looks something like this: `wmic nteventlog where filename="windows powershell" cleareventlog`. (So without anything coming after the `cleareventlog` part.) Thus, clearing event logs using wmic is not detected by this rule.

Proposed change:
I think, an easy fix would be to change line 42 of the rule to `CommandLine|contains: 'ClearEventLog'`, i.e. remove the spaces.

If my understanding is correct, I will gladly implement the proposed change and open a pull request.

Best regards,
Louis

**Comment by nasbench** [comment]
Thanks for raising this issue, will look into it and see if any changes are required

**Comment by nasbench** [comment]
Alright checked and updated, its seem that this was an error introduced in the past indirectly. Thanks once again :)
