### ISSUE TITLE
Variable with dot in the agg-function count()

### ISSUE THREAD

**Issue by RuthlessAndRude** [SigmaHQ/sigma#434]
I'm trying to use variable with the dot in it inside count() structure, but it doesn't works.
Here is the example of the condition section:
`condition: execlogs and keywords | count(process.title) by host > 6`.

I'm getting following error:
`Unexpected token in condition at position .title) by host > 6`

**Comment by zouzias** [comment]
As a work-around, you can use the `fieldsMapping` (see below) to rename your field from the source system to sigma rule field name:

https://github.com/Neo23x0/sigma/blob/master/tools/config/winlogbeat.yml#L48

You need to add a line `Title: process.title` in your case and then the condition is

```
 condition: execlogs and keywords | count(Title) by host > 6.
```

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
