### ISSUE TITLE
Very weak hash based rules are trivial to bypass

### ISSUE THREAD

**Issue by scudette** [SigmaHQ/sigma#4348]
### Description of the Idea of the Rule

While reviewing this repository for a Blackhat Presentation I noticed that there are many driver load rules such as this https://github.com/SigmaHQ/sigma/blob/master/rules/windows/driver_load/driver_load_win_vuln_dell_driver.yml

Which use MD5/SHA1/SHA256 whole of file hashes. Since whole of file hashes are trivial to modify these rules are extremely weak.

On the other hand because these are drivers and need to maintain a valid signature it is much harder to modify the imp hash of the binary (because the import table is inside the authenticode hash). Modifying the import table will invalidate the hash preventing the driver from loading.

Sysmon already provides the imp hash anyway (right next to the other hashes) so it seems like a shame to skip this opportunity to strengthen the rule.

**Comment by phantinuss** [comment]
Some thoughts:
- As far as I can see the loldrivers project doesn't have the Imphash in it's database. As long as that is the case, we cannot use it in the auto-generated rules
- Also you have to make sure that the Imphash is unique to the sample and not shared with other PEs (therefore we cannot even use it for automatically generated rules)

I like the idea. As long as the Imphash is specific it's a nice addition to the rules of that type.

**Comment by nasbench** [comment]
Since the vulnerable drivers are for a specific version of a range of old versions the only way to target them is by using their hash or authentihash. The imphash is while it can be unique for some drivers its not a guarantee to target a vuln version if the imported function/libs were kept the same.

**Comment by scudette** [comment]
Afaik sysmon does not report the authenticode hash itself. That would be the best solution.

I agree that including the imp hash might lead to some false positives if the version of the driver is not vulnerable but the import table has not changed. But IMHO it's better to have some fp here rather than miss a byod attack. Most of those drivers do not occur naturally in most environments.

**Comment by nasbench** [comment]
I will enhance the script we have in LOLDrivers to show the imphash and offer it as an option for people who wants to use and have the capabilities to tune things. That would the best thing to do imo.

Thanks for your input

**Comment by nasbench** [comment]
Future rules will now be generated with Imphash too. See https://github.com/magicsword-io/LOLDrivers/pull/139 for reference
