### ISSUE TITLE
Read event of MsMpEng.exe should be whitelisted

### ISSUE THREAD

**Issue by nekopep** [SigmaHQ/sigma#4349]
### Rule UUID

75bf09fa-1dd7-4d18-9af9-dd9e492562eb

### Example EventLog

Sorry, I'm using data from my edr here, hope it will be sufficient.

Commande line: C:\ProgramData\Microsoft\Windows Defender\Platform\4.18.23050.5-0\MsMpEng.exe
Company name: Microsoft Corporation  
File Description: Antimalware Service Executable  
File version: 4.18.23050.5 (b79513656627928b5505482e6c59e640a77adba5)  
Internal name: MsMpEng.exe  
Original filename: MsMpEng.exe  
Product version: 4.18.23050.5  
Process name
MsMpEng.exe (pid=5060)   
  
Username: NT AUTHORITY\SYSTEM  
User SID: S-1-5-18  
Size: 133592 (130.46 KiB)   
SHA256: 165b1bca85a75f95f377e5bc7030830f193b2cca3793e9f2acf71cdb7efeb2fa 

windows event filesystem kind: read
windows event filesystem path: C:\Users\user.name\AppData\Local\Microsoft\Windows\SchCache\domain.name.sch

### Description

My EDR is detecting this event and I think it is a false positive. To be noted that my EDR detect a "Read" event on the file path C:\Users\user.name\AppData\Local\Microsoft\Windows\SchCache\domain.name.sch
I suspect sigma rules implies write only event (event11) and usually I whitelist "read" & "delete" events but this time it looks like even a read event should be suspect so I made this report, to potentially whitelist at the source rule

**Comment by phantinuss** [comment]
As you say the file_event is meant to trigger on file creation. Therefore this is not a false positive in the rule but an issue of the mapping of the category to the EDR events. What is the EDR in use? How is the rule conversion done?

**Comment by nekopep** [comment]
The EDR is harfanglab and the conversion is done by it when we upload a sigma rule (so kind of black box here).
I suspect harfang is able to detect more fine grained event on file access (read,write,delete,rename) than what sigma expect from a windows events.
My point of the report was that I suspect that the rule should also trigger an alert even on a read event (that windows events do not see?), so would be interestign to whitelist  MsMpEng.exe for EDR that do a little more.
But if you want to stick on file creation only, then you can close the bug report, I'll whitelist in the EDR directly :)

**Comment by frack113** [comment]
If you read the rule references to understand its context, the trigger is the creation of the "Active Directory Schema Cache File".
If you want to use the logsource "category: file_access", it's a different detection logic and therefore a different rule.

For you, it's a harfanglab bug that doesn't handle the logsource of the rule properly.
Logically, the other rules are also affected.
I advise you to get in touch with them to have this problem corrected.
