### ISSUE TITLE
Rule for "gzip -f", atomic red references "gzip -k"

### ISSUE THREAD

**Issue by Mladia** [SigmaHQ/sigma#4363]
Inconsistency between sigma rule and atomic red team scenario. Sigma rule is for gzip -f (force), but the atomic red team executes gzip -k (keep).  Is there any particular reason for chosing one over the other?

https://github.com/SigmaHQ/sigma/blob/202b79e8f8d192e8d4a7031c4146fc548230bef3/rules/linux/auditd/lnx_auditd_data_compressed.yml#L23C17-L23C17

https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf365fee2a9/atomics/T1560.001/T1560.001.md#atomic-test-6---data-compressed---nix---gzip-single-file

**Comment by nasbench** [comment]
Fixed and will be merged later
