### ISSUE TITLE
Problem of writing a sigma rule

### ISSUE THREAD

**Issue by Nyk0la5** [SigmaHQ/sigma#4368]
Good evening,
I'm asking you for help because I can't manage to write my rule to run under Thor in order to aggregate two events in my sigma rule.
To put it simply, I need to detect the creation of two files in the user's temporary folder with the same name but two different extensions (.dll and cmdline) generated by one and the same process. And/or the same thing, deleted.
I'm trying to perform correlation or aggregation, but I can't. Maybe I don't quite understand how the sigma rule is written.
Could you help me?
I've attached my rule.
Thank you very much.
Yours respectfully

[Sigma_rule.txt](https://github.com/SigmaHQ/sigma/files/12241439/Sigma_rule.txt)

**Comment by nasbench** [comment]
The SIGMA rule in question is using the old notation of correlation which is not supported. Also Thor doesn't support SIGMA aggregation. Other than that the syntax looks fine :)

Hope this help.
