### ISSUE TITLE
sysmon_control_panel_item.yml covers only manually execution if control.exe not in System32

### ISSUE THREAD

**Issue by super0xbad1dea** [SigmaHQ/sigma#444]
Hi,

The Rule sysmon_control_panel_item.yml says
`detection:
  selection:
    CommandLine: '*.cpl'
  filter:
    CommandLine:
      - '*\System32\\*'
      - '*%System%*'
  condition: selection and not filter`
This rule will only triggers in case where control.exe is not in \System32. 
Manually start of a cpl produce this CommandLine: 
`"C:\Windows\system32\Control.exe" firewall.cpl`
Automatically start of a cpl (by function Control_RunDLL or double-click) produce this CommandLine:
`"C:\Windows\System32\rundll32.exe" C:\Windows\System32\shell32.dll,Control_RunDLL C:\Windows\System32\inetcpl.cpl`

So, the intension of this rule is not fullfilled, because it doesn't cover the case described in MITRE; it covers only the very rare case, if somebody moves or copies control.exe to another place and start a cpl manually.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
