### ISSUE TITLE
question about wildcard and contains condition 

### ISSUE THREAD

**Issue by gen3111620** [SigmaHQ/sigma#4441]
Hello, thanks to this great source.

I have some question about this rule 

https://github.com/SigmaHQ/sigma/blob/b4eb5316fd80b9aa5f38e340e95bea5237705e62/rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml#L4

I want to know the meaning of the detection condition as below

###  selection: HostApplication|contains: *

Does it mean that  HostApplication has any value, it match?

or does it mean that the text inside it should contain "*" the star string match?

the result of my conversion using pysigma looks like this:

**HostApplication:***  <-- it looks like wildcard * query 
AND (NOT ((HostApplication:(powershell* OR C\:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe*)) OR ContextInfo:*Citrix\\ConfigSync\\ConfigSync.ps1*))

Reference conversion website used: https://sigmaio.app/

thanks

**Comment by nasbench** [comment]
The rule is looking for any `HostApplication` using a wildcard as its stated by the description/title.
