### ISSUE TITLE
Officialize New Conditionals for More Complex Sigmas Rules - For Documentation Purposes Only

### ISSUE THREAD

**Issue by ish-icarocesar** [SigmaHQ/sigma#4474]
### Officialize New Conditionals for More Complex Sigmas Rules - For Documentation Purposes Only

I would like to propose adding new conditionals to just the Sigma rules logic documentation, which will be read and interpreted by analysts.

My proposal would be to add the following conditionals:
- followedby
- groupby

I propose this because the outputs of my research are Sigma rules, however, many rules are a sequence or grouping of events. And no existing conditional supports writing Sigma rules with this level of granularity.

I know there is a challenge in making these conditionals work when automatically translating the Sigma rule into SIEM product languages. However, the idea would be to make such conditionals official only for the use of documentation of detection logic in Sigma.

### EQL Exemple of Sequence Rule

Below is a simple example of a rule in EQL, which predicts a sequence of events. At the moment, this type of rule cannot be documented in Sigma (at least, official conditionals cannot be used, for documentation purposes only)

```yaml
sequence by host.name with maxspan=60s
  [ process where event.code == "4688" and process.name == "cmd.exe" ]
  [ process where event.code == "4688" and process.name == "powershell.exe" ]
```

**Comment by nasbench** [comment]
I think the type of condition you're talking about are temporal correlations where you correlate 2 or more events in a defined time span. This is well documented by the correlation documentation [here](https://github.com/SigmaHQ/sigma-specification/blob/version_2/appendix_meta_rules.md) and will be part of the pySigma library sometime in the future as it's still a work in progress.

**Comment by ish-icarocesar** [comment]
I think that's enough, my man!! I didn't know about this specification!! Again, it's just for documentation, I believe this documentation is enough.

**Comment by nasbench** [comment]
Awesome man and thanks for the discussion. You might wanna save this https://sigmahq.io/

As its the new hub for everything related to Sigma you can find everything linked there and if not feel free to open an discussion or issue.

Thanks once again :)

Cheers.

**Comment by ish-icarocesar** [comment]
Yes, I will want to save this link haha. Thank you very much!!

**Comment by nasbench** [comment]
Hey, You got some more questions @ish-icarocesar ?

**Comment by ish-icarocesar** [comment]
Yes, a question arose, thank you very much for your attention!! Sorry to reopen this issue, but a question arose about the link you sent, in response to my request for conditionals that include certain more complex logic, for the Sigma rule documentation.

My doubt is that, when reading and analyzing the information contained in the documentation you provided, I identified that the condition identified as temporal allows the correlation of more than one sigma rule, within a given time.

However, if I didn't understand it wrong, this condition does not allow temporal correlation between two EVENTS (selections).
And I return to the example I used when opening the issue, I could use this condition with EVENTS (selections) that store certain characteristics. Simple example below:

```yaml
action: correlation
type: temporal
detection:
    selection1
       EventID:
         - 4688
       ProcessName|endwith:
         - "cmd.exe"
    selection2
       EventID:
         - 4688
       ProcessName|endwith:
         - "powershell.exe"
group-by:
    - ComputerName
    - User
timespan: 60s
ordered: true
```

**Comment by nasbench** [comment]
I understand what you mean but a sigma rule is meant to capture and trigger on a single event as its matching a log entry somewhere. A selection inside a Sigma rule is actually a condition grouping of some logic. So to correlate on 2 events you need more than one sigma rule in theory. 

You could argue that you can achieve this in a single rule similar to elastic's example via some syntax say like this

But the approach of having separate sigma rules and then using them to correlate is more flexible and readable for more complex rules.

And btw the document doesn't contain the latest updates as they're still in an open pr [here](https://github.com/SigmaHQ/sigma-specification/pull/91). But the final correlation format we agreed upon allows you to write multiple sigma rules in one file and you can even reference external rules via their.

A high level example of how to achieve what you're talking about will look like this.

```yml
RULE1 with its own selection
----
RULE2 with its own selection
----
Correlation rule using the 2 RULES
```

All of this in a single document. We'll share more in the future about correlation and some concrete example

Hope my answer help answer your questions (if that make sens lol)

**Comment by ish-icarocesar** [comment]
Yes you answered!! Thank you brother!!
