### ISSUE TITLE
[Enhancement Proposal] Add "offset" parameter in detection

### ISSUE THREAD

**Issue by herrBez** [SigmaHQ/sigma#448]
Add a parameter named "offset" in detection. This offset is the minimal distance between the search time and the query time range. 

Let us explain it with the aid of an example. Given a rule with the following "detection" section:
```
detection:
     timeframe: 24h
     offset: 1h
     selection: ...
```

We would search results in the range (`now - timeframe - offset`, `now-offset`).
The idea behind this enhancement proposal is that if we are searching inside a backend to which we continuously add data. It is possible, that the data currently indexed is still not available for search. This is the case for Elasticsearch, which indeed introduces the [refresh API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html) to assure that the operations performed are available. If we introduce this offset we enhance the probability that the data is available.

Do you think this change would make any sense?

Kind regards,
Mirko

**Comment by Karneades** [comment]
The same is for indextime vs time in Splunk. I think teams should add such specifics in their implementation and not in the generic rule. The offset is infrastructure specific and not a generic value.

**Comment by herrBez** [comment]
Thank you for your input. I think that this offset depends not solely from the "backend" (Elasticsearch, Splunk ecc.) but also by other parameters like the underlying HW and the amount of data indexed. The "rule" approach would give more granularity, but you are right that it would be the same (or at least very similar) for each query performed on a given backend. 

Maybe the best thing to do is to add a configurable backend-option (only hard-coded would be too unflexible) to each backend.

**Comment by Karneades** [comment]
> I think that this offset depends not solely from the "backend" (Elasticsearch, Splunk ecc.) but also by other parameters like the underlying HW and the amount of data indexed. 

That's the reason why I think we should not add such infrastructure specific values in rules. I also think this is not only a generic backend option, instead it depends on the exact source - so log source A must be handle differently than log source B. We use such offsets (or delayed searching) specific to log sources.

**Comment by thomaspatzke** [comment]
I think the backend configuration would be a better location for this, as this is a very SIEM-specific aspect.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
