### ISSUE TITLE
Uncommon Userinit Child Process: Add cmstart.exe to filter_optional_citrix

### ISSUE THREAD

**Issue by rkmbaxed** [SigmaHQ/sigma#4569]
### Rule UUID

0a98a10c-685d-4ab0-bddc-b6bdd1d48458

### Example EventLog

Image: C:\Program Files (x86)\Citrix\HDX\bin\cmstart.exe
Description: Citrix Client Manager Starting Utility
Product: Citrix XenApp & XenDesktop
Company: Citrix Systems, Inc.
OriginalFileName: CMStart.exe
CommandLine: cmstart.exe
ParentImage: C:\Windows\System32\userinit.exe
ParentCommandLine: C:\Windows\system32\userinit.exe

### Description

Add cmstart.exe to filter_optional_citrix, its a common Citrix executable file.

https://support.citrix.com/article/CTX983798/purpose-of-cmstart-command

```
 filter_optional_citrix:
        - Image|endswith: '\Citrix\System32\icast.exe'
        - Image|endswith: '\Citrix\HDX\bin\cmstart.exe'
```

**Comment by nasbench** [comment]
Thanks @rkmbaxed for this quick report. This FP will be fixed in #4564
