### ISSUE TITLE
c8b00925-926c-47e3-beea-298fd563728e Possible incorrect field/value pairing

### ISSUE THREAD

**Issue by Blackmore-Robert** [SigmaHQ/sigma#4572]
title: Remote Access Tool Services Have Been Installed - Security
id: c8b00925-926c-47e3-beea-298fd563728e

This is the first time I'm posting here and am hopefully adhering to the guidelines. 

This rule uses 'ServiceFileName' in the selection; however, based on my research into this Windows event and log, I think it should be 'ServiceName' instead. We could certainly use the 'ServiceFileName' field if we want to use the executable path instead. Please let me know if I've made an error, thanks!

![Rule](https://github.com/SigmaHQ/sigma/assets/112221099/15d3105a-bb50-4d97-8fd6-6ebec0c7e85b)

**Comment by nasbench** [comment]
Hey @Blackmore-Robert thanks for opening this issue. 

I agree with you this seems to be a typo/mistake in the rule. I'll get it fixed asap :)

Cheers.
