### ISSUE TITLE
elastalert - CommandLine and Keyword

### ISSUE THREAD

**Issue by PurpleV0id** [SigmaHQ/sigma#459]
Hi,

I have been testing some of the sigma rules converted for elastalert.
There are a number of rules I have picked on to test as they are easy:
win_netsh_fw_add.yml
win_netsh_port_fwd.yml
win_ransomware_shadowcopy.yml
These rules are purely based on CommandLine rather than Image and CommandLine like win_cmdkey_recon.yml

These CommandLine rules have been converted to .keyword and are not matching due to the actual commandline been:
"c:\windows\system32\netsh.exe" interface portproxy add v4tov4
as an example.

However the sigma rule is:
query: (event_id:"1" AND process_command_line.keyword:(netsh\ interface\ portproxy\
        add\ v4tov4\ *))

For keyword to work this would have to be query: (event_id:"1" AND process_command_line.keyword:(*netsh*\ interface\ portproxy\
        add\ v4tov4\ *))
so that netsh matches netsh.exe"

Alternatively to not use keyword and have a rule without the wildcards as that stops the rule from hitting as the field is analyzed.  ie

      query: (event_id:"1" AND process_command_line:(netsh\ interface\ portproxy\
        add\ v4tov4\ ))

Thanks
Phil

**Comment by fryguy04** [comment]
Yes ^^^ I actually was just coming here to raise the same issue and curious how to solve. I was running very basic Recon like so ... 
`c:\windows\system32\net.exe" group "domain admins" /domain`

Which _win_susp_commands_recon_activity.yml_ was intended to detect but missed it due to Sysmon adding **.exe** ... also it was **net.exe** not **net1** as in the rule

I can see this being an issue across many rules so wanted to hear proposed fixes could be

**Comment by fryguy04** [comment]
another somewhat different issue is rules that match commandline but arguments can be position independent ie: `test.exe -f attack -z now` vs `test.exe -z now -f attack` ... can open a separate ticket for this, don't mean to derail

**Comment by PurpleV0id** [comment]
Have to appologise, i messed up the copy paste.  The working solution (for me) to the net.exe would be:
(event_id:"1" AND process_command_line.keyword:(*netsh* interface\ portproxy\
        add\ v4tov4\ *))

I used notepad++ to find these type of rules, beleive there were around 20.

I decided to test a few permutations and document them as i found *netsh*\ would not work:
Does not work
process_command_line.keyword:*vssadmin.exe*\ delete shadows
process_command_line.keyword:*vssadmin.exe\ delete shadows
process_command_line.keyword:*vssadmin\ delete shadows
process_command_line.keyword:*\\vssadmin.exe\ *

works
process_command_line.keyword:*vssadmin.exe* delete shadows
process_command_line.keyword:*vssadmin* delete shadows

In response to test.exe and variations of command order, reducing what is searched for could help with the potnetial permutations:

If attack was command that was required
process_path.keyword:*\\test.exe AND process_command_line:attack

I will be testing more commands hopefully this week and will try and give my feedback.

**Comment by r1d3th3wav3s** [comment]
Hi,

Any update on this issue? I have the same problem for example with rule win_office_spawn_exe_from_users_directory.yml: Converting it to elastalert I get the following query:

((process.parent.executable.keyword:(*\\WINWORD.EXE OR *\\EXCEL.EXE OR *\\POWERPNT.exe OR *\\MSPUB.exe OR *\\VISIO.exe) AND process.executable.keyword:C\:\\Users\\* AND process.executable.keyword:*.exe) AND (NOT process.executable.keyword:*\\Teams.exe))

But to work it should be:
((process.parent.executable:(*\\WINWORD.EXE OR *\\EXCEL.EXE OR *\\POWERPNT.exe OR *\\MSPUB.exe OR *\\VISIO.exe) AND process.executable:C\:\\Users\\* AND process.executable:*.exe) AND (NOT process.executable:*\\Teams.exe))

**Comment by frack113** [comment]
You must use the backend options : 
```bash
PS D:\rootme\sigma\tools> python sigmac -t es-qs -c .\config\winlogbeat-modules-enabled.yml ..\rules\windows\process_creation\proc_creation_win_office_spawn_exe_from_users_directory.yml --backend-option keyword_blacklist="process.parent.executable,process.executable"
((process.parent.executable:(*\\WINWORD.EXE OR *\\EXCEL.EXE OR *\\POWERPNT.exe OR *\\MSPUB.exe OR *\\VISIO.exe OR *\\MSACCESS.exe OR *\\EQNEDT32.exe) AND process.executable:C\:\\users\\* AND process.executable:*.exe) AND (NOT (process.executable:*\\Teams.exe)))
PS D:\rootme\sigma\tools>
```

Here `keyword_blacklist`
