### ISSUE TITLE
proc_creation_win_susp_bad_opsec_sacrificial_processes Chrome Installer False Positives

### ISSUE THREAD

**Issue by AaronS97** [SigmaHQ/sigma#4613]
### Rule UUID

a7c3d773-caef-227e-a7e7-c2f13c622329

### Example EventLog

N/A

### Description

It appears that issue #4571 was opened by @celalettin-turgut to report false positives for this rule originating from the Google Chrome installer process spawning a Rundll32.exe process with no command line arguments. When this fix was applied, it seems that the condition was incorrectly updated to include these false positives, rather than exclude them. The condition field says "1 of selection_* and not 1 of filter_main_* and 1 of filter_optional_\*", when I believe it should be "1 of selection_* and not 1 of filter_main_* and not 1 of filter_optional_*"

**Comment by nasbench** [comment]
Hey @AaronS97 thanks for pointing this out. Will get a fix for it :)
