### ISSUE TITLE
Logsources, lack of machine readable definition of log sources (and additional requirements)

### ISSUE THREAD

**Issue by MrSeccubus** [SigmaHQ/sigma#4669]
I have been doing some reseach over the past few days to figure out if I can easily determe the log sources that I need to have based on the signatures I have enabled or .e.g detect which signatures I have enabled, but I don't have the log source for (yet).

The resources I have found sofar are:
* https://github.com/SigmaHQ/sigma-specification/blob/main/Taxonomy_specification.md
* https://github.com/SigmaHQ/sigma/blob/master/documentation/tools/sigma-logsource-checker.py (which seems to cover only windows logs)
* https://github.com/SigmaHQ/sigma/tree/master/documentation/logsource-guides

The taxonomy specification is reasonably complete, but not machine readable.
sigma-logsource-checker.py seems to be quite comprehensive when it comes to windows log sources, but it's output is not machine readable and it's input is hard coded into the source.
And the logsources-guide is again not machine readable and far from complete.

I'm thinking along the lines of a simple YAML file that is like this:

```
applications:
	django:
		product: django
		category: applicaiton
	python:
		product: python
		category: applicaiton
	rpc_firewall:
		product: rpc_firewall
		category: applicaiton
	ruby_on_rails:
		product: ruby_on_rails
		category: applicaiton
	spring:
		product: spring
		category: applicaiton
	sql:
		product: sql
		category: applicaiton

windows:
	any:
		description: Any windows log file
		product: windows
	windows_clipboard_capture:
		category : clipboard_capture
		product: windows
		description : "EventID: 24 - Channel: Microsoft-Windows-Sysmon/Operational"
	windows_create_remote_thread:
		category : create_remote_thread
		product: windows
		description : "EventID: 8 - Channel: Microsoft-Windows-Sysmon/Operational"
	windows_create_stream_hash:
		category : create_stream_hash
		product: windows
		description : "EventID: 15 - Channel: Microsoft-Windows-Sysmon/Operational"
	windows_security:
		service : security
		product: windows
		description : "Channel: Security"
		conditional: #Example of how to tackle sigma-logsource-checker.py type checks
			audit_credential_validation:
				"EventIDs": [4774, 4775, 4776, 4777]
				"description" : "Audit Credential Validation"
				"policy_id" : "{0CCE923F-69AE-11D9-BED3-505054503030}"
			audit_kerberos_authentication_service:
				"EventIDs": [4768, 4771, 4772]
				"description" : "Audit Kerberos Authentication Service"
				"policy_id" : "{0CCE9242-69AE-11D9-BED3-505054503030}"
```

Does something along these lines exists? If it doesn;t exist would it be

**Comment by nasbench** [comment]
Hey,

Your request is reasonable. What you can use to start is to use this https://github.com/SigmaHQ/sigma/blob/master/tests/logsource.json. Which is a file we use for the CI pipelines. It contains information about product, service and category (should be a very good start)

Other than that you're more than welcome (and encouraged) to create one if the above doesn't fit your need and maybe contribute it back in the specification repo :D

**Comment by nasbench** [comment]
@MrSeccubus i'll be closing this issue as resolved soon if you have no further questions :)

**Comment by MrSeccubus** [comment]
Just one  question and then I guess I should start writing ;)
What would be the best location for the file? I would suggest: documentation/logsource-guides/logsources.json in the main rule repo.
