### ISSUE TITLE
[Enhancement Proposal] Add Tasks section to spec

### ISSUE THREAD

**Issue by defensivedepth** [SigmaHQ/sigma#467]
Though there is currently a [Fields](https://github.com/Neo23x0/sigma/wiki/Specification#fields) and [False Positive ](https://github.com/Neo23x0/sigma/wiki/Specification#falsepositives) section in the spec, I think it would be useful to have a more direct section that can be used to describe explicitly what the next steps should be for an analyst when reviewing results generated by the Sigma. 

For example, please see the `Tasks` section in the following Sigma: https://gist.github.com/defensivedepth/82fc1a55aaa3496b39e50fa555106ec9

This also maps very neatly to using something like TheHive's case templates - [screencap](https://www.screencast.com/t/pmgFyfbB).  You can see this in action on the following video demo, where we automatically generate the case template + tasks from the Sigma (starting around 6 minutes into the demo):  https://www.screencast.com/t/jhXEbl3pxm72

**Comment by neu5ron** [comment]
@defensivedepth did you implement this in SO already?

**Comment by defensivedepth** [comment]
Yes, we are using this in Security Onion Hybrid Hunter. The `tasks` become part of `thehive` case template.

1) Tasks as part of the Sigma - https://www.screencast.com/t/OJSdO4pgmj

2) Tasks used to create `thehive` case template - https://www.screencast.com/t/OakRC4JTB86
