### ISSUE TITLE
Adding new hosting sites to downloading rules

### ISSUE THREAD

**Issue by omaramin17** [SigmaHQ/sigma#4708]
### Description of the Idea of the Rule:
It has been observed from the recently published Microsoft blog, the usage of multiple hosting sites such as onrender.com, glitch.me, and supabase.co for malware delivery,  where they create a unique subdomain, such as test-project.onrender.com, and connect the project to their GitHub Pages to host malicious files, making these accessible from such subdomains

![image](https://github.com/SigmaHQ/sigma/assets/25645659/655e4c18-5080-40fa-90f2-fa481fd708fc) -> an example from onrender dashboard where i created a project called threat-test.onrender.com and connected it to my github page repository .

Adding these sites :

- onrender.com
- glitch.me 
- supabase.co

to the following rules :

* [win_bits_client_new_transfer_via_file_sharing_domains.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/builtin/bits_client/win_bits_client_new_transfer_via_file_sharing_domains.yml)
* [proc_creation_win_bitsadmin_download_file_sharing_domains.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/process_creation/proc_creation_win_bitsadmin_download_file_sharing_domains.yml)
* [create_stream_hash_file_sharing_domains_download_susp_extension.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/create_stream_hash/create_stream_hash_file_sharing_domains_download_susp_extension.yml)
* [proc_creation_win_certutil_download_file_sharing_domains.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/process_creation/proc_creation_win_certutil_download_file_sharing_domains.yml)
* [proc_creation_win_wget_download_susp_file_sharing_domains](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/process_creation/proc_creation_win_wget_download_susp_file_sharing_domains.yml)
* [create_stream_hash_file_sharing_domains_download_unusual_extension](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/create_stream_hash/create_stream_hash_file_sharing_domains_download_unusual_extension.yml)
* [win_appxdeployment_server_susp_domains.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/builtin/appxdeployment_server/win_appxdeployment_server_susp_domains.yml)
* [proc_creation_win_curl_download_susp_file_sharing_domains.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/process_creation/proc_creation_win_curl_download_susp_file_sharing_domains.yml)
* [net_connection_win_binary_susp_com.yml](https://github.com/SigmaHQ/sigma/blob/889efd1663f0781e110f32e8e81e88a311e6c500/rules/windows/network_connection/net_connection_win_binary_susp_com.yml)

### Public References
https://www.microsoft.com/en-us/security/blog/2024/01/17/new-ttps-observed-in-mint-sandstorm-campaign-targeting-high-profile-individuals-at-universities-and-research-orgs/

**Comment by nasbench** [comment]
Thanks @omaramin17 

I will get the rules updated as soon as I can.

**Comment by nasbench** [comment]
Resolved in #4702
