### ISSUE TITLE
Symantec vs. Disable Windows Defender Functionalities Via Registry Keys

### ISSUE THREAD

**Issue by Snp3r** [SigmaHQ/sigma#4896]
### Rule UUID

0eb46774-f1ab-4a74-8238-1155855f2263

### Example EventLog

Registry value set:
RuleName: T1089,Tamper-Defender
EventType: SetValue
UtcTime: 2024-07-02 10:34:00.830
ProcessGuid: {*id removed*}
ProcessId: 1111
Image: C:\Program Files\Symantec\Symantec Endpoint Protection\14.3.9681.7000.105\Bin64\sepWscSvc64.exe
TargetObject: HKU\.DEFAULT\Software\Microsoft\Windows\CurrentVersion\Group Policy Objects\{*id removed*}Machine\Software\Policies\Microsoft\Windows Defender\DisableAntiSpyware
Details: DWORD (0x00000001)
User: NT AUTHORITY\SYSTEM
ParentProcessGuid: {*id removed*}
ParentImage: C:\Windows\System32\services.exe
ParentCommandLine: C:\Windows\system32\services.exe
GrandParentProcessGuid: {*id removed*}
GrandParentImage: C:\Windows\System32\wininit.exe
GrandParentCommandLine: wininit.exe

### Description

We have a lot of false positives with Symantec Endpoint Protection, example eventlog above. Thank you for your work!

**Comment by nasbench** [comment]
Resolved in #4888
