### ISSUE TITLE
Rules detected as threats by Windows Defender

### ISSUE THREAD

**Issue by Alex-C-github** [SigmaHQ/sigma#4925]
Hello,

I just got two threats detected and quarantined by Windows Defender while using the Sigma rules through Aurora agent lite.

Here are the concerned rules:
|Rule file|Detection type|
|------------|----------------|
|windows\powershell\powershell_script\posh_ps_tamper_windows_defender_set_mp.yml|Trojan:Script/Phonzy.A!ml|
|windows\powershell\powershell_classic\posh_pc_tamper_windows_defender_set_mp.yml|Trojan:Win32/BatTamper.A|

Other people also have the same issue : https://github.com/NextronSystems/aurora-agent-lite/issues/13

**Comment by nasbench** [comment]
Thanks for reporting this. As I explained in this https://github.com/NextronSystems/aurora-agent-lite/issues/12
AV detecting clear text rules that contains strings and keyword that can be considered suspicious is not anything we can take care of from here.
The rule uses these strings to detect potential tampering with defender and defender itself seems to have created a signature that matches on this.
The solution is to encrypt the rules (which is something offered by Aurora enterprise version). For now, just add those 2 rules as exclusions. Also submit those 2 files to Microsoft (https://www.microsoft.com/en-us/wdsi/filesubmission) and report them as false positives

**Comment by KakouMoses** [comment]
Same issue but with _rem_mp.yml at the end of the filename... Was wondering if it had anything to do with you or is it an unwanted file
