### ISSUE TITLE
Rule compile issue - wrong filter names or wrong condition - rule "Potential DLL Sideloading Of DbgModel.DLL"

### ISSUE THREAD

**Issue by smitstephan** [SigmaHQ/sigma#4926]
Hi, 
not exactly a FP but rather a rule issue;
When using Aurora Agent, I noticed a rule could not be compiled:

>  Could not compile rule 
>    Module: Sigma 
>    Error: no search identifier matches pattern filter_optional_* 
>    File: public\windows\image_load\image_load_side_load_dbgmodel.yml 
>    Id: fef394cd-f44d-4040-9b18-95d92fe278c0 
>    Title: Potential DLL Sideloading Of DbgModel.DLL

There is a `filter_main_generic`, which is covered by `filter_main_*` in the condition - OK.
The optional filters are named `filter_main_optional_windbg` and `filter_main_optional_windbg`, while the condition has extra checks for `filter_optional_*`.

https://github.com/SigmaHQ/sigma/blob/29d06798b35d1f551eb40073422cd4254f2306c6/rules/windows/image_load/image_load_side_load_dbgmodel.yml#L18

https://github.com/SigmaHQ/sigma/blob/29d06798b35d1f551eb40073422cd4254f2306c6/rules/windows/image_load/image_load_side_load_dbgmodel.yml#L23

https://github.com/SigmaHQ/sigma/blob/29d06798b35d1f551eb40073422cd4254f2306c6/rules/windows/image_load/image_load_side_load_dbgmodel.yml#L25

https://github.com/SigmaHQ/sigma/blob/29d06798b35d1f551eb40073422cd4254f2306c6/rules/windows/image_load/image_load_side_load_dbgmodel.yml#L29

From my understanding, either both optional filters need to be renamed (remove the `main_`) or the `and not 1 of filter_optional_*` removed in condition.
As an alternative, the condition for both optional filters could be changed to `filter_main_optional_*`, but that would be redundant as `filter_main_*` already matches all three filters.

Cheers

**Comment by nasbench** [comment]
Thanks for reporting this. There was an issue with the tests and it missed this. This will be fixed in #4928
