### ISSUE TITLE
Possible wrong detection of MacOS Startup Items

### ISSUE THREAD

**Issue by sebastianrath** [SigmaHQ/sigma#4962]
### Rule UUID

dfe8b941-4e54-4242-b674-6b613d521962

### Example EventLog

TargetFilename:/private/var/db/receipts/dev.actionforge.actrun.plist

### Description

I have the following report from my executable on VirusTotal.com.
https://www.virustotal.com/gui/file/d9543b98f88645e3951c85114a678297c99ad6bce4862502ecadc8766f5eff4d/

It is reported, that the check detected the creation of a startup item plist file. The rule is as follows:

https://github.com/SigmaHQ/sigma/blob/bfc5586e439ab11954292ec8a0be5b52b1657a2f/rules/macos/file_event/file_event_macos_startup_items.yml#L17-L22

I'm not familiar with the ruleset syntax. As you can see from the report, the match is: `/private/var/db/receipts/dev.actionforge.actrun.plist`

**Comment by nasbench** [comment]
Hey @sebastianrath and thanks for reporting this.

There is indeed a typo in the rule. I will get it fixed asap.

**Comment by sebastianrath** [comment]
Much appreciated!

**Comment by nasbench** [comment]
Issue resolved. Thanks once again @sebastianrath for the report.
