### ISSUE TITLE
Sigma yaml nesting question

### ISSUE THREAD

**Issue by djlukic** [SigmaHQ/sigma#4996]
Hi,

I would like to ask if Sigma completely supports nesting in its rule format:

Example of one filter:
```
    filter_optional_trend_micro:
        FileNameBuffer|endswith: '\Trend Micro\Client Server Security Agent\perficrcperfmonmgr.dll'
        RequestedPolicy: 8
``` 
I would like to add more conditions under this trend_micro filter using OR logic.
Is this a correct/acceptable modification:

```
    filter_optional_trend_micro:
        -
            FileNameBuffer|endswith: '\Trend Micro\Client Server Security Agent\perficrcperfmonmgr.dll'
            RequestedPolicy: 8
        -
            FileNameBuffer|endswith: 'tmumevt64.dll'
            FileNameBuffer|contains: 'windows\system32\tmumh'
        -   FileNameBuffer|endswith: 'tmmon64.dll'
``` 

Thank you!

**Comment by nasbench** [comment]
It is supported but not accepted in SigmaHQ. Also btw, you can use the sigma converter via sigma cli for all related tests of what's supported.
