### ISSUE TITLE
Could not compile rule

### ISSUE THREAD

**Issue by TheDudeasap** [SigmaHQ/sigma#5025]
### Rule UUID

f01d1f70-cd41-42ec-9c0b-26dd9c22bf29

### Example EventLog

{
  "Module": "Sigma",
  "aurora_eventid": 95,
  "error": "syntax error in selection element of rule Process Deletion of Its Own Executable: invalid Modifier \"fieldref\"",
  "file": "public\\windows\\file\\file_delete\\file_delete_win_delete_own_image.yml",
  "id": "f01d1f70-cd41-42ec-9c0b-26dd9c22bf29",
  "level": "error",
  "msg": "Could not compile rule",
  "time": "2024-09-27T20:16:55+02:00",
  "title": "Process Deletion of Its Own Executable",
  "_Match": [
    "-"
  ],
  "_Description": []
}

### Description

can someone tell me what that is ?

**Comment by nasbench** [comment]
Responded to your issue on pysigma.
Also for future reference, please refrain from opening the same issue on multiple repos :)
