### ISSUE TITLE
Correct aggregation for ElastAlert backend

### ISSUE THREAD

**Issue by spvcxsh1p** [SigmaHQ/sigma#5083]
Hello!
I have encountered a problem with using aggregation functions in SIGMA rules. I use ElastAlert as a backend.
When trying to convert a SIGMA rule that uses the count() by construct, I get an error that ElastAlert cannot use this aggregation function.
Can you tell me, maybe someone has encountered a similar problem, are there other methods that can be used to implement aggregation functions in SIGMA, supported by ElastAlert?
Here is an example of a rule that does not work on ElastAlert, is it possible to convert it using other aggregation functions to use it on the ElastAlert backend?

title: Network Scans 
id: fab0ddf0-b8a9-4d70-91ce-a20547209afb 
description: Detects many failed connection attempts to different ports or hosts 
author: Thomas Patzke 
date: 2017/02/19 
logsource: 
  category: firewall 
detection: 
  selection: 
    action: denied 
  timeframe: 24h 
  condition: 
    - selection | count(dst_port) by src_ip > 10 
    - selection | count(dst_ip) by src_ip > 10 
fields: 
    - src_ip 
    - dst_ip 
    - dst_port 
falsepositives: 
    - Inventarization systems 
    - Vulnerability scans 
    - Penetration testing activity 
level: medium

**Comment by frack113** [comment]
Hello,
With the specification [V2](https://github.com/SigmaHQ/sigma-specification) the rule is `unsupported`.
This issue is more about backend not the rule.
If it is a Elastalert trouble, we can't provide solutions.

**Comment by nasbench** [comment]
Hey @spvcxsh1p 

As stated by frack the rule you're trying to convert is "unsupported" as its using the old syntax. You need to convert it to the new correlation format which you can read about [here](https://github.com/SigmaHQ/sigma-specification/blob/main/specification/sigma-correlation-rules-specification.md). As your issues isn't in the scope of either a supported rule nor a topic of this repo, I will be closing it.

What I suggest is that you try to get your rule into the new format. You can join the sigma [discord](https://discord.gg/kQQBn5W2z5) if you need help doing that.

if the issues persist and you think it's elastalert related, I suggest you open an issue in the appropriate backend repo, which is located [here](https://github.com/SigmaHQ/pySigma-backend-elasticsearch)

Thanks for your understanding.
