### ISSUE TITLE
Integer ranges and inequalities support

### ISSUE THREAD

**Issue by 59e5aaf4** [SigmaHQ/sigma#541]
Here are integer operators we'll need for the FireEye HX OpenIOC-like backend:
- greater than
- less than
- between

# inequalities
I believe we could add [modifiers](https://github.com/Neo23x0/sigma/wiki/Specification#value-modifiers) for the two first without being too creative:
* `field|greater-than: 500`
* `field|less-than: 500`

(`gt` and `lt` would make sense as well, your spec, your choice)

# ranges

How could Sigma include ranges though ? I believe FE uses `fieldName between "100 TO 200"` (`{start:d} TO {end:d}`), but using strings sounds weird.

Does:
* `fieldName|between: "400 TO 500"`

Sound right ?

**Comment by thomaspatzke** [comment]
I would implement this as additional value modifiers.

**Comment by HarishHary** [comment]
Any update on this value modifiers ?

**Comment by thomaspatzke** [comment]
Not yet, sorry.

**Comment by jahshuah** [comment]
Had this idea while updating some Sigma rules the other day and checked to see if someone's mentioned it. Any plans to get it into a current version soon?

**Comment by thomaspatzke** [comment]
It wouldn't go into the 0.x tools anymore, it's already implemented in the rewrite which I plan to release a first preview version soon.

**Comment by jahshuah** [comment]
@thomaspatzke Sounds great! If you're looking for beta testers, I'm happy to throw my hat in the ring.

**Comment by vbr-cts** [comment]
Hi. Just throwing some input into the discussion.
We're using the Sigma spec internally, but not the tooling. Our analysts have expressed the need for arithmetic comparison operators. We've implemented them this way:

```
    field|gte: 5000
```

And for various reasons we have another (non-sigma compliant) syntax where we use objects nested under fields:
```
    field:
      gte: 5000
```

We've implemented the usual operators: gte, gt, lte, lt, eq, neq. They only work on numerical values, and currently don't perform any casting. We are considering having the bitwise operator "AND" (to test if a given flag is set), but this is an open question at this stages.

Use cases for us include things such as:
 - long running connections
 - large data transfers (connection payload, http content-length, etc.)
 - checking against computed risk scores
 - checking against website popularity indicators
 
I've also seen some interesting discussions about implementing len(), for command-line or similar stuff and I definitely love the idea.

**Comment by thomaspatzke** [comment]
It's already implemented in pySigma:

https://github.com/SigmaHQ/pySigma#modifier-compare-from-sigmac
https://github.com/SigmaHQ/pySigma/blob/d8f408e9ea4bf8b8ba4fc6d15bb628c861757d8f/tests/test_conversion_base.py#L258

In quite the same way you described 😊

**Comment by jahshuah** [comment]
@thomaspatzke Should teams be looking to transition to using `pySigma` vs. `sigmac` going forward? Are these features going to be worked into the `sigmac` utility? Just curious what the direction is. Thanks!

**Comment by thomaspatzke** [comment]
You should definitely use pySigma, it is a rewrite of sigmac and has a better structure and test coverage. The final goal is to port backends to pySigma and discontinue the development of sigmac. New features will not be backported, at least by me.

**Comment by jahshuah** [comment]
@thomaspatzke that's good to know. I wasn't able to see at first glance (I'll take a deeper look in a bit), but will `pySigma` be usable via CLI in the same way?

**Comment by thomaspatzke** [comment]
Yes, there will be a CLI, even a better one 😉

The project structure will be a bit different. PySigma is the library part, backends and cli will be separate parts.

**Comment by frack113** [comment]
The cli is  here https://github.com/SigmaHQ/sigma-cli
And the specification are here https://github.com/SigmaHQ/sigma-specification
