### ISSUE TITLE
when the yaml file have condition, with the recursive braces how to handle that?

### ISSUE THREAD

**Issue by PADMAG6** [SigmaHQ/sigma#548]
Hi, 
I'm trying to convert the sigma rules to drools rules.For that i collected the ymal file from your github sigma link. can u help me to find out the soultion.I'm giving my code, error pic and yaml file here. Thanks in advance.(https://github.com/PADMAG6/sigma-_tokens/blob/master/sigma_tokensa.py),https://stackoverflow.com/questions/59158810/how-to-iterate-the-given-while-loop-in-python.

**Comment by Neo23x0** [comment]
Link 404

**Comment by PADMAG6** [comment]
Sorry, Pls follow this https://github.com/PADMAG6/sigma-_tokens

**Comment by PADMAG6** [comment]
Sorry, pls follow this https://github.com/PADMAG6/sigma-_tokens

**Comment by Neo23x0** [comment]
These are two rules, one is of type process_creation and the order one for PowerShell, right? 
So, why do you want to combine them in a single Sigma YML? 

You could do that - see : 
https://github.com/Neo23x0/sigma/blob/master/rules/apt/apt_apt29_tor.yml

**Comment by PADMAG6** [comment]
Sorry  i dn't whether this is powershell or process_creation. I have the requirement like that to convertion of the file (most of the files from sysmon category). Here my condition: (selection1 AND (selection2 AND selection3) OR (selection4 AND selection5)) AND NOT selection6. this is in the recursive braces this formation is not working for me. I provided the python code in the given github link. can u pls check with the code.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
