### ISSUE TITLE
[Feature Request] Multiple output with ElastAlert conversion

### ISSUE THREAD

**Issue by V1D1AN** [SigmaHQ/sigma#552]
# [Feature Request] Multiple output with ElastAlert conversion

### Request Type
Feature Request

### Problem Description
When your want use sigmac for converting rules in elastalert rules.. Can we have 1 file per rule ??

For the moment .. if i do (the option recursive is "On") :

/root/sigma/tools/sigmac --target elastalert-dsl --config /root/sigma/tools/config/winlogbeat.yml -r -I --output /root/rules/rule.yml /root/sigma/rules/

I have 1 file with all rules inside, but ElastAlert don't load all rules... Only the first.

Can you integrate the possibility to having the output multiple files with the option recursive??
Example:

/root/sigma/rules/win_GPO_scheduledtasks.yml
/root/sigma/rules/win_account_backdoor_dcsync_rights.yml
...

Thanks for you works :)

**Comment by SMAPPER** [comment]
While not part of sigmac itself, maybe something like this would work:

# Convert rules to single output file
/path/to/sigma/tools/sigmac --config winlogbeat --target elastalert --recurse /path/to/sigma/rules/windows/ --ignore-backend-errors --output sigma_single_file_output

# Convert output file into multiple files using csplit
csplit --prefix sigma_ --suffix-format "%04d.yaml" sigma_single_file_output "/^alert:/" "{*}"
# Delete the original output file
rm sigma_single_file_output
# Delete the first file as it will always be empty - This does it dynamically by finding empty files in the current directory
find . -size  0 -print -delete

Does that help?
