### ISSUE TITLE
ATT&CK id / tag in Elastalert 

### ISSUE THREAD

**Issue by iukea1** [SigmaHQ/sigma#564]
Hello,
Love the sigma project!

But I have a quick question.

Is there a way to add the ATT&CK id/tags into an alert made by elastalert?

Example: these tags are in a couple of sigma rules and I was hoping if this sigma rules are hit that these tag IDs are printed into the  elastalert log.

tags:

- attack.execution

- attack.t1086

Thanks again for all your hard work! 

From a noob

**Comment by V1D1AN** [comment]
Hello

You can change the file elasticsearch.py in the folder of backend.

```
    962             rule_object = {
    963                 "name": title + "_" + rulename,
    964                 "description": description,
    965                 "index": index,
    966                 "priority": self.convertLevel(level),
    967                 "realert": self.generateTimeframe(self.realert_time),
    968                 "mitre": rule_tag,
    969                 "author": author,

```


I have add "mitre": rule_tag,

then i have this:


 ./sigmac -t elastalert -c config/generic/sysmon.yml -c /root/nxlog.yml /root/sigma/rules/windows/process_creation/win_susp_whoami.yml

alert:
- debug
author: Florian Roth
description: Detects the execution of whoami, which is often used by attackers after exloitation / privilege escalation but rarely used by administrators
filter:
- query:
    query_string:
      query: ((EventID:"1" AND Channel:"Microsoft\-Windows\-Sysmon\/Operational") AND (Image:*\\whoami.exe OR OriginalFileName:"whoami.exe"))
index: nxlog-*
mitre:
- attack.discovery
- attack.t1033
- car.2016-03-001
name: Whoami Execution_e28a5a99-da44-436d-b7a0-2afc20a5f413
priority: 2
realert:
  minutes: 0
type: any

**Comment by anust** [comment]
@iukea1 have you managed to do it? I need help in the same issue. 
@V1D1AN this is for rules generation, we need mitre tags in alerts so that mapping is done easily.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
