### ISSUE TITLE
Develop Sigma rules for PowerShell Abuse

### ISSUE THREAD

**Issue by yugoslavskiy** [SigmaHQ/sigma#575]
- Research (slides): [Hunting For PowerShell Abuse](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse)
- Author: Teymur Kheirkhabarov, [@HeirhabarovT](https://twitter.com/HeirhabarovT)
- Type: Ready-made alerts (Kibana queries)
- Requirements: Create one Pull Request per Sigma rule

You can pick up some of the listed Kibana queries from the slides and develop Sigma rules out of them:

| Page                                                                          | Sigma Rule | Topic                                                |
|:-----------------------------------------------------------------------------:|:----------:|------------------------------------------------------|
|[28](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=28)| None       | Suspicious PowerShell parent process                 |
|[31](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=31)| None       | PowerShell Scripts Installed as Services             |
|[34](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=34)| None       | Renamed PowerShell                                   |
|[37](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=37)| None       | Base64-encoded commands. –EncodedCommand             |
|[42](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=42)| None       | FromBase64String / Compression / X509Enrollment      |
|[43](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=43)| None       | FromBase64String + Compression                       |
|[46](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=46)| None       | Xor-ed commands                                      |
|[48](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=48)| None       | Execution of PS code / .NET assembly from registry   |
|[50](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=50)| None       | Execution of PS code / .NET assembly from file       |
|[56](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=56)| None       | PowerShell Download Cradles                          |
|[57](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=57)| None       | PowerShell Download Cradles. COM objects CLSID       |
|[59](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=59)| None       | PowerShell Download Cradles. BITS                    |
|[60](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=60)| None       | PowerShell Download Cradles. BITS.                   |
|[64](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=64)| None       | PowerShell command line obfuscation                  |
|[65](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=65)| None       | PowerShell command line obfuscation                  |
|[66](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=66)| None       | PowerShell command line obfuscation                  |
|[67](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=67)| None       | Too long PowerShell command lines                    |
|[69](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=69)| None       | Accessing WinAPI in PowerShell                       |
|[70](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=70)| None       | Accessing WinAPI in PowerShell. Code injection       |
|[71](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=71)| None       | Accessing WinAPI in PowerShell. Credentials dumping  |
|[75](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=75)| None       | PowerShell without PowerShell.exe                    |

**Comment by HarishHary** [comment]
Started to work on this. Pull requests coming soon ! :D

**Comment by HarishHary** [comment]
Sorry for the delay here are few PR going on:
Renamed PowerShell: https://github.com/Neo23x0/sigma/pull/866
Suspicious PowerShell parent process: https://github.com/Neo23x0/sigma/pull/867

**Comment by NikitaStormwind** [comment]
28, 31, 37, 67, 69, 70, 71, 75

**Comment by vburov** [comment]
Start working on issues:
64 | None | PowerShell command line obfuscation
65 | None | PowerShell command line obfuscation
66 | None | PowerShell command line obfuscation

**Comment by vburov** [comment]
https://github.com/Neo23x0/sigma/pull/1125

**Comment by vburov** [comment]
Start working on issues:
64 | None | PowerShell command line obfuscation
65 | None | PowerShell command line obfuscation
66 | None | PowerShell command line obfuscation

**Comment by frack113** [comment]
Make some update to check wtah need to be check before close this issue

| Page                                                                          | Sigma Rule | Topic                                                |
|:-----------------------------------------------------------------------------:|:----------:|------------------------------------------------------|
|[42](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=42)| None       | FromBase64String / Compression / X509Enrollment      |
|[43](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=43)| None       | FromBase64String + Compression                       |
|[48](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=48)| None       | Execution of PS code / .NET assembly from registry   |
|[50](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=50)| None       | Execution of PS code / .NET assembly from file       |
|[56](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=56)| None       | PowerShell Download Cradles                          |
|[57](https://speakerdeck.com/heirhabarov/hunting-for-powershell-abuse?slide=57)| None       | PowerShell Download Cradles. COM objects CLSID       |
