### ISSUE TITLE
Develop Sigma rules for Lateral Movement in Windows Infrastructure

### ISSUE THREAD

**Issue by yugoslavskiy** [SigmaHQ/sigma#576]
- Research (slides): [Hunting Lateral Movement in Windows Infrastructure](https://drive.google.com/file/d/1lKya3_mLnR3UQuCoiYruO3qgu052_iS_/view?usp=sharing)
- Author: Teymur Kheirkhabarov, [@HeirhabarovT](https://twitter.com/HeirhabarovT)
- Type: Ready-made alerts (Splunk queries)
- Requirements: Create one Pull Request per Sigma rule

You can pick up some of the listed Splunk queries from the slides and develop Sigma rules out of them or improve existing ones:

| Page  | Sigma Rule ID/Link                                                                                                                                      | Topic                        |
|:-----:|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|------------------------------|
|  7    | [098d7118-55bc-4912-a836-dc6483a8d150](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_admin_share_access.yml) (partially) | administrative shares access |
|  8    | None                                                                                                                                                    | usage of standard tools for copying to administrative shares |
|  9    | None                                                                                                                                                    | usage of net tool for mounting remote admin share |
|  11   | None                                                                                                                                                    | files creation/changes in autostart locations |
|  12   | None                                                                                                                                                    | search for execution from remote shares |
|  15   | None                                                                                                                                                    | wmic/powershell that executes something on the remote host |
|  27   | [5a105d34-05fc-401e-8553-272b45c1522d](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_mal_service_installs.yml), [42c575ea-e41e-41f1-b248-8093c3e82a28](https://github.com/Neo23x0/sigma/blob/master//rules/windows/other/win_tool_psexec.yml) | search for PsExec (& clones) artifacts – services |
|  29   | [c462f537-a1e3-41a6-b5fc-b2c2cef9bf82](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_psexec.yml) (partially)              | search for PsExec (& clones) artifacts – access to pipes |
|  30   | None                                                                                                                                                    | search for PsExec (& clones) artifacts – pipes creation |
|  47   | [f1f3bf22-deb2-418d-8cce-e1a45e46a5bd](https://github.com/Neo23x0/sigma/blob/32ecb816307e3639cf815851fac8341a60631f45/rules/windows/builtin/win_mmc20_lateral_movement.yml) (partially)                                                                                                                                                    | executions in network logon sessions (WinRM, WMI, PsExec/PaExec, Powershell Remoting, MMC20/Visio/Excel/Outlook COM...) |
|  54   | None                                                                                                                                                    | remotely created or updated scheduler tasks |
|  56   | [f6de6525-4509-495a-8a82-1f8b0ed73a00](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_atsvc_task.yml)                           | ATSVC pipe connections |
|  60   | None                                                                                                                                                    | remotely created services |
|  64   | [68fcba0d-73a5-475e-a915-e8b4c576827e](https://github.com/Neo23x0/sigma/blob/oscd/rules/windows/builtin/win_remote_registry_management_using_reg_utility.yml) | WINREG pipe connections |
|  67   | [24357373-078f-44ed-9ac4-6d334a668a11](https://github.com/Neo23x0/sigma/blob/oscd/rules/windows/process_creation/win_susp_direct_asep_reg_keys_modification.yml) (partially), [17f878b8-9968-4578-b814-c4217fc5768c](https://github.com/Neo23x0/sigma/blob/oscd/rules/windows/sysmon/sysmon_asep_reg_keys_modification.yml) (partially) | changes in autostart registry keys |
|  71   | [0b7889b4-5577-4521-a60a-3376ee7f9f7b](https://github.com/Neo23x0/sigma/blob/master/rules/windows/other/win_wmi_persistence.yml) (different method)     | WMI Filters\Consumers creation |
|  77   | None                                                                                                                                                    | logon with explicit credentials |
|  81   | [cbe51394-cd93-4473-b555-edf0144952d9](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_dns_config.yml)                      | Remote execution via DNS server level plugin |

**Comment by Sigreil** [comment]
29, 30

**Comment by svch0stz** [comment]
8, 9, 77

**Comment by james0d0a** [comment]
11, 12, 15

**Comment by JPMinty** [comment]
54, 60

**Comment by GlebSukhodolskiy** [comment]
67,71

**Comment by Karneades** [comment]
47:  https://github.com/SigmaHQ/sigma/pull/1493
* https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_access/win_susp_shell_spawn_from_winrm.yml

**Comment by frack113** [comment]
All cover
