### ISSUE TITLE
Default fields per log source

### ISSUE THREAD

**Issue by thomaspatzke** [SigmaHQ/sigma#591]
Define fields that should be defined per log source and/or event attribute in the configuration of the converter.

**Comment by maninthewall** [comment]
Could this optionally include regex to extract that field from the log source or is that too specific?  It seems for backends like Sumologic (and maybe Splunk?) if we could define the regex needed to extract that field's data from the logsource, it would go a long way to improve effectiveness of rules.  

In Sumologic's case, the backend could generate the `parse` commands to extract the field, or optionally FER (Field Extraction Rules) that admins could set.

@juju4 what do you think?

**Comment by sp4ce-hUtch** [comment]
Any thoughts on using a generic vendor-agnostic schema, like the OSSEM CIM, for Sigma fields? This would allow all rules to be written using common generic fields, and then converter files could be mostly monolithic per backend schema. I.e., if you know all of the possible Sigma fields, as per a schema like OSSEM CIM, then you could write a single converter config file for mapping to your given backend(s) schema, such as Elastic Common Schema (ECS), which would support multiple Elasticsearch/ElastAlert-related backends.

**Comment by thomaspatzke** [comment]
@maninthewall this issue is only about that a logsource (e.g. process_creation) is mapped to a static set of fields that is useful to be displayed in the results (in the previous example: command line and parent command/image). This would replace the explicit enumeration of the same fields in all rules of a particular type that is currently required. Your suggestion targets some kind of enrichment. This could be incorporated as comment in rules ([was already done in various rules](https://github.com/Neo23x0/sigma/search?q=enrichment&unscoped_q=enrichment)) where required.

**Comment by thomaspatzke** [comment]
@sp4ce-hUtch yes, we already had this discussion several times. The first big question that lacks an answer is: which schema should be used? There are various more or schemas out there and all have advantages and disadvantages.

> This would allow all rules to be written using common generic fields, and then converter files could be mostly monolithic per backend schema. I.e., if you know all of the possible Sigma fields, as per a schema like OSSEM CIM, then you could write a single converter config file for mapping to your given backend(s) schema, such as Elastic Common Schema (ECS), which would support multiple Elasticsearch/ElastAlert-related backends.

This is already the case. Where possible, we have a single mapping per backend. The problem is, that backends change their naming schemas causing that multiple mappings are required. This wouldn't be solved by moving to a different schema.

Usage of the original naming schemas (like for Windows, which are the most Sigma rules) gives the advantage that the field names can be mapped 1:1 to the real events without the requirement of a mapping in most backends.

**Comment by sp4ce-hUtch** [comment]
Understood, and it does make sense/seems valuable to use original naming schemas of log sources in order that "field names can be mapped 1:1 to the real events." Essentially, then, is it expected to have a converter config per log source per backend (I know ECS applies to multiple Elasticsearch-related backends), e.g. ecs-proxy.yml (exists), and notionally ecs-zeek.yml, ecs-windows.yml, ecs-linux.yml, ecs-network.yml, where the Sigma fields in ecs-zeek.yml, for example, would be populated with names of fields native to logging in Zeek, like id.orig_h?

> This is already the case. Where possible, we have a single mapping per backend. The problem is, that backends change their naming schemas causing that multiple mappings are required. This wouldn't be solved by moving to a different schema.

I think this is a different issue. I am talking about the naming schema of log source fields, aka Sigma field names, not the naming schemas of backends, aka target field names. You and Sigma project maintainers control the former but don't have any control over the latter, which is the responsibility of SIEM vendors and/or an org's SIEM admins.

**Comment by sp4ce-hUtch** [comment]
Thinking about it further, admittedly it makes sense to use native log source field names for the Sigma field names in rules and converter configs when a _product_ and/or _service_ is defined as the log source, but what about generic log sources, where there is only a _category_ scope, such as category: dns or, notionally, category: network or category: flow or category: http? It seems like a generic vendor-agnostic schema, such as the OSSEM CIM, would be beneficial in those cases, similar to how someone, for whatever reason, chose to use the W3C Extended Log File Format for Sigma field names regarding category: proxy and category: webserver. I'm not saying that the OSSEM CIM is necessarily the best option, as I've done no real comparison with other schemas, though it does seem fairly well considered.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
