### ISSUE TITLE
[Backend Dev] Working on adding Elastic Detection Engine

### ISSUE THREAD

**Issue by ipninichuck** [SigmaHQ/sigma#629]
Hello,

   I wanted to connect with others who have aspirations of adding support for the new Detection Engine released in Elastic 7.6. I started working on adding it the Elasticsearch backend. Currently it supports Kibana Query Language and a variety of options. The code can be found in my fork of Sigma. I am not making a PR just yet as some key features are not ready. I will list those below. I have discussed the detection engine with Elastic devs and so I have a good road map of where they are headed and have a good source for any other questions.

--Att&ck tags need to be transformed to ECS Threat Objects(I am thinking of doing this on ingest rather than in the backend...just an idea).

--EQL will be the primary language used but Elastic has not released support in this version

--Actions need to be added but again Elastic has not added them in this release.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
