### ISSUE TITLE
Carbon Black query woes

### ISSUE THREAD

**Issue by pyllyukko** [SigmaHQ/sigma#660]
I have several issues with the Carbon Black backend and Sigma seems to produce broken queries.

This is tested with Cb Response 6.X.

Removed backslashes
-------------------

[This part](https://github.com/Neo23x0/sigma/blob/cbf0f4393412c51e00b07430e16daddd310d7b32/tools/sigma/backends/carbonblack.py#L75-L80) of carbonblack.py back translates the following rule:

```
    filter:
        CommandLine|contains: '\\'
    condition: selection and not filter
```

Into the following query:

```
AND ( -(cmdline:**))
```

So it effectively removes the backslashes completely.

Grouping of conditions
----------------------

The following rule:

```
detection:
    selection:
        Image|endswith: 
            - 'net.exe'
            - 'net1.exe'
        CommandLine|contains: 'view'
```

Produces the following query (part):

```
(process_name:*net.exe OR process_name:*net1.exe AND cmdline:*view*)
```

This produces zero results and the following query works:

```
((process_name:*net.exe OR process_name:*net1.exe) AND cmdline:*view*)
```

Invalid filter condition
------------------------

The following rule:

```
    filter:
        CommandLine|contains: 'xyz'
    condition: selection and not filter
```

Produces the following:

```
AND ( -(cmdline:*xyz*))
```

CbR produces zero results with this and it seems like it should be:

```
AND -(cmdline:*xyz*)
```

**Comment by neu5ron** [comment]
Thomas,
the CB backend is basically same as elasticsearch correct? wondering if it just needs updated some

**Comment by thomaspatzke** [comment]
I don't know. Just looked into the code and it isn't derived from one of the Elastic classes but the code seems quite similar.

**Comment by thomaspatzke** [comment]
@socprime can you look at this?

**Comment by thomaspatzke** [comment]
Just merged #831 which should fix the grouping part. @pyllyukko can you verify?

**Comment by pyllyukko** [comment]
Grouping looks good now.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
