### ISSUE TITLE
Backend es-dsl: conversion of keyword rules with wildcards

### ISSUE THREAD

**Issue by thomaspatzke** [SigmaHQ/sigma#705]
Conversion of rules with keyword expressions (matches on all fields) cause a wrong result that wouldn't match anything in the es-dsl backend:

```
tools/sigmac -t es-dsl -c helk rules/linux/lnx_susp_named.yml
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "should": [
            {
              "multi_match": {
                "query": "* dropping source port zero packet from *",
                "fields": [],
                "type": "phrase"
              }
            },
            {
              "multi_match": {
                "query": "* denied AXFR from *",
                "fields": [],
                "type": "phrase"
              }
            },
            {
              "multi_match": {
                "query": "* exiting (due to fatal error)*",
                "fields": [],
                "type": "phrase"
              }
            }
          ]
        }
      }
    }
  }
}
```

A query similar to the queries generated by the es-qs backend should be generated by the es-dsl backend:
```
\*.keyword:(*\ dropping\ source\ port\ zero\ packet\ from\ * OR *\ denied\ AXFR\ from\ * OR *\ exiting\ \(due\ to\ fatal\ error\)*)
```

It should do a wildcard matching on all keyword fields.

**Comment by neu5ron** [comment]
I have been thinking about this one too, for rules that have the `keywords` field, there is no ability in sigmac to map `keywords` to a field.
some backends have a field that contains the original log as is, it would be beneficial to map `keywords` to this field (or similar fields) like `message` for others.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
