### ISSUE TITLE
How logs are taken?

### ISSUE THREAD

**Issue by fabiob10scr** [SigmaHQ/sigma#760]
We would like to integrate the rules for our custom siem. Is there a list of requirements for how and what logs are taken? I noticed there are syslogs, history files, and more, but I haven't found an exhaustive list. Thanks so much

**Comment by Karneades** [comment]
I'm not a ware of a prepared list to answer your question in full. Others can jump in :)

You could look at the wiki (difficult to find): https://github.com/Neo23x0/sigma/wiki/Taxonomy#specific

The available public Sigma rules can be applied against different logs: Rules cover different OS logs for *nix servers (e.g. auth, auditd,...) , for Windows there are Sysmon, PowerShell or Window Events rules which are common, for web proxy logs, ... it's up to you, what you try to detect ;)

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
