### ISSUE TITLE
[QRadar] Custom field without single quotes

### ISSUE THREAD

**Issue by mdurancarreras** [SigmaHQ/sigma#787]
Hi everyone!

I have done a fieldmapping with some custom fields.

The result I always get is "... **'**dst_port**'**, **'**src_port**'** ...", for example.

Is there a way to remove the single quotes or change them to double quotes?

Thanks!

**Comment by k3mpaxl** [comment]
@mdurancarreras I've updated the converter for qradar and this issue is fixed now.

@Neo23x0 : maybe this issue could be closed?
