### ISSUE TITLE
sysmon_lsass_memdump.yml comment and question

### ISSUE THREAD

**Issue by johnwunder** [SigmaHQ/sigma#804]
I have a comment and question in regards to [sysmon_lsass_memdump.yml](https://github.com/Neo23x0/sigma/blob/82cae6d63c9c2f6d3e86c57e11497d86279b9f95/rules/windows/sysmon/sysmon_lsass_memdump.yml) contributed by @sbousseaden. First of all, great work and great analytic!

The comment: two very common false positives are WerFault.exe and tasklist.exe. I can make a PR for this if you want...but first wanted to ask the question.

The question: I noticed that the blog post doesn't mentioned the GrantedAccess filter in the analytic posted here. In our testing we didn't notice it filtering out any FPs beyond WerFault.exe (which had many more instances of the 0x1FFFFFF pattern, so it didn't help much)...but maybe in other environments it does? Just wasn't sure what the purpose of it was given our testing.

**Comment by sbousseaden** [comment]
Thanks John for your feedback! the sigma logic is based only on two tools prodump and taskgmr.
The GrantedAccess condition can be relaxed if according to your dataset you don't see dbhelp or dbcore (likely call to [Minidumpwritedump](https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump) to dump lsass memory) in the calltrace only for werfault.exe (likely lsass.exe crashed which is rare) and tasklist.exe (haven't encountred this case if possible to share CallTrace details).

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
