### ISSUE TITLE
Skip rules if mapping isn't set

### ISSUE THREAD

**Issue by stevengoossensB** [SigmaHQ/sigma#805]
Hi,

Is there a way to skip the conversion of the Sigma rule, in case the mapping isn't set to a target field for the product? I don't think it should be the standard behaviour, but for products with a limited syntax, it would be handy if I could pass a flag which skips the rule if the fieldname cannot be resolved, rather then creating a translation with the default name.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
