### ISSUE TITLE
What is the correct way to group rules?

### ISSUE THREAD

**Issue by gonvald** [SigmaHQ/sigma#820]
I have a question about gruoping rules.

I want to have different rules to detect the same event with different frecuencies and different severity levels. 

**I would like to know if there is a way to create a rule that is triggered when another one has been triggered a certain amuont of times**. I think it's not possible to do this using the "action" attribute, but I'd like to make sure.

Also, **what is the correct way to validate if a rule is written properly**?

Thank you so much.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
