### ISSUE TITLE
Output queries that use Splunk's Data Models and Data Model Acceleration

### ISSUE THREAD

**Issue by cygnetix** [SigmaHQ/sigma#83]
Hi,

I saw Florian's twitter post this week and thought I'd raise a ticket to discuss how using Splunk's data models could work: https://twitter.com/cyb3rops/status/992315782582427648?s=12

After giving it some thought, I'm now thinking it's best to update the existing backend but to have it produce SPL that leverages Splunk's data models and data model acceleration when it can. Something like the following:

1. Check that the config file associates a logsource with a data model.
2. If all the provided fields exist within the data model, then produce a query that uses the `tstats` command.
3. If not all the fields exist within the datamodel, then fallback to producing a query that uses the `from` command.
4. If the logsource isn't associated with a data model, then just output a regular `search`.

Doing the above would mean there'd need to be some way to associate a logsource to a data model within the config. A data model consists of a json schema that sigma could read in to see if the fields listed exist. The Common Information Model (CIM) is the one everyone should be using, but it's possible that some may have extended it or need to use custom data models, so it'd be good to make sigma account for this: https://splunkbase.splunk.com/app/1621/ (json is under default\data\models\ within the .tar.gz).

Some examples of what this might look like:
1. rules\proxy\proxy_powershell_ua.yml could be associated with the Web.Proxy data model and only uses fields within the data model, so it should produce:
`| tstats count from datamodel=Web where nodename=Web.Proxy (Web.http_user_agent="* WindowsPowerShell/*") by host`
2. rules\windows\sysmon\sysmon_webshell_detection should be associated with the Application_State.Processes data model but not all fields from the sigma query are contained within this datamodel (EventID), so it should produce:
`| from datamodel:Application_State.Processes
| search (EventID="1" (parent_process="*\\apache*" OR parent_process="*\\tomcat*" OR parent_process="*\\w3wp.exe" OR parent_process="*\\php-cgi.exe" OR parent_process="*\\nginx.exe" OR parent_process="*\\httpd.exe") (cmdline="whoami" OR cmdline="net user" OR cmdline="ping -n" OR cmdline="systeminfo"))`
3. The final outcome is where the logsource hasn't been associated to a data model, which produces the same SPL that the current splunk backend does.

I started having a little bit of a tinker but haven't gone as far as implementing the above suggestion. Let me know what you think first.

**Comment by cubedwombat** [comment]
nice work! 
However I do think adjustments could be made due to the creation of data models in splunk is pretty easy. Not sure about the pure acceleration of it but...


Re 3 "If not all the fields exist within the datamodel, then fallback to producing a query that uses the from command.
4 If the logsource isn't associated with a data model, then just output a regular search."
IMHO, disagree a bit. The data model should be cloned and recreated to accept the new fields. For new/no prebuilt data model w/com compliant fields: just build a data model (really should be called super search for the passers by). As it is custom, just add it as a note or dependency. Then redo the data model when those fields catches up to be CIM compliant.

EG: the latest awesomeness in sysmon means new fields with valuable data in them. New data means new rules/opportunities. This also won't happen often. Clone the (aw crap, you will have to create one for your sysmon anyway) sysmon datamodel and account for the new fields.

**Comment by cygnetix** [comment]
Thanks for taking the time to have a read though. I can definitely see this turning out to be tricky and it's worth discussing before settling on a solution.

I'm failing to see how my suggestion prevents anyone from creating or extending an existing data model? I believe the same rules should be apply, you just need to provide sigma's config with your custom data model (.json) so it can follow the logic / steps I've listed to see which command should be used based on whether you've associated a logsource with a data model and what fields are available in the yaml ("tstats" will only work if all fields exist. "from" uses _raw logs and all fields are available for searching). The idea to have sigma figure out which search command is best is just from a usability perspective. Possibly some of the values can be overridden manually with options (-O) but I'd like to be able to have SPL be produced to that even those that don't understand how to write "tstats" and "from" queries can benefit.

Not sure if this might describe the issue you've identified better but I am unsure of how to deal with the fact that there's not a 1-to-1 mapping between a logsource and a data model. For example, proxy will probably map well to the CIM's Web data model.. until you want to search your proxy logs for certificate hashes, then it needs to use the Certificates data model. The fact that the examples I've given use data models from the CIM, I don't believe, is relevant. If you've created your own data model for searching certificate hashes in sysmon then the same rules should apply... but, "should" is the key word here. I expect if there is a problem then I just haven't understood your comment above (it may still come to me).

If the sysmon data model is available to take a look at, possibly your concerns may become clear to me. It would certainly help to validate the attestation I'm making above about this method working for custom data models equally well? Or if you're able to provide a specific example of where the logic I've listed breaks down, as I'm sure there will be cases, as I've described?

The good news is, most of rules that I've looked over in this repo are pretty straight forward. The tinkering I was referring to above was just me creating a new splunk_dm backend (not what I'm proposing going forward) and hard coding the output to produce a tstats query. This seemed to work fine against the rules under rules/proxy (I think I also played with DNS) but certainly some more thought may be required: https://github.com/Neo23x0/sigma/compare/master...cygnetix:splunk_dm

Apologies if I've managed to overlook the concern you were trying to raise.

PS: Aggregations should also be considered. I'd suggest tstats use these when provided and just default to "groupby host" when not.

**Comment by cubedwombat** [comment]
I didn't explain myself fully. Sorry about that.

I am saying that I think you are on the right course. 

Mapping to CIM compliance where ever you can, where there is already a datamodel is great. 

I am saying that, in instances where there is no standard splunk sanctioned CIM data model, you COULD use a custom data model that folks could also deploy in their own environment.  Then just list it as a dependency. 

Rather than the output be the spl search. Just a suggestion.

There isn't an official datamodel for sysmon (that I know of) but this https://github.com/splunk/TA-microsoft-sysmon/blob/master/README.md might be close. Especially because it seems to have been designed with sigma in mind. 

Besides, while the end result of Sigma will get someone going, the data models might have to be tuned for every ones specific environment anyway. Just like any rule or signature. So there being an external dependency like a datamodel, is not a big deal IMHO.

**Comment by d1vious** [comment]
Good news @cubedwombat @cygnetix there is now a sysmon "sanctioned" data model in Splunk called  Endpoint. https://docs.splunk.com/Documentation/CIM/4.12.0/User/Endpoint
 It was specifically built and tested by my team with sysmon data. 

With that said I love the approach you suggested at first @cubedwombat with how to treat DM queries, and also see the challenge in mapping log source to actual datamodels. I had some quick ideas that came to mind like creating a "hard coded" map of datasource to a corresponding out of the box datamodel. example:

sysmon -> endpoint
carbon black -> endpoint
osquery -> endpoint
nginx -> proxy, web
apache -> proxy,web
etc..

I wasn't sure where it would be a good place to write this, was going to make a attempt at `splunk_dm` as you suggested @cygnetix and hard code the above mapping into the backend for now. There is not a whole lot of variations in the services, should be pretty feasible: 
https://twitter.com/d1vious/status/1088146177512607746

**Comment by bluexti** [comment]
Hi all,

Any update regarding splunk CIM backend ?
Maybe i can help ?

**Comment by mf1d3l** [comment]
I started an implementation of my own based on what has been initially suggested by @cygnetix and @cubedwombat . I'm  [hardcoding](https://github.com/mf1d3l/sigma/blob/splunkdm_backend/tools/sigma/backends/cim.py) the sigma logsource to datamodel/dataset mapping and normalization field mapping but also allow users to ingest their own datamodels specification as yaml file via the backend options. Backend both retrieves for a  logsource  a pair of datamodel/dataset and provides field normalization. If no datamodel/dataset or field normalization is found or any error occurs like non supported aggregation operator, backend rolls back to standard splunk query.

User has also the option to ignore normalization errors and to try to force the usage of a datamodel/dataset via backend options. 

### Example:

**command**
```
./tools/sigmac -c splunk-windows -t splunkdm rules/windows/process_creation/win_office_shell.yml
```

**output**
```
| tstats count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where ((Processes.parent_process_path="*\\WINWORD.EXE" OR Processes.parent_process_path="*\\EXCEL.EXE" OR Processes.parent_process_path="*\\POWERPNT.exe" OR Processes.parent_process_path="*\\MSPUB.exe" OR Processes.parent_process_path="*\\VISIO.exe" OR Processes.parent_process_path="*\\OUTLOOK.EXE") (Processes.process_path="*\\cmd.exe" OR Processes.process_path="*\\powershell.exe" OR Processes.process_path="*\\wscript.exe" OR Processes.process_path="*\\cscript.exe" OR Processes.process_path="*\\sh.exe" OR Processes.process_path="*\\bash.exe" OR Processes.process_path="*\\scrcons.exe" OR Processes.process_path="*\\schtasks.exe" OR Processes.process_path="*\\regsvr32.exe" OR Processes.process_path="*\\hh.exe" OR Processes.process_path="*\\wmic.exe" OR Processes.process_path="*\\mshta.exe" OR Processes.process_path="*\\rundll32.exe" OR Processes.process_path="*\\msiexec.exe" OR Processes.process_path="*\\forfiles.exe" OR Processes.process_path="*\\scriptrunner.exe" OR Processes.process_path="*\\mftrace.exe" OR Processes.process_path="*\\AppVLP.exe" OR Processes.process_path="*\\svchost.exe")) by Processes.process Processes.parent_process
```
