### ISSUE TITLE
round brackets issue

### ISSUE THREAD

**Issue by crimsoncore** [SigmaHQ/sigma#835]
Hi there,
 Running full elk stack 7.6.2, winlogbeat 7.6.2, sigma installed with python3 -m pip install sigmatools==0.16.0}

I'm running into a strange issue.

sigmac -Okeyword_blacklist=* -t es-qs -c /opt/sigma/tools/config/winlogbeat-modules-enabled.yml /opt/threathunt/sigma_rules/win_crimsoncore_net.yaml

the yaml file has a very simple detection:

logsource:
    product: windows
    service: sysmon
detection:
    selection:
        EventID: 1
        ProcessName:
            - '*net.exe'
            - '*net1.exe'
    condition: selection

when I run the above sigma onelines - I get the following query output

(winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND winlog.event_id:"1" AND process.executable:("*net.exe" OR "*net1.exe"))

running this won't yield any results in kibana, unless i remove the () at the end, around the OR statement - so if I use this query it works fine:

(winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND winlog.event_id:"1" AND process.executable:"*net.exe" OR "*net1.exe")

Is this an elastic (version 7.x issue) or just sonething with sigma?

Many Thanks,
Luk

**Comment by crimsoncore** [comment]
to clarify in Kibana KQL

this works : 
process.executable: (*net.exe OR *net1.exe)
process.executable: "*net.exe" OR "*net1.exe"

but this doesn't work (output from sigma):
process.executable: ("*net.exe" OR "*net1.exe")

**Comment by crimsoncore** [comment]
weird, when I skip the -Okeword_blacklist - the output is this, which is without the ()

sigmac -t es-qs -c /opt/sigma/tools/config/winlogbeat.yml /opt/threathunt/sigma_rules/win_crimsoncore_net.yaml

(winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND winlog.event_id:"1" AND winlog.event_data.ProcessName.keyword:(*net.exe OR *net1.exe))

**Comment by crimsoncore** [comment]
Hey guys, did anyone have some time to look into this - maybe my example wasn't clear? Here's another one.

Running ELK stack 7.8, but this seems to be the same on any 7.x

------

root@kali:/opt/threathunt/sigma_rules# sigmac -Okeyword_blacklist=* -t es-qs -c /opt/sigma/tools/config/winlogbeat-modules-enabled.yml /opt/threathunt/sigma_rules/win_crimsoncore_officespawn.yaml

Resulting Kibana Query:
(process.parent.executable:("*\\EXCEL.EXE") AND process.executable:("*\\cmd.exe"))

Problem: This removes the .keyword but it adds "" which yield in no results when you run this query. Manually removing the quotation marks around cmd.exe and excel.exe fixes this. Seem weird that when using the keyword_blacklist this is added.

-----

root@kali:/opt/threathunt/sigma_rules# sigmac -t es-qs -c /opt/sigma/tools/config/winlogbeat-modules-enabled.yml /opt/threathunt/sigma_rules/win_crimsoncore_officespawn.yaml

Resulting Kibana Query:
(process.parent.executable.keyword:(*\\EXCEL.EXE) AND process.executable.keyword:(*\\cmd.exe))

Problem: Here the "" aren't added by you need to manually remove the .keyword from the search.

-----

Hope this helps.

**Comment by thomaspatzke** [comment]
Appears to be a bug. The quotes shouldn't be and the keyword field should be used to match the whole value.

**Comment by neu5ron** [comment]
@crimsoncore  can you try with only the CLI option `--backend-option keyword_field=""`

the option previously specified in your config was actually setting nothing as a keyword and was thus treating as an analyzed field.

this guide we created may help:

https://github.com/Neo23x0/sigma/blob/master/tools/README.md#choosing-the-right-sigmac

https://github.com/Neo23x0/sigma/blob/master/tools/README.md#elastic---some-final-examples

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
