### ISSUE TITLE
[Question] Negate operator support

### ISSUE THREAD

**Issue by emretinaztepe** [SigmaHQ/sigma#856]
Is there any plan to add negate support for transformations such as !contains, !startsWith, and so on. Negating in condition string using "not filters" decreases the readability of the rule in my opinion and it would be great to make it possible to negate the modifier such as:
selection:
  ProcessName|!endswith: a.exe
or
selection:
  ProcessName|not endswith: a.exe

**Comment by Karneades** [comment]
You can use the not condition in the rule. Would that help?

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
