### ISSUE TITLE
[QRadar] QRadar configuration field mapping question

### ISSUE THREAD

**Issue by barvhaim** [SigmaHQ/sigma#858]
I Noticed that many of the fields in fieldmapping of QRadar has the prefix `event_data.`, however only few of them have the same field name without this prefix for example: `event_data.Imphash: IMP Hash` and `Imphash: IMPHash`, thus, fields as `ImageLoaded` won't be mapped even though `event_data.ImageLoaded` does exists and therefore the AQL query will failed as `ImageLoaded` stays AS-IS and not mapped to LoadedImage. is there any magic behind putting dots `.` in field name I am missing?  

For windows I can see several major fields that will prevent from my AQL to run as those fields are not mapped and do appear in Sigma rules, for example `ImageLoaded` appear in 16 windows rules, `DestinationPort` and `DestinationIP` appear in 11 windows rules.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
