### ISSUE TITLE
Handle modifiers in custom backend.

### ISSUE THREAD

**Issue by svnscha** [SigmaHQ/sigma#870]
I am in the process of implementing a custom backend for Sigma. I am trying to handle modifiers such as `endswith` and `startswith`. I am inheriting from `SingleTextQueryBackend` but the method `generateTypedValueNode` is not called for rules that use the `endswith` and `startswith` modifier. I am just seeing it called for regular expressions.

While analyizing this I have noticed that `SigmaEndswithModifier:apply_str` is indeed called during parsing the search. It then returns a string and that might be the reason why `generateTypedValueNode` is not called for this.

Am I missing something in the general usage of this? 

I've been looking to the `ala.py` backend as reference. This backend checks explicitly for 

```
elif type(value) in [SigmaTypeModifier, SigmaContainsModifier, SigmaRegularExpressionModifier, SigmaStartswithModifier, SigmaEndswithModifier]:
```

but it seems that it never goes into this block.

What is the preferred way to handle these modifiers in a backend?

**Comment by hazedav** [comment]
I am having a similar issue.  TLDR is that I believe the value is already transformed prior to the backend call to "generate"...

1.  I see that `generateMapItemNode` is looking for values that have a `SigmaTypeModifier`:
```
        elif isinstance(value, SigmaTypeModifier):
            return self.generateMapItemTypedNode(transformed_fieldname, value)
```

2. Which seems to imply that a custom backend should implement:

```
    def generateTypedValueNode(self, node):
```

However, when I debug this I am noticing that the type for fieldname/value (i.e. for `userIdentity.arn|contains`) is always `str`, so this code path does not execute...  Furthermore when we get into `generateMapItemNode` the value is already wrapped in wildcards.

The wildcard wrapping is happening as part of `class SigmaContainsModifier` which gets called via:
sigmac.py:main() -> collection.py:SigmaCollectionParser:__init__() -> rule.py:SigmaParser:__init__() -> rule.py:SigmaParser:parse_sigma() -> condition.py:SigmaConditionParser:parseSearch() -> condition.py:convertId() -> rule.py:parse_definition_byname() -> rule.py:parse_definition() -> discovery.py:apply_modifiers()`

It is at this juncture that sigmac applys the modifier:
```
def apply_modifiers(value, modifier_list):
    print('entering apply modifiers')
    """
    Apply modifiers to value.

    value: value from Sigma rule
    modifiers: list of modifier names
    """
    print(value)
    print(modifier_list)
    for modifier in modifier_list:      # apply modifiers in given order
        value = modifiers[modifier](value).apply()
    return value
```

The best I could come up with was to hack `generateMapItemNode`:
```
    def generateMapItemNode(self, node):
        fieldname, value = node

        transformed_fieldname = self.fieldNameMapping(fieldname, value)

        if value.startswith('*') and value.endswith('*'):
            value = value[1:-1]
            return f"contains({transformed_fieldname}, '{value}')"
        ...
```

David

**Comment by thomaspatzke** [comment]
pySigma improved this by providing dedicated types for all Sigma elements. Concretely, there's a SigmaDetectionItem object that keeps all information regarding modifers, original values etc. and the backend base classes already contain implementations for generation of optimized startswith/endswith/contains queries that can be utilized by simply providing query templates.
