### ISSUE TITLE
Rar with Password or Compression Level - generate massive amount of FP

### ISSUE THREAD

**Issue by GelosSnake** [SigmaHQ/sigma#883]
The following rule: Rar with Password or Compression Level is configured very badly basically taking every process with command lines: -hp or -m and alerting on it.

I recommend deducting this rule from the repository until it is better configured.

https://github.com/Neo23x0/sigma/commits/f2587791f2a07fcda15428a1e8dd78796aee6953/rules/windows/process_creation/win_susp_rar_flags.yml

An example FP trigger:
"C:\\WINDOWS\\system32\\CompatTelRunner.exe -m:appraiser.dll -f:UpdateAvStatus -cv:+1LU2tvO

**Comment by frack113** [comment]
Last update rule is 2022/03/16
Now trigger only if you use plain password in commandline
