### ISSUE TITLE
Question : Can anyone help to find option for -c as syslog ?

### ISSUE THREAD

**Issue by Ashjavi** [SigmaHQ/sigma#902]
I have been able to convert rules using the --help option 
For example:
./tools/sigmac -t graylog -c windows-audit ./rules/windows/process_creation/win_susp_control_dll_load.yml

to create a rule for target (-t) as graylog search query and configuration (-c) as windows-audit

What if the logs being received are in plain old syslog format ?

**Comment by thomaspatzke** [comment]
Syslog means unparsed or non Windows logs?

**Comment by Ashjavi** [comment]
What i meant by syslog is the standard format defined under IETF RFC 5424. rsyslog and syslog-ng are some examples of utilities that handle syslog formatted messages. For windows this is done using nxlog.

The syslog header format defines fields for information like timestamp, hostname, application name, and process ID. The message itself, however, is free text. If there is particular part of the message you’re interested in, the application consuming the logs will need to extract it from the message.

But there’s also another way to include structured data with syslog. The syslog standard allows for a section in the message header, called Structured Data (SD) to include key-value pairs that can be easily parsed and interpreted. 

Hope this helps with my question.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
