### ISSUE TITLE
Feature Request: Audit Config Resources

### ISSUE THREAD

**Issue by nterl0k** [SigmaHQ/sigma#938]
SIGMA is a wonderful resource, the only thing currently lacking is a comprehensive audit configuration resource. Resilient detection rules are wonderful, but only when they have the proper logs to detect on. 

Is there is any work in progress on what audit configurations need to be inplace for the log sources (linux audit, windows LPO/GPO settings, sysmon configurations, etc)? 

An endorsed Sysmon config?
Specific Windows auditing GPO template?

Kindly direct me to anything already built.

**Comment by Neo23x0** [comment]
There are other projects that do exactly that : 

https://github.com/atc-project/atomic-threat-coverage

**Comment by nterl0k** [comment]
Thanks for the link, apologies if I'm being daft about the mission of this repo.

I agree ATC has a portion of this ask. Tho the last time I looked at them, the Sysmon recommendations vary from "here's a sample of Swift's config start here" to "This is off by default(normally because super noisy), set to exclude nothing and tune out stuff".

I was hoping for something a bit more prescriptive that worked against rule base. I was wondering if it would make sense to add a Sysmon "target" to sigmac that would generate a Sysmon configuration file based on whatever rules are given to it?

Sysmon config generated could be easily appended to any well known/existing Sysmon config to insure maximum detection accuracy...I do recognize it's a bit narrow focus versus "log all things" which can catch more, but at the cost of $/retention length in some places.

I know sigma is about making detections easy and since Sysmon is relied on heavily that seemed like a good fit.

Thanks for such a quick reply, eager to continue this dialog! :)

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
