### ISSUE TITLE
[Wiki] Separating wiki pages into development areas

### ISSUE THREAD

**Issue by aw350m33d** [SigmaHQ/sigma#959]
Currently the wiki is not structured, all pages are mixed in one space. Default side panel contains the specification, the rule creation guide, etc. I propose to create separate sections for those areas of knowledge about Sigma that might be useful. 

In my opinion, there are three main areas of project development: 
1. syntax and language constructions, 
2. enriching repository with new rules and updating existing ones, 
3. converter development and writing backends for it.

At the moment I suggest the following sections (example https://github.com/aw350m33d/sigma/wiki):
•	`General` - general information and answers to frequently asked questions
•	`Syntax` – everything related to the syntax and description of language constructs.
•	`Rule Creation` - information on rules writing, guides, helpful tips, etc.
•	`Sigmac converter` - everything about converter: how it works, how to create your own backends and mappings.

If anyone has alternative proposal on sections split, let's discuss it here.

**Comment by nterl0k** [comment]
I like your proposal, i'd like to suggest adding a section to the Wiki that contains current rules with general info about them. Name,Description,tags, etc

For my own needs I made a simple PowerShell script to parse all the existing rules into a simple csv/xls to see/sort the rules versus needing to drill into each one individually. This was for my own purposes for a use-case comparison project, but I could see this also being helpful for new user/authors finding things easier.

I'm happy to share code.

**Comment by aw350m33d** [comment]
Thanks for your comment and for the script. 
I like the idea of ​​a rules summary, but I can't figure out how to keep such a summary up to date without manually transferring the script results to the wiki. Because it seems to me that very few people will want to constantly do this work for a long time.
If this question is not thought out, then in a couple of months the list will not be entirely relevant. I ran into this situation when I was doing visualizations for my articles on Sigma rules (https://habrastorage.org/webt/tx/sq/8a/txsq8abx8lji-v70cqso1q6x6su.png and https://habrastorage.org/webt/tj/ov/ik/tjoviknbfjenrhvh4sngo6vqyuq.png). After a while, the diagrams had to be redone, because the set of rules changed slightly.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
