### ISSUE TITLE
[Wiki] Translation of the wiki into Russian

### ISSUE THREAD

**Issue by aw350m33d** [SigmaHQ/sigma#960]
I have translated the wiki into Russian and added a new sidebar for navigation and language selection. Thanks to one kind person for the idea of ​​how to implement the markup. Proposed wiki design will enable multilingual project support, which will help beginners from different countries to get started more easily with the project. The translation can be found [here](https://github.com/aw350m33d/sigma/wiki)

Additionally I’ve created an issue about dividing the wiki into sections. Now all the pages come as a single flow, while I believe it would be more convenient to have separate sections for different areas of activity. Get more details via this link: https://github.com/Neo23x0/sigma/issues/959

I’ve tried to translate the text 1-to-1 with the only exception – one more link added to the list of guides with my articles about Sigma rules in Russian.

Let’s discuss proposed translation in this issue if anyone has any comments or inputs.

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
