### ISSUE TITLE
escaping characters

### ISSUE THREAD

**Issue by crimsoncore** [SigmaHQ/sigma#973]
Hey guys, 

I have a question about escaping characters.

running ELK 7.8, winlogbeat 7.8 with ECS modules enabled and Sigmatools-0.18.0

sigmac -I -t es-qs -c /opt/sigma/tools/config/winlogbeat-modules-enabled.yml /opt/threathunt/sigma_rules/win_crimsoncore_regsrv32.yml --backend-option keyword_base_fields="*"

this outputs a wrong format that yields no results in Kibana : (process.executable:*\\regsvr32.exe)

The correct output should have "" around the *\\regsvr32.exe - so the working query should be:

process.executable: "*\\regsvr32.exe"

However in Kibana this works (with the .keyword):

process.executable.keyword :*\\regsvr32.exe

Bug?

Cheers,
Luk

**Comment by Neo23x0** [comment]
Hi, I can feel your pain and it is caused by Elastic. Sorry, but it is true. 

See :
https://github.com/Neo23x0/sigma/tree/master/tools#elastic---some-final-examples

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
