### ISSUE TITLE
About wildcard logic(ver.0.17.0) in API default_value_mapping changed (sigma/backends/ala.py)

### ISSUE THREAD

**Issue by william-su** [SigmaHQ/sigma#983]
Dear Author,
Thank you for contributing sigma this awesome library.

I found that wildcard logic in ver 0.16.0 is more suitable than 0.17.0.
**Logic of wildcard in 0.16.0 as below:**
- [*keyword] will be transformed to [endswith keyword]
- [keyword*] will be transformed to [startswith keyword]

**But logic of wildcard in 0.17.0 has been changed as below:**
- [*keyword] will be transformed to [contains keyword]
- [keyword*] will be transformed to [contains keyword]

May I know what is the main reason for the changed in 0.17.0?
Will you consider to rollback the wildcard logic to ver 0.16.0?

Thank you and looking forward for your reply.

Source code information is as below:
1) v0.16.0
**File :** https://github.com/Neo23x0/sigma/blob/0.16.0/tools/sigma/backends/ala.py
**API :** def default_value_mapping(self, val):
**Line :** 119~124
2) v0.17.0
**File :** https://github.com/Neo23x0/sigma/blob/0.17.0/tools/sigma/backends/ala.py
**API :** def default_value_mapping(self, val):
**Line :** 117~118

**Comment by frack113** [comment]
Sorry this post is closed automatically because it is not more active
